#+TITLE: PHYS 1062 Notes

* Unit 1 - Part 2 - Jan 20

** What Did You Learn in Part 1

- Reading Assignment: 18.1-18.2

  + Part 1 lecture (not delivered) note posted on Canvas

  + How to Solve Physics Problems?

  + The IDREA Framework

  + Macroscopic description in terms of state variables (mass- M, number of mules -n, volume -V, pressure -p)

** What You're Learning

- Reading Assignment: 18.3-18.6

  + What is temperature? (read only)

  + Thermal expansion

  + Phase changes (read only)

  + What is an ideal gas?

** Thermal Expansion

- Fact: Most micro objects expand when heated.
  There are two laws of thermal expansion:

  + Consider a solid object of length L that changes by \(\Delta L\) when the temperature is changed from \(T\) to \(T + \Delta T\).

  + The law of linear thermal expansion holds:

    a. For most solid materials, \(\Delta L / L\) is proportional to \(\Delta T\) with a proportionality coefficient \(\alpha\) called the material's cofficient of linear expansion

- Fact: For liquids and gases, the volume expansion is the only meaningful concept.

  + For most fluids and solids, the law of volume thermal expansion holds:
       \[\frac{\Delta V}{V} = \beta \Delta T\]

    a. For liquids, \(\beta\) is much greater than for solids (used in thermometers!)

    b. For gases, \(\beta = 3400 \times 10^{-6}\) is large and universal

    c. For uniform solids, \(\alpha\) (see 18.8) and \(\beta\) are related (derive it!):
       \[\beta_{\text{solid}} = 3 \alpha\]

*** QuickCheck #1

A steel plate has a 2.000-cm-diameter hole through it.
If the plate is heated, what happens to the diameter of the hole?

- It increases.

*** Applications, Example 1 (18.3)

A 55m-long pipe runs from one side of refinery to the other.
By how much does the pipe expand on a 5.0°C winter day when 155°C oil is pumped through it?

- Interpret: What is the problem about?

  + We will use the law of linear expansion, assuming that the pipe is heated by 150°C

  + We assume that the pipe is uniform, made of the same material throughout, e.g. steel

  + Predict: we expect small, several cm expansion

- Represent: Introduce symbols for...

  + \(\alpha = 1.1 \times 10^{-5}^{\circ} C\)

  + \(L = 55 \text{ m}\)

  + \(\Delta T = 150^{\circ} C\)

  + The target quantity is \(\Delta L = \;?\)

  + Make a sketch

- Develop: a symbolic plan for solving the problem

  + \(\Delta L = \;?\) From the law of linear expansion, we can find: \(\Delta L = \alpha L \Delta T\)

- Evaluate: your answer

  + In cm:
    \[\Delta L = \alpha L \Delta T = 1.1 \times 10^{-5} \times 5.5 \times 10^3 \times 150 = 9.075 \approx 9.1 \text{ cm}\]

- Assess your answer: We use cm as the units. 2 sig. figs.

  + About 9 cm is a very small fraction of 5,500 cm, so the pipe as a whole has expanded very little.
    The answer is reasonable-as predicted.

*** Applications, Problem 1

A steel gas tank can hold 70L at 20°C.
It's filled to the brim with gasoline at 20°C.
If the temperature now increases to 40°C, how much gasoline spills out?

- Interpret: What is the problem about?

  + Assume that both the gasoline and tank expand following the law of volume expansion.

  + The tank container expands as the volume steel filler.

  + Predict: Out of the two, the gasoline expands more and that's why it spills.

- Represent: Introduce symbols...

  + \(\beta_{\text{steel}} = 3 \times 1.1 \times 10^{-5} / ^{\circ}C\)

  + \(\beta_{\text{gasoline}}\)

- Develop: a plan for solving

  + \(V_{\text{spill}} = \;?\)

    \begin{align*}
    V_{\text{spill}} &= V_{\text{f,gas}} - V_{\text{f,steel}} \\
    &= \Delta V_{\text{gas}} - \Delta V_{\text{steel}}
    \end{align*}

  + \(\Delta V_{\text{gas}} = \;?\)

  + \(\Delta V_{\text{steel}} = \;?\)

  + For both we use the law of volume expansion \[\Delta V = \beta V_0 \Delta T\]

- Evaluate: your answer

  \begin{align*}
  \Delta V_{\text{gas}} &= 1.334 \approx 1.3 \\
  \Delta V_{\text{steel}} &= 0.0462 \approx 0.05 \\
  V_{\text{spill}} &= 1.3
  \end{align*}

- Assess: to the nearest tenth L, about 1.3 L

** Ideal Gas Model

- Important experimental fact: For gases that are (a) not too dense and (b) well above the condensation point

  + We observe a simple relationship (called ideal gas law or model) between the state variables: n, its volume V, pressure p, and absolute temperature T:
    \[pV = nRT \quad \text{(ideal-gas law)}\]

  + Where \(R\) is the universal gas constant: \(R = 8.31 \text{ J/mol K}\)

  + In terms of the number of particles in the gas:
    \[pV = Nk_B T \quad \text{(ideal-gas law)}\]

  + Where N is the number of molecules and \(k_B\) is Boltzman's constant:
    \[k_B = 1.38 \times 10^{-23} \text{ J/K}\]

- Q: What units to use when working with the ideal gas equation?

  + In metric system: T in K, p in Pa, and V in \(m^3\)

  + In laboratory units: T in K, p in atm, and V in liters

  + Conversion between these two systems:

    - 1L = 1000 cm^3 = 10^{-3} m^3

    - 1 atm = 1.013 * 10^5 Pa

  + The gas constant in these two systems has different values:

    \begin{align*}
    \end{align*}

  + Useful fact: If the amount of gas does not change in a process, ideal gas law implies:
    \[\frac{}{} = \frac{}{}\]

*** Applications, Example 2 (18.4)

What is the pressure (in atmospheres) inside a 600-mL container holding 100 g of oxygen gas at 150°C?

- Interpret: What is the problem about?

  + Assume that the oxygen is ideal and diatomic gas

  + Use the ideal gas law in laboratory units

  + Counting moles method---see Part 1

- Represent: Introduce symbols for...

- Develop: a symbolic plan for solving the problem:

  + p = ? From Eq. 18.13--the IGL, we can calculate the pressure if we know the number of moles = n, volume and the absolute temperature: \[p = nRT / V\]

  + n = ? From Eq. 18.4, we can calculate the number of moles of oxygen from the mass of the sample in grams = M and the atomic weight in grams per mol: \[n = M / M_{\text{mol}}\]

** Solving Problems with Thermal Expansion, Problem 1 (in-class problem)

An ordinary glass is filled to the brim with 350.0 mL of water at 100.0°C.
If the temperature decreased to 20.0°C, how much water could be added to the glass (in mL to the nearest tenth of mL)?

Hint: Assume that both the glass container and water contractt when the temperature falls; use the following values: \(\beta_{\text{glass}} = 27 \times 10^{-6}\) and \(\beta_{\text{water}} = 210 \times 10^{-6}\)

Upload your solution on the IRDEA worksheet for grading using the Canvas link.

* Unit 1 - Part 3 - Jan 22

** In-class problem #1

An ordinary glass is filled to the brim with 350.0 mL of water at 100.0°C.
If the temperature decreased to 20.0°C, how much water could be added to the glass?
Hint: Assume that both glass and water contract when the temperature falls with \(\beta_{\text{glass}} = 27 \times 10^{-6}\) \(\beta_{\text{water}} = 210 \times 10^{-6}\)

** What You're Learning

Reading Assignment: 18.7

1. What are the pV diagrams?

2. What are ideal gas processes such as

   a. quasi-static

   b. isochoric

   c. isobaric

   d. isothermal

** The pV Diagrams

Recall from Part 2: For all gases in thermal equilibrium an important relation (ideal gas model) holds:

\[pV = nRT \quad \text{(ideal-gas law)}\]

- R is universal gas constant: R = 8.31 J/(mol*K)

- Consider a fixed amount of ideal gas in a /sealed/ container, where n is fixed.

- In such a case, knowing p and V, we can find T by using the ideal gas model.

- So a point (p, V) on a pV diagram give us a complete identification of a state of the gas [= (p, V, n, T)]

** Quasi-static Processes

- Def: An ideal gas process is the means by which the gases changes from one state to another.

- Recall: IG Law applies only to gases in thermal equilibrium.

- An important model: slow change that the system remains always in thermodynamic equilibrium and follows /a path/ in its pV diagram.

** Ideal-Gas Processes

- Now, we will name three basic processes, included on the pV diagram below:

  path 1 is a vertical line, path 2 is a horizontal line, path 3 is a hyperbola

  a) constant V path #1 is called isochoric

  b) constant p path #2 is called isobaric

  c) constant T path #3 is called isothermal

** Constant-Pressure Process

- Consider a cylinder of gas with a tight-fitting piston of mass \(M\) that can slide up and down but seals the container.

- A small flame heats the cylinder, causing the piston to slowly move upward.

- For the gas inside the cylinder, the process is occurring at constant pressure.

- In equilibrium, the gas pressure inside the cylinder is fixed at _____

** Applications, Example 1 (Example 18.7)

A constant volume-gas thermometer is placed in contact with a reference cell containing water the triple point (273.16K).
After reaching equilibrium, the gas pressure is recorded at 55.78 kPa.
The thermometer is then placed in contact with a sample of unknown temperature.
After the thermometer reaches a new equilibrium, the gas pressure is 65.12 kPa.
What is the temperature of this sample (in °C)?

- Interpret: What is the problem about?

  1) The thermometer's volume doesn't change, so this is an isochoric process

  2) The gas is in a sealed container, so we can use the IGL in the form of pV/T ratio

  3) Predict: the temperature will increase

- Represent: Introduce symbols for...

  + \(T_1 = 273.16 \text{ K}\)

  + \(p_1 = 55.78 \text{ kPa}\)

  + \(p_2 = 65.12 \text{ kPa}\)

- Develop: a symbolic plan for solving the problem:

  1. \(T_2\) in \(K = \;?\) From IGL in the ratio form, we can calculate \(T_2\):

     \begin{align*}
       \frac{T_{2}}{V_{2}p_{2}} &= \frac{T_{1}}{p_{1}V_{1}} \\
       T_{2} &= \frac{T_{1}}{p_{1}p_{2}V_{1}V_{2}}
     \end{align*}

  2. \(V_2 = \;?\) The process is isochoric so \(V_2 = V_1\)

  3. Final expression is \[T_2 = \frac{T_1 p_2}{p_1}\]

- Evaluate: your answer

\begin{align*}
T_2 &= \frac{T_1 p_2}{p_1} = 318.899 \text{ K} \\
T_2 \text{ in } ^{\circ}\text{C}&= T_2 - 273.15 = 45.75^{\circ}{\text{C}}
\end{align*}

- Assess

  + \(T_2 > T_1\) which is reasonable (increase!)

** Applications, Example 2 (Example 18.11)

A gas at 2.0 atm pressure and a temperature of 200°C is first expanded isothermally until its volume has doubled.
It then undergoes an isobaric compression until it returns to its original volume.
Find the final temperature (in °C).

- Interpret: What is the problem about?

  1) 1->2 is isothermal expansion

  2) 2->3 is an isobaric compression

  3) The gas is ideal and in a sealed container

  4) Prediction: we expect \(T_3 \ll T_1\)

- Represent: Introduce symbols for...

  \begin{align*}
    T_1 &= 473 \text{ K} \\
  \end{align*}

- Develop: a symbolic plan for solving the problem

  1. \(T_3\) in \(K = \; ?\) From IGL in a sealed container (the ratio form) for the process isobaric 2->3

     \begin{align*}
       \frac{p_{3}V_{3}}{p_{2}V_{2}} &= \frac{T_{3}}{T_{2}} \\
       \frac{V_{3}}{V_{2}} &= \frac{T_{3}}{T_{2}} \\
       T_{3} &= \frac{T_{2} V_{3}}{V_{2}}
     \end{align*}

  2. \(T_2 = \; ?\) \(T_2 = T_1\) because 1->2 is isothermal

  3. \(V_3 = \; ?\) \(V_3 = V_1\) because the final volume equal to initial volume

  4. \(V_2 = \; ?\) \(V_2 = 2V_1\) \(T_3 = \frac{T_1 V_3}{V_2} = \frac{T_1 V_1}{V_2}\)

- Evaluate: your answer

  \[T_3 \text{ in } ^{\circ}\text{C} = \]

* Unit 2 - Part 1 - Jan 25

** What You're Learning

Reading Assignment 19.1 - 19.4

- About a generalization of work-energy theorem to thermal interactions (read only).

- What is heat?

- How to calculate the work done on a gas by changing its volume?

** Introduction

Fact. Any macro system has internal structure and has internal energy.
We will call it thermal energy.

Def. Thermal energy is the combination of kinetic and potential energy of the molecules.

Q. How can we change thermal energy of a system?

   Recall the work-energy theorem the work done by external forces changes the total energy of a mechanical system

   \[\Delta E_{\text{sys}} = \Delta E_{\text{mech}} + \Delta E_{\text{th}} = W_{\text{ext}}\]

** The Missing Piece: Heat

In the 1840s, James Joule showed that there are two completely equivalent ways to change a system's thermal energy.

1. Mechanical interaction. Doing mechanical work, symbol W.
   Macroscopic pulls and pushes acting over a distance.

2. Thermal interaction. Flow of heat, symbol Q.
   Energy flow resulting from a temperature difference between the environment and the system.

** The First Law of Thermodynamics

The change in \(E_{\text{th}}\) depends *only* on the net energy transferred, i.e., the net heat added _to_ the system plus the net work done _on_ the system.

\[\Delta E_{\text{th}} = W + Q\]

Assess. Q and W are not state variables but \(E_{\text{th}}\) is.

Q and W /depend on the process but/ \(\Delta E_{\text{th}}\) is independent of the process.
** Sign conventions

We adopt the following sign conventions in setting up the equation \[\Delta E_{\text{th}} = W + Q\]

- \(Q > 0\) (energy added) when the environment is hotter than the system (\(T_{\text{env}} > T_{\text{sys}}\))

- \(Q < 0\) (energy extracted) when the system is hotter than the environment (\(T_{\text{sys}} > T_{\text{env}}\))

- \(Q = 0\) (no energy transfer) when the system is in thermal equilibrium with the environment (\(T_{\text{sys}} = T_{\text{env}}\))

** SI unit of heat

The SI unit of heat (symbol Q) is the Joule.

Historically, a unit for measuring heat, the calorie, had been defined as 1 calorie = 1 cal = the quantity of heat needed to change the temperature of 1 g of water by 1°C.

In today's SI units, the conversion is 1 cal = 4.186 J.

** Example 1 (Exercise 19.11)

500 J of work are done on a system in a process that decreases the system's thermal energy by 200 J.
How much heat energy (in J) ins transferred to or from the system?

Develop. Using the 1st law of TD, \(\Delta E_{\text{th}} = Q + W\), we solve for Q and get \(Q = \Delta E_{\text{th}} - W\).

Evaluate. Substituting for \(\Delta E_{\text{th}}\) and \(W\), we find \[Q = -200 - 500 = 700 \text{ J}\]

Assess. The negative sign means the heat is transferred from the system to the environment.

** Work in Ideal-Gas Processes

Q. How to calculate W = the work done on a macroscopic system?

Consider a sample of gas in a cylinder under a movable piston.

Q. Why ideal gas?

Recall. A state of thermal equilibrium of a fixed amount of ideal gas is completely determined by only two quantities: (p, V) or (p, T) or (V, T). So
#+begin_quote
Any process carried out slowly enough to be quasi-static is a path (or a curve) in its pV diagram.
#+end_quote

We will be able to use tools of calculus to calculate the work done _on_ the gas during ideal-gas process.

** Work in Ideal-Gas Processes (Piston Example Explanation)

Consider again the gas cylinder sealed at one end by a movable piston.

If the piston moves slowly a small distance dx, the external force (i.e., the environment) does the work (force * displacement):

\[dW_{\text{ext}} = (F_{\text{ext}}) \; dx = -(F_{\text{gas}}) \; dx = -(pA) \;dx = -p \;dV\]

Fact. The work _on_ the gas, as V changes, from \(V_i\) to \(V_f\), can be obtained by integrating the infinitesimal quantities \(dW_{\text{ext}}\): \[W_{\text{ext}} = -\int_{v_i}^{v_f} p \;dV \quad \text{(work done on a gas)}\]

** Geometric Interpretation of Work in Ideal-Gas Processses

On a pV diagram, W = the work done on a gas W has a simple geometrical interpretation:

\[W = -\text{(the AREA under the pV curve)}\]

1. For expansion (\(V_f > V_i\)), AREA > 0, W < 0

2. For compression (\(V_f < V_i\)), AREA < 0, W > 0

** Example 2 (Exercise 19.2)

How much work is done (in J) in the ideal gas process of the figure below?

Interpret. What is the problem about?

- The work = -(the area under the pV curve).

- From geometry: the area under the curve can be divided into a rectangle and a triangle.

- Predict: W positive, because the environment does positive work on the gass to compress it.

Represent. Introduce symbols for the knowns and target:

\begin{align*}
V_i &= 300 \text{ cm}^3 \\
V_f &= 100 \text{ cm}^3 \\
p_i &= 200 \text{ kPa} \\
p_m &= 400 \text{ kPa}
\end{align*}

Develop.

\(W_{i \to f} = \; ?\) From geometry: the area under the curve can be divided into a rectangle and a triangle. Final expression: \[W_{i \to f} = -\left[p_i(V_f - V_i) + \frac{1}{2} (p_m - p_i) (V_f - V_i)\right]\]

Evaluate.

\[W_{i \to f} = -\left[-(200)(200) - \frac{1}{2} (200) (200)\right] = 60 \text{ J}\]

Assess.

- The results presented in Joules.

- Positive as expected because a compression of a gas is involved (\(V_f < V_i\))

** Recall from Unit 1

1. In an isochoric process (V = const) no work is done. \[W = 0\]

2. In an isobaric process (p = const) and the volume changes by \(\Delta V = V_f = V_i\), the work done during the process is \[W = -p \Delta V\]

3. In an isothermal process, when temperature is a constant, the work done is (derive it using calculus) \[W = -nRT \ln{\left(\frac{V_2}{V_1}\right)}\]

** Example (QC) (Example 19.2)

How much work does it take to compress 7.0 g of a nitrogen gas to half its original volume while maintaining a constant 80°C temperature?

Interpret.

- The work on an ideal gas in T = const compression.

- Predict: the work is positive because compression.

Represent.

\begin{align*}
M &= 7.0 \text{ g} \\
M_{\text{mol}} &= 2.8 \text{ g} \\
R &= 8.314 \\
T &= 80 + 273 = 353 \text{ K} \\
V_2 &= \frac{V_1}{2} \\
W &= \; ?
\end{align*}

- Make an isothermal sketch.

Develop.

1. \(n = \; ?\) From counting moles, \(n = \frac{M}{M_\text{mol}}\).

2. \(W = \; ?\) from the previous s (T = const) => \(W = nRT \ln{\left(\frac{V_2}{V_1}\right)}\)

Evaluate.

** Work Depends on the Path (Read Onlyy)

1. To evaluate the integral, you must know a function: p(V) and i & f states.

2. The work done during an IG process depends on the path following through the pV diagram.

3. Work is additive. For a multi-step process 1 -> 2 -> 3, the work has to be calculated separately for each step in the process.

** Problem 1 (19.52 (b)) (CALC)

An ideal-gas process is described by \(p = cV^{1/2}\), where \(c\) is a constant.
0.033 mol of gas at an initial temperature of 150°C is compressed, using this process, from 300 cm^3 to 200 cm^3. How much work is done (in J) on the gas?

Interpret.

- Work in ideal-gas process

- Predict: compression, so positive work

Represent.

\begin{align*}
n &= 0.033 \text{ mol} \\
R &= 8.314 \\
T_1 &= 423 \text{ K} \\
V_1 &= 300 \text{ cm}^3 \\
V_2 &= 200 \text{ cm}^3 \\
W &= \; ?
\end{align*}

Develop.

1. \(W = \; ?\)

2. \(c = \; ?\) \(c = \frac{p_1}{{V_1}^{1/2}} = \frac{nRT_1}{{V_1}^{3/2}}\)

3. \(p_1 = \; ?\) IGL. \(p_1 = \frac{nRT}{V_1}\)

Evaluate.

\[W = 35 \text{ J}\]

Assess.

Reasonable because positive.

** Problem 2 (Problem 19.49 (a))

Answer: ≅ 5.5 kJ

* Unit 2 - Part 2 - Jan 27

** What You're Learning

Reading Assignment: 19.3 - 19.6

1. What is heat?

2. What are some thermal properties of matter, such as specific heat and heat of transformation?

** What Did You Learn in Part 1

The first law of TD:

\[\Delta E_{\text{th}} = W + Q\]

** Heat
** Thermal Properties of Matter: Specific Heat

- Let us start with T change... Assume W = 0.

- Fact: The amount of heat required Q to... is directly proportional to M & ΔT: \[Q = cM\Delta T = \Delta E_{\text{th}}\]

- The thermal property called the specific heat is important here:

  + Def. The amount of energy that raises the temperature of 1 kg of a substance by 1 K is called the specific heat c of that substance.

- \(Q = Mc \Delta T\) (temperature change)

- Alternatively we use: The molar specific heat C as the amount of energy that raises the temperature of 1 mole of a substance by 1 K: \[Q = nC \Delta T\]

** Example 1 (Exercise 19.13 (b))

A rapidly spinning paddle wheel raises the temperature of 200 mL of water from 21°C to 25°C.
How much (a) heat is transferred and (b) work (in kJ) is done in this process?

Interpret: What is the problem about?

- The questions about Q & W.
  We will use the 1st law of TD.

- To solve it, we have to assume that no energy is transferred between the system and the environment due to a difference in temperature -- the key word: rapidly.

Represent.

- M = 0.200 kg
- c_w = 4190 J/(kg*K)
- ΔT = 4.0K
- 1 L H_2O = 1 kg
- Targets: Q = ? W = ?
- Make a sketch.

Develop.

a) Q = 0
b) W = ? From 1st law, W = ΔEth = c_w MΔT

Evaluate.

\[W = c_w M \Delta T = (4190)(0.200)(4.0) = 3352 \approx 3.4 \text{ kJ}\]

** Thermal Properties: Heat of Transformation

- Suppose we start with a 1-kg system in its solid phase and heat it at a steady rate.
  \(c\) can be measured from the slope of the linear increases.

- There are 4 more thermal properties on the graph: \(T_m\), \(T_b\), \(L_f\) and \(L_v\)

- If W = 0, the heat required for a system of mass M to undergo a phase change is
  \begin{align*}
    Q = \begin{cases}
        \pm ML_f & \text{melt/freeze} \\
        \pm ML_v & \text{boil/condense}
    \end{cases}
  \end{align*}

** Example 2 (Exercise 19.15)

How much heat (in kJ) is needed to change 20 g of mercury at 20°C into mercury vapor at the boiling point?

Interpret.

- About a change of T and boiling.
  Two steps are involved from 20°C and T_b = 357°C

- We use the law of specific heat and the law of heat of transformation, respectively.

- Energy is additive

Represent.

- M = 0.020 kg
- ΔT = 337 K
- \(c_{\text{Hg}}\) = 140 J/kg*K
- L_v(Hg) = 2.96 × 10^5 J/kg
- target: \(Q_{\text{tot}} = \; ?\)
- Make a sketch.

Develop.

- \(Q_{\text{total}}\) = ? There are two portions. Energy is additive: \[Q_{\text{tot}} = Q_1 + Q_2\]

- \(Q_1\) = ? Specific heat \(Q_1 = M c_{\text{Hg}} \Delta T\)

- \(Q_2\) = ? Heat of vaporization: \(Q_2 = ML_v\)

- The final expression: \(Q_{\text{tot}} = M c_{\text{Hg}} \Delta T + ML_V\)

Evaluate.

- 6.9 kJ

Assess.

** Calorimetry

- Consider two systems with different temp.
  \(T_1\) and \(T_2\) that can interact thermally with each other but are isolated from everything else.

- Fact: Heat will flow by itself (spontaneously) from the hotter to the colder system until they reach a common final temperature \(T_f\).

- Q: How to find \(T_f\)?

- Answer: COE Principle: If \(Q_1\) is the heat transferred from system 1, and \(Q_2\) is the energy transfer to system 2, the fact that no energy is exchanged with the environment

- It means as an eq: \[Q_{\text{net}} = Q_1 + Q_2 = 0\]

- In general, \[Q_{\text{net}} = Q_1 + Q_2 + Q_3 + \cdots = 0\]

** Problem 1 (Problem 19.47)

Your 300 mL cup of coffee is too hot to drink when served at 90°C.
What is the mass of an ice cube, taken from a ~20°C freezer, that will cool your coffee to a pleasant 60°C?

Interpret.

- About two interacting systems (coffee=water & ice) isolated form the rest and energy is conserved (COE)

- Lowering the coffee temp. of coffee (1 step) requires 3 steps involving the ice

Represent.

Develop.

- \(M_{\text{ice}}\) = ? From COE: \(Q_{\text{ice}} = Q_w = 0\)

- \(Q_{\text{ice}}\) = ? 3 steps.
  Use the law of specific heat and the law heat of transformation:
  \[Q_{\text{ice}} = +c_{\text{ice}} \times M_{\text{ice}} \times \Delta T_{\text{ice}, 1} + M_{\text{ice}} \times L_F + c_w \times M_{\text{ice}} \times \Delta T_{\text{ice}, 2}\]

- \(Q_w\) = ? From the law of specific heat we do have \(Q_w = c_w \times M_w \times \Delta T_w\)

- Adding these two and solving for \(M_{\text{ice}}\) one obtains final expression
  \[M_{\text{ice}} = (-c_w \times M_w \times \Delta T_w) / (c_{\text{ice}} \times \Delta T_{\text{ice}, 1} + L_F + c_w \times \Delta T_{\text{ice}, 2})\]

Evaluate.

- 60 g

Assess.

- A small value, so we will use the prefix units: grams, 2 sig. figs.

** In-class Problem

2.0 mol of gas are at 30°C and a pressure of 1.5 atm.
How much work (in kJ) must be done on the gas to compress it to one third of its initial volume at constant pressure.
Show the process on a pV diagram.

Interpret.

- Isobaric
- Ideal-gas law
- Constant pressure

Represent.

Develop.

- W = -pΔV
- p = nRT / V

Evaluate.

Assess.

* Unit 2 - Part 3 - Jan 29

** What Did You Learn in Part 2
** What You're Learning

- Reading Assignment: 19.7

- The molar specific heats of gases (C_p and C_v)

- What is an adiabatic process?

- How to calculate the work and heat transfer in an adiabatic process?

** The Molar Specific Heats of Gases

- Recall: We can quantify the heat transfer in terms of moles \[Q = nC\Delta T\]

- Where C is called the molar (per mole) specific heat.

- In an isochoric (V=const) process, Q_v and ΔT are related by \[Q_v = n C_v \Delta T\]
  here C_v is the molar specific heat at constant volume.

- For V=const, W=0, then 1st law gives \(\Delta E_{\text{th}} = Q_v\), or \[\Delta E_{\text{th}} = nC_v \Delta T \quad \text{(any ideal-gas process)}\]

- ASSESS: Since \(E_{\text{th}}\) is a state variable, so this relationship is valid for ANY process with ideal gas.

** C_p and C_v

Note three interesting features:

1. The values of C_V, (at T=0°C), for monatomic gases are clustered around (3/2) R = 12.5

2. The values of C_V, (at T=0°C), for diatomic gases are clustered around (5/2) R = 20.8

3. For all idea gases (see below), \[C_p - C_v \approx R\] where R = 8.31 J/mol K is the universal gas constant.

Q: Why these relationships? We will address this in Unit 3.

** C_p and C_v (Read Only)

- Consider two ideal gas processes A and B, A=isochoric and B=isobaric, both start on the T_i isotherm and end on the T_f isotherm.

** Adiabatic Processes

1. Isothermal process (\(\Delta E_{\text{th}} = 0\)), \(W + Q = 0\)

2. Isochoric process (\(W = 0\)), \(\Delta E_{\text{th}} = Q\)

3. Adiabatic process (\(Q = 0\)), \(\Delta E_{\text{th}} = W\)

\[\Delta E_{\text{th}} = W_{\text{adibat}} = nC_V\Delta T\]

Fact. An adiabatic process has the following path: \[pV^{\gamma} = \text{constant} \text{ or } p_f {V_f}^{\gamma} = p_v {V_i}^{\gamma} \text{ or } T_f {V_f}^{\gamma - 1} = T_i {V_i}^{\gamma - 1}\]

* Unit 3 - Part 1 - Feb 1

** What You're Learning

- Reading Assignment: 19.8

- How is heat transferred?

- Three mechanisms:

  + conduction

  + convection (read only)

  + radiation

** Heat Transfer - Conduction

- Recall: we defined heat as the energy that flows between a system and its environment as a result of a temperature difference that exists between them.

- Q. How that transfer take place?

- We will consider three mechanisms of heat transfer:

- Def. Thermal conduction (TC) is heat transfer through direct physical contact.

- Fact. Thermal conduction occurs as molecules in the hotter region collide and transfer energy to those in an adjacent cooler region.

- Fact. Thermal conduction can occur in solids, liquids and gases

- Q. What factors affect the rate of thermal conduction?

- Simple model: A slab of cross-sectional area A and thickness L, whose ends are maintained between \(T_H = T + \Delta T\) and \(T_c = T\) (\(\Delta T > 0\))

- Experimental fact (thermal conductivity law): The rate of heat transfer \(\frac{dQ}{dt}\) is directly proportional to \(A\), \(\Delta T\) and \(\frac{1}{L}\):

  \[\frac{dQ}{dt} = k \frac{A}{L} \Delta T\]

- where \(k\) is the thermal conductivity, which characterizes whether the material is a good conductor of heat or a poor conductor.

- Facts about thermal conductivity:

  + SI units of k: \(W/m \cdot K\)

  + A broad range of values

    - large k for metals; they are good thermal conductors

    - small k for air, foam; they are good insulators

** Example 1 (Example 19.10)

A deep home freezer measures 1.8 m by 1.0 by 0.65 m and is insulated with 5.0 cm-thick Styrofoam insulation.
If the surrounding building is at 25°C, at what *average rate* must the compressor remove heat from the freezer in order to maintain -20°C inside?

Interpret.

- It involves the thermal conductivity law through Styrofoam 6 slabs

- Assume energy balance state: the compressor has to remove heat at the same rate it enters through the wall conduction

Represent.

- a = 1.8 m, b = 1.0 m, c = 0.65 m, L =0.050 m

- ΔT = 45 K, \(k_{SF}\) = 0.035 W/(mK); target: dQ/dT = ?

- Make a sketch.

Develop.

- dQ/dt = ? Energy balance plus the law of conduction: \[\frac{dQ}{dt} = k_{SF} \frac{A}{L} \Delta T\]

- A = ? Simple model with 6 slabs of the total area, from geometry: \[A = 2ab + 2ac + 2bc\]

Evaluate.

- Combining these two results we obtain: \[\frac{dQ}{dt} = \frac{(0.035)(7.24)(45)}{0.05} = 228.06 \approx 230 \text{ W}\]

Assess.

- We present the answer in Watts and keep 2 sig figs.

** Heat Transfer - Convection (Read Only)

Def. Thermal convection, or simply convection, is transfer of thermal energy by the motion of a fluid.

** Heat Transfer - Radiation

- Turn a stove burner to "high" and it glows brightly

- Turn it to "low" and you can still sense its heat; although it doesn't glow visibly.

- Either way, the burner loses thermal energy not by thermal conduction or convection (why?)

- But a by a new mechanism called radiation

- Def. Radiation is heat energy transfer by emission of electromagnetic waves (generated by oscillating electric charges in the atoms that form the object- see Unit 12)

- Interesting fact: The wavelength (=color) of the emitted radiation varies with T

- Law of radiation #1: The rate of thermal radiation dQ/dT from an object at T is directly proportional to the fourth power of its absolute temperature T and to A.
  It also depends on the surface (e): \[\frac{dQ}{dt} = e\sigma AT^4\]

- A = the object's surface area, T = temperature in Kelvins

- The proportionality constant σ is called the Stefan-Boltzmann constant: \[\sigma = 5.67 \times 10^{-8} \text{ W/m}^2 \cdot \text{K}^4\]

- The parameter \(e\) is the emissivity of the surface, a measure of how effectively it radiates. The value of e ranges from 0 to 1.

- Important facts about thermal radiation:

  + Radiation is the dominant heat-loss mechanism at high T

  + Radiation also dominates for objects in vacuum

- Fact. Any object radiates energy and at the same time, it absorbs energy from the environment.

- If a body is surrounded by an enclosure (room) at the ambient \(T_a\) there wukk be an exchange of heat energy between these two.

- Law of radiation #2: The net radiated power from an object at T is \[\frac{dQ_{\text{net}}}{dt} = e \sigma A(T^4 - {T_a}^4)\]

- Assess. A perfect emitter has e = 1 and it is also a perfect absorber (no reflection)

** Example 2 (Example 16.11)

The radius of the sun is 6.96 × 10^8 m.
At the distance of the earth, 1.50 × 10^{11} m, the intensity of solar radiation (measured by satellites above the atmoshere) is 1370 W/m^2. What is the temperature of the sun's surface?

Interpret.

- Thermal radiation (1st law) from the Sun which we assume is a perfect emitter with e=1,

- We also assume COE: power radiated by the Sun is the power received through the surface of a sphere with radius d= at the distance of the earth

- We need the concept of intensity defined as the average power per unit area

Represent.

- R_s = 6.96 * 10^8 m, d = 1.50 * 10^{11} m, e = 1

- S = 1370 W/m^2, σ = 5.67 * 10^{-8} W/(m^2 * K^4); target T = ?

- Make a sketch.

Develop.

- T = ? We solve the first law of radiation for T: \[T = \left[\frac{dQ}{dt} \cdot \frac{1}{e\sigma 4\pi {R_s}^2}\right]^{0.25}\]

- dQ/dt = ? We can find dQ/dt using the COE and the concept of intensity:

  \[\frac{dQ}{dt} = S \cdot 4\pi d^2\]

- Final expression: \[T = \left[\frac{Sd^2}{e\sigma {R_s}^2}\right]^{0.25}\]

Evaluate.

\[T = 5788 \approx 5790 \text{ K}\]

Assess.

This T is confirmed by measurements of the solar spectrum

- 3 sig figs and in Kelvins

* Unit 3 - Part 2 - Feb 3

** What You're Learning

- Reading Assignment: 20.1 - 20.3

- Goal of Unit 3: to see how macroscopic properties, such as \(p\), \(T\) and \(C_V\) depend on the motion of atoms.

- What is the micro/macro connection?

- Why gases have pressure?

- What is temperature?

** Intro to the Micro/Macro Connection

- Specifically we will explore a micro/macro connection called *kinetic theory of the ideal gas*.
  Its purpose is to resolve the puzzles we discovered in Units 1 and 2, such as

  + Why does the ideal gas law work so well for /every/ gas?

  + Why does the molar specific heat (\(C_V\)) have the same value for every monatomic gas (=3R/2)?
    For every diatomic gas (=5R/2)?
    For every elemental solid (=3R)?

  + What is temperature?

  + Why does a gas have pressure?

** Kinetic Theory of the Ideal Gas

- The ideal-gas law follows by assuming a gas consists of particles that obey Newton's laws.
  For our analysis, we assume:

  1. N identical particles of mass m and no internal structure.

  2. No intermolecular forces, so the molecules only have kinetic energy, no potential energy.

  3. Molecular motion is random (no preferred direction).

  4. Collisions with the wall of the container are elastic.

- In addition we assume that gas pressure arises from the average force, the particles exert when they collide with the container walls.

- Simple Model: Gas molecules confined to a rectangular box.

** Pressure in a Gas (Read page 551)

- Consider the elastic collision with a wall at rest, perpendicular to the x-axis:

  + The magnitude of \(v_x\) and \(v_y\) do not change - see PHYS 1061

  + The total momentum change of the gas during \(\Delta t\) is \((-)\text{N}_{\text{coll}} \cdot 2 mv_x\).

  + The # of collisions: \[N_{\text{coll}} = \frac{1}{2} \frac{N}{V} Av_x \Delta t\]

- The force on the wall due to these collisions is
  \[(F_{\text{on wall}})_x = \frac{2N_{\text{coll}} mv_x}{\Delta t}\]

- The pressure on one wall of the box is the average force on the wall per unit area:
  \[p = \frac{\overline{F}}{A} = \frac{mN}{V} \overline{{v_x}^2}\]

** Pressure in a Gas

- The pressure on one wall of the box: \[p = \frac{\overline{F}}{A} = \frac{mN}{V} \overline{{v_x}^2}\]

- However, the molecules are moving randomly.
  Thus, we can eliminate references to the x-component by using:
  \[\overline{v^2} = \overline{{v_x}^2} + \overline{{v_y}^2} + \overline{{v_z}^2} = 3 \overline{{v_x}^2}\]

- Def. \(v_{\text{rms}} = \sqrt{{v_{\text{avg}}}^2}\) is the rms speed of the molecules.

- You square all the speeds, then you average the squares (to find mean), then you take the square root.

  \[v_{\text{rms}} = \sqrt{{v_{\text{avg}}}^2}\]

- The results: The pressure on the walls of the container due to all the molecular collision is \[p = \frac{F_{\text{on wall}}}{A} = \frac{1}{3} \frac{N}{V} m{v_{\text{rms}}}^2\]

** Pressure and Temperature in a Gas

- Main result of KT: p in the container: \[p = \frac{F_{\text{on wall}}}{A} = \frac{1}{3} \frac{N}{V} m{v_{\text{rms}}}^2\]

- We define the average translational kinetic energy of a molecule to be \(\epsilon_{\text{avg}} = \frac{1}{2} m{v_{\text{rms}}}^2\), and find the micro-macro connection for p in terms of \(\epsilon_{\text{avg}}\) & \frac{N}{V}
  \[\text{Pressure, } p = \frac{2}{3}\frac{N}{V} \epsilon_{\text{avg}}\]

- Then, using \(pV = NkT\) we find the micro-macro connect for \(T\):
  \[\text{Temperature, } T = \frac{2}{3k_B} \epsilon_{\text{avg}}\]

- In words: The thing we call *temperature* measures the average translational kinetic energy \(\epsilon_{\text{avg}}\) of molecules in a gas.

- Assess. A higher T corresponds to a larger value of \(\epsilon_{\text{avg}}\) and thus to higher molecular speeds.

- In particular, T=0 is the temperature at which \(\epsilon_{\text{avg}} = 0\) and all molecular motion ceases.

** RMS Speed in a Gas

- Using Eq. 20-25 \(T = \frac{2}{3k_B} \epsilon_{\text{avg}}\) and the definition of
  \[\epsilon_{\text{avg}} = \frac{1}{2} m{{v_{\text{rms}}}^2\]
  we solve for the rms speed of molecules in a gas
  \[v_{\text{rms}} = \sqrt{\frac{3k_B T}{m}}\]

- Now, we can justify our assumption that molecular collisions are perfectly elastic.

- If they weren't, temperature of an isolated system would steadily decrease

- But that doesn't happen

** Example 3 (20.2)

What's the rms speed of nitrogen molecules at 20°C?

Interpret.

- The problem is involving the concept of the rms speed, and micro/macro connection

- N₂ is a diatomic molecule → Table 18.2

- Predict: More than the speed of sound in air 350 m/s

Represent.

- T = 293K, m = 28 u, u = 1.66 × 10^-27 kg

Develop.

- \(v_{\text{rms}} = \; ?\) Using micro-macro connection we get final expression
  \[v_{\text{rms}} = \sqrt{\frac{3k_B T}{m}}\]

Evaluate.

- \(v_{\text{rms}} = \sqrt{\frac{(3)(1.38 \times 10^{-23})(293)}{(28)(1.66 \times 10^{-27})}} = 510.86 \approx 511 \text{ m/s}\)

Assess.

- This is in excellent agreement with the experimental result of Fig. 20.2

** Problem 1 (Exercise 20.19)

By what factor does the rms speed change if the temperature is increased from 10.0°C to 1000°C?

Interpret.

- The question is about comparing two numbers by calculating their ratio

- The problem involves the concept of the rms speed

Represent.

- T_f = 1273K, T_i = 283K, ratio = ?

Develop.

- ratio = √(T_f / T_i)

Evaluate.

- ratio = √(1273 / 283) = 2.1209 ≅ 2.12

** In-class Problem #1

At what temperature (in °C) do hydrogen molecules have the same rms speed as nitrogen molecules at 100°C?

Interpret.

Represent.

Develop.

Evaluate.

Assess.

* Unit 3 - Part 3 - Feb 5

** What You're Learning

- Reading Assignment: 20.4 - 20.6

- How molecular structure determines the molar specific heats of gases?

- How do interacting system reach thermal equilibrium (Q_1 + Q_2 = 0)?

- What is the second law of thermodynamics (read only)?

** Thermal Energy and Molar Specific Heat

- Recall: The thermal energy of a system is \[E_{\text{th}} = K_{\text{micro}} + U_{\text{micro}}\]

- Question: What determines the value \(E_{\text{th}}\)?
  In Part 2, we found that T, structure and

- Step #1 - In ideal gas, there is no between neighbors, so \(U_{\text{micro}} = 0\)

- Step #2 - assume molecular structure of particles in the gas: e.g., monatomic particles, such as He or Ne

- For such a gas, \(E_{\text{th}} = K_{\text{micro}} = N\epsilon_{\text{avg}}\).
  With the average translational energy \[\epsilon_{\text{avg}} = \frac{3}{2} k_B T\]

- Then, we can obtain the total thermal energy as
  \[E_{\text{th}} = \frac{3}{2} Nk_B T = \frac{3}{2} nRT \quad \text{(theraml energy of a monatomic gas)}\]

- ASSESS: Besides the structure only T and n matter

- In consequence, if the temperature of a monatomic gas changes by \(\Delta T\), its thermal energy changes by \[\Delta E_{\text{th}} = \frac{3}{2} nR\Delta T\]

- In Unit 2, we found that the change in the thermal energy \(\Delta E_{\text{th}}\) for any ideal-gas process is related to the molar specific heat at constant volume \(C_V\) by
  \[\Delta E_{\text{th}} = nC_V \Delta T\]

- Combining these equations gives us a prediction for the molar specific heat for a monatomic gas:
  \[C_V = \frac{3}{2} R = 12.5 \text{ J/mol K} \quad \text{(monatomic gas)}\]

- ASSESS: Recall, this prediction is well confirmed by experiments, providing a strong evidence that gases really do consist of moving colliding particles.

** The Equipartition Theorem

- Fact: Atoms in a monatomic gas carry energy exclusively as translational kinetic energy (3 deg. of freedom: x, y, and z).

- Particles in other gases may have /additional modes of energy storage/, e.g., the kinetic and potential energy associated with vibration, or rotational kinetic energy (2 or 3 dof)

- Def. In general, the number of degrees of freedom is the number of distance and independent modes of energy storage.

Equipartition theorem.
The thermal energy of a system of particles is equally divided among all the possible degrees of freedom.
For a system of \(N\) particles at temperature \(T\), the energy stored in each mode (each degree of freedom) is \(\frac{1}{2} Nk_B T\) or, in terms of moles, \(\frac{1}{2} nRT\).

- As an equation: for a gas with \(f\) d.o.f, Eq. 20-28 has to be replaced by \[\epsilon_{\text{avg}} = \frac{f}{2} k_B T\]

** Thermal Energy and Molar Specific Heat

Q. What does the equipartition theorem imply for the values of \(C_V\)?

   \[E_{\text{th}} = \frac{f}{2} nRT \implies C_V = \frac{f}{2} R\]

ASSESS (read about quantum effects):

- For solid we have \(f = 6\) dof (-"bedspring" model with 3 translational + 3 more associated with the potential energy in the molecular bonds), then the equipartition theorem gives:
  \[C = 3R = 25.0 \text{ J/mol K} \; \text{ (solid)}\]

- Diatomic gases (at room T) have \(f = 5\) dof (with 3 translational and 2 rotational), the equipartition theorem gives:
  \[C_V = \frac{5}{2} R = 20.8 \text{ J/mol K}\]

** Example 1 (Exercise 20.29(b))

The thermal energy of 1.0 mol of a substance is increased by 1.0 kJ.
What is the temperature change (in °C) if the system is a diatomic gas?

Interpret.

- About application of the equipartition theorem

- A diatomic gas has 5 dof.
  This determines the substance \(C_V\).

Represent.

- \(\Delta E_{\text{th}} = 1.0 \text{ kJ}\)

- \(n = 1.0 \text{ mol}\)

- \(\Delta T = \; ?\)

- Sketch diatomic

Develop.

- \(\Delta T = \; ?\) From ET for \(f = 5\)

- \(\Delta E_{\text{th}} = \frac{5}{2} nR \Delta T\)

- Final expression: \(\Delta T = \frac{2\Delta E}{5nR}\)

Evaluate.

- \(\Delta T = \frac{2\Delta E}{5nR}\)

Assess.

** Problem 1 (20.63)

A gas mixture consists of \(n_1\) moles of monatomic gas and \(n_2\) moles of diatomic gas mixed together in a container.
Derive an expression for the molar expecific heat constant volume of the mixture?

Interpret.

- About expression for the molar specific heat at V=constant

- Molecular structure of dof f:f(n_1) = 3 dof and f(n_2) = 5 dog

- Equipartition theorem

- If two sub-systems are NOT interacting, energy is additive.

Represent.

- \(n_2\), \(n_1\), \(C_V = \; ?\), \(R\)

Develop.

- \(C_V = \; ?\), from Eq.20-30 \(C_V = \frac{\Delta E_{\text{th}}}{n \Delta T\)

- \(\Delta E_{\text{th}} \; ?\) from additivity and equipartition theorem (\(E_{\text{th}} = \frac{f}{2} nRT\)), and info about molecular structure: \(f(n_1) = 3\) and \(f(n_2) = 5\),
  \[E_{\text{th}} = \left(\frac{5}{2} n_2 + \frac{3}{2} n_1\right) R\Delta T\]

- Final expression:
  \[C_V = \frac{\Delta E_{\text{th}}}{n \Delta T} = \frac{(\frac{5}{2} n_2 + \frac{3}{2} n_1) R}{n_1 + n_2}\]

Assess.

- Reasonable

** Thermal Interactions and Heat

- Consider two gases, initially at different temperatures:
  \[T_{1_i} > T_{2_i}\]

- They can interact thermally through a very thin barrier.

- The membrane is so thin that atoms can collide at the boundary as if the membrane were not there, yet atoms cannot move from one side to the other:
  \[V_1 \text{ and } V_2 = \text{const}\]

- Question. How the thermal interactions, via molecular collision at the boundary, bring the systems to thermal equilibrium?

- We start with the COE on macro level:
  \[Q_1 = -Q_2\]

- The above implies the COE on the micro level (\(E_{1_i} + E_{2_i} = E_{1_f} + E_{2_f}\)). Why?

- Answer. Using the 1st law for isochoric process:
  \begin{align*}
    Q_1 &= \Delta E_1 = E_{1_f} - E_{1_i} \\
    Q_2 &= \Delta E_2 = E_{2_f} - E_{2_i} \\
  \end{align*}

- TE(\(T_{1_f} = T_{2_f} = T\)) is reached when the atoms, on each side have, on average, equal (translational- if mono) KEs:
  \[(\epsilon_1)_{\text{avg}} = (\epsilon_2)_{\text{avg}} \quad \text{(thermal equilibrium)}\]

  \[\Leftrightarrow \frac{E_{1_f}}{N_1} = \frac{E_{2_f}}{N_2} = \frac{E_{\text{tot}}}{N_1 + N_2}\]

** In-class Problem #2

A mixture of monatomic and diatomic gases has specific-heat ratio \(\gamma = 1.52\).
What fraction of its molecules are monatomic?

Interpret.

Represent.

- \(x_1 = \frac{n_1}{n_1 + n_2}\)

- \(x_1 + x_2 = 1\)

- \(C_{V_m} = \frac{3}{2} R\)

- \(C_{V_d} = \frac{5}{2} R\)

- \(C_V = \frac{3}{2} R x_1 + \frac{5}{2} R x_2\)

- \(\gamma = \frac{C_P}{C_V}\)

- \(C_P = C_V + R\)

Develop.

- Let \(n_1\) and \(n_2\) represent the number of monatomic and diatomic molecules in the mixture, respectively.

- Then \(f(n_1) = 3\) and \(f(n_2) = 5\).

- Thermal energy in terms of moles is then \(E_{\text{th}} = \left(\frac{3}{2} n_1 + \frac{5}{2} n_2\right) R\).

- Next, represent the change in thermal energy in terms of moles
  \[\Delta E_{\text{th}} = n C_V \Delta T\]

- Solving for \(C_V\), we obtain
  \begin{align*}
  C_V &= \frac{\Delta E_{\text{th}}}{n \Delta T} \\
  \end{align*}

\begin{align*}
\gamma &= \frac{C_P}{C_V} \\
&= \frac{C_V + R}{C_V} \\
&= 1 + \frac{R}{C_V}
\end{align*}

Evaluate.

Assess.

* Unit 4 - Part 1 - Feb 8

** What You're Learning

- Reading Assignment: 21.1 - 21.3

- Goal of Unit 4: to study the principles that govern a heat engine and refrigerator operation

** Turning Heat into Work

- Fact: Many practical devices are designed to transform energy from the heat (from burning fuel) into work.

- Any such device must obey two laws of TD:

  + First law. Energy is conserved; that is, \(\Delta E_{\text{th}} = W + Q\).

  + Second law. Most macroscopic processes are irreversible. In particular, heat energy is transferred spontaneously from a hotter system to a colder system but never from a colder system to a hotter system.

** Work Done by a System

\[\Delta E_{\text{th}} = W + Q\]

- Recall from Unit 2: The symbol W in the 1st law is the work done on a system by external forces from the environment.

- However, here in Unit 4, it makes more sense to use the work done by a system --- symbol \(W_s\)

- Fact: \(W\) and \(W_s\) are simply related:

  \[W_s = -W = \text{the area under the } pV \text{ curve}\]

- In terms of \(W_s\), the first law is

  \[Q = W_s + \Delta E_{\text{th}} \text{ first law}\]

- Assess: This equation in words says:
  #+begin_quote
  Any energy transferred to a system as heat is either used to do work or stored within the system as an increased thermal energy
  #+end_quote

** Energy-Transfer Diagrams

- We introduce an idealization to answer "How does the device.."

- Def: A heat (energy) reservoir is an object or a part of the environment so large that its T does not change when heat is transferred between the system and the reservoir.

- Examples: a burning flame or a large block of ice and hot water in the cup in the Sterling Engine DEMO:

- Def: A reservoir at a higher \(T_H\) than the system is called a /hot reservoir/.

- A reservoir at a lower \(T_C\) than the system is called a /cold reservoir/.

- We introduce notation convention...

  + \(Q_H\) = amount of heat transferred to or from a hot reservoir

  + \(Q_C\) = amount of heat transferred to or from a cold reservoir

** Heat into Work

- Converting heat into work is easy

- as seen in the isothermal expansion we considered in Quick Check #1

- Fact: In this T=const expansion heat is transformed into work, but at the end, the system (=gas) is in a different state: initial ≠ final

- This is unpractical...

- To be practical, a device converting heat into work (\(Q_{\text{add}} = W_s\)) must return to its initial state to be ready for continued use.

** Heat Engines

- Def: a heat engine (HE) is any closed-cycle device (final=initial) that

  1. extracts heat \(Q_H\) from hot reservoir

  2. does useful work, and

  3. exhausts heat \(Q_C\) to a cold reservoir.

- Figure shows the energy-transfer diagram of a heat engine.

- Fact: car engines and steam generators at your local power plant are heat engines

- Read about a steam turbine operation in a modern power plant - the text p.573.

** The Efficiency of Heat Engines

- Fact: The purpose of good heat engine is to transform as much of the heat absorbed \(Q_H\) into work done \(W_{\text{out}}\) as possible.

- Q: How to measure a quality of an engine?

- Def: The thermal efficiency of a heat engine is the ratio of the net work output in a cycle to the heat input per cycle:

  \[\eta = \frac{W_{\text{out}}}{Q_H} = \frac{\text{what you get}}{\text{what you had to pay}}\]

- Notation: \(W_{\text{out}}\) is the net \(W_s\) for a full cycle.

- Using the 1st law: \(W_{\text{out}} = Q_{\text{net}} = Q_H - Q_C\), we find:

- Note: a perfect HE would have \(\eta = 1\).
  Actual engines (cars, steam generators, etc.) have \(\eta \approx\) 0.1--0.5. This is not large!

** Ideal-Gas Heat Engines

- In this course, we will limit our attention to heat engines using an ideal gas as the working substance.

- Fact: a ideal gas HE can be represented by a CW loop on a pV diagram.

- The net work done during a full cycle in such engine is
  \[W_{\text{out}} = W_{\text{expand}} - |W_{\text{compress}}| = \text{area inside the closed curve}\]

** Example 1 (CQ) (21.15)

What is the thermal efficiency of the heat engine shown in Figure on the right?

Interpret.

- The definition of efficiency of a heat engine with ideal gas as the working substance.

- The work done by the gas per cycle is the area inside the closed pV curve.

- The 1st law to calculate Q_H

- kPa * cm^3 = mJ

Represent.

\begin{align*}
Q_C &= 280 \text{ J} \\
p_1 &= 100 \text{ kPa} \\
p_2 &= 300 \text{ kPa} \\
V_1 &= 200 \text{ cm}^3 \\
V_2 &= 600 \text{ cm}^3
\end{align*}

\begin{align*}
W_{\text{out}} &= \frac{1}{2} (200) (400) \times \frac{1}{1000} = 40 \text{ J}
\end{align*}

Develop.

1. \(\eta = \; ?\) \(\eta = \frac{W_{\text{out}}}{Q_H}\)

2. \(Q_H = \; ?\) The 1st law for the closed cycle: \(Q_H = Q_C + W_{\text{out}}\)

3. Final Expression: \(\eta = \frac{W_{\text{out}}}{Q_H} = \frac{W_{\text{out}}}{Q_C + W_{\text{out}}}\)

Evaluate.

1. \(\eta = \frac{W_{\text{out}}}{Q_C + W_{\text{out}}} = \frac{40}{280 + 40} \approx 0.13\)

Assess.

1. well below 1 so it is reasonable.

2. 2 sig figs and no units.

** Problem 1 (Example 21.1 (b))

Determine the efficiency for the cycle shown in Fig. below, assuming that the engine contains monoatomic ideal gas.

Interpret.

1. The efficiency of a heat engine working with ideal monoatomic gas

2. Three ideal gas processes involved: 1->2 isobaric, 2->3 isochoric, and 3->1 isothermal

3. heat added at p=const is determined by the law of molar specific with Cp = 5/2 R

4. ideal gas law will be used to eliminate (nRT) for pV.

Represent.

\begin{align*}
V_1 &= 200 \text{ cm}^3 \\
V_2 &= 600 \text{ cm}^3 \\
p_1 &= 200 \text{ kPa} \\
C_p &= \frac{5}{2} R \\
\eta &= \; ?
\end{align*}

Develop.

1. \(\eta = \; ?\) \(\eta = \frac{W_{\text{out}}}{Q_H}\) we need \(W_S\) and the heat added for 1->2 process \(Q_H\)

2. \(W_{\text{out}} = \; ?\) additivity + isobaric + isothermal
   \[W_{\text{out}} = W_{1 \to 2} + W_{3 \to 1} = p_1 (V_2 - V_1) + nRT \ln{\left(\frac{V_1}{V_3}\right)}\]
   \[W_{\text{out}} = p_1 (V_2 - V_1) + p_1 V_1 \ln{\left(\frac{1}{3}\right)}\]

3. \(Q_H = \; ?\) molar specific heats of mono gas, plus ideal gas law \(nRT = pV\):
   \[Q_H = Q_{1 \to 2} = nC_p (T_2 - T_1) = \frac{5}{2} p_1 (V_2 - V_1)\]

Evaluate.

\[W_{\text{out}} = 80 - 44 = 36 \text{ J}\]

\[Q_H = 200 \text{ J}\]

\[\eta = 18\%\]

** In-class Problem #1

Determine the efficiency for the cycle shown in Fig., assuming that the engine contains diatomic ideal gas.

Interpret.

1) The problem involves the definition of efficiency of a heat engine,.

2) This is a CW cycle, so the work done by the engine is the area on the pV diagram enclosed the cycle

3) 2->3 is isochoric and 3-> is isobaric processes

4) The heat is delivered from a hot reservoirs in the process 1->2 only.

5) We will use the 1st law to compute \(Q_H\)

6) The gas is monoatomic so its \(C_V = \frac{5}{2} R\)

7) We also use the ideal gas law to convert \(nRT\) into \(pV\)

Represent.

\begin{align*}
V_1 &= 10 \text{ cm}^3 \\
V_2 &= V_3 = 4V_1 = 40 \text{ cm}^3 \\
p_2 &= 1.5 \text{ atm} = 3 p_1 \\
p_1 &= p_3 = 0.5 \text{ atm} \\
\eta &= \; ?
\end{align*}

Develop.

1) \(W_{\text{out}} = \; ?\) Area of the triangle:

   1) \(W_{\text{out}} = \frac{1}{2} (p_2 - p_1) (V_3 - V_1) = A p_1 V_1\)

2) \(Q_H = \; ?\) We use the 1st law and the area under the curve 1>2

   \begin{align*}
     Q_H &= Q_{1 \to 2} = \Delta E_{\text{th}} + W_{S_{1 \to 2}} \\
         &= \Delta E_{\text{th}} + p_1 (V_3 - V_1) + \frac{1}{2} (p_2 - p_1) (V_3 - V_1) \\
         &= \Delta E_{\text{th}} + \frac{1}{2} (p_2 + p_1) (V_3 - V_1) \\
         &= \Delta E_{\text{th}} + B p_1 V_1
   \end{align*}

3) \(\Delta E_{\text{th}} = \; ?\) The thermal energy of ideal gas (\(\Delta E_{\text{th}} = nC_V (T_2 - T_1)\)) and then use \(C_V = \frac{5}{2} R\) for diatomic gas finally we use IGL to convert \(nRT\) into \(pV\)

   \[\Delta E_{\text{th}} = nC_V (T_2 - T_1) = \frac{5}{2} (nRT_2 - nRT_1) = 2.5 (p_2 V_2 - p_1 V_1) = C p_1 V_1\]

4) \(\eta = \; ?\) From the definition: \(\eta = \frac{W_{\text{out}}}{Q_H}\)

5) Final expression: \(\eta = \frac{W_{\text{out}}}{Q_H} = \frac{A}{B + C}\)

Evaluate.

\[\eta = \frac{A}{B + C} \approx 0.XX = XX\%\]

Assess.

1) No units and 2 sig. figs.

2) Small value efficiency--reasonable!

3) We can check that \(Q_H = Q_C + W_{\text{out}}\) where

   \[Q_C = |Q_{2 \to 3}| + |Q_{3 \to 1}| = \frac{5}{2} V_2 (p_2 - p_3) + \frac{7}{2} p_1 (V_3 - V_1) = D p_1 V_1\]

4) Check that \(B + C = D + A\)

* Unit 4 - Part 2 - Feb 10

** Refrigerators

- Fact: The operating principle of refrigerators is just the reverse of a heat engine.

- Def: It transfers heat out of its cooler interior to its warmer surroundings.

- In a refrigerator, the heat flows from \(T_C\) to \(T_H\).

- Q: Does it violate the 2nd law of TD?

- A: No, in a refrigerator or AC

  + heat energy is FORCED to flow from a cool reservoir to a hot reservoir.

- In any closede-cycle refrigerator, all state variables return to their initial values once every cycle:

  + initial = final

- So over one full cycle \[\Delta E_{\text{th}} = 0\]

- Then, the 1st law implies that the amount of heat exhausted per cycle to a hot reservoir by a refrigerator has to balance \(Q_C + W_{\text{in}}\) \[Q_H = Q_C + W_{\text{in}}\]

- We generalize the concept of thermal efficiency of a heat engine introducing the coefficient of performance (COP) of a refrigerator:

- Def: The coefficient of performance \(K\) of a refrigerator has to be (read from the right to left):
  \[K = \frac{Q_C}{W_{\text{in}}} = \frac{\text{what you get}}{\text{what you had to pay}}\]

- ASSESS: A better refrigerator will require less work to remove a given amount of heat.

- If a "perfect refrigerator (K = ∞)" existed, it would require no work \(W_{\text{in}} = 0\), then heat would flow spontaneously from cold to hot.
  This is expressly forbidden by the 2nd law of TD:

  Second law, informal statement #3. There are no perfect refrigerators with coefficient of performance \(K = \infty\).

** Refrigerator Example

- An ideal-gas refrigerator can use a Brayton cycle in reverse

- The CCW cycle involves four steps

  + In 4->3, a gas is compressed adiabatically to make it extremely hot.

  + In 3->2 then, heat is lost to the hot reservoir.

  + In 2->1 then, the gas expands adiabatically making it extremely cold.

  + In 1->4 lastly, heat flows into the gas from the cool reservoir.

** Example 1 (Exercise 21.20) Calculating the Coefficient of Performance

What is the coefficient of performance for the refrigerator shown in the fig.

Interpret.

1) The problem involves the COP of a refrigerator.

2) The diagram provides info about the heat exhausted to the hot reservoir, and the work done by the refrigerator.

3) We will use the 1st law for the whole cyccle to find the heat \(Q_C\)

4) We have to know the distinction between the work done by and on the system.

Represent.

\begin{align*}
Q_H &= 105 \text{ J} \\
W_{S_{2 \to 3}} &= -119 \text{ W} \\
W_{S_{4 \to 1}} &= 78 \text{ J} \\
\text{Target } K &= \; ?
\end{align*}

Develop.

1) \(K = \; ?\) Definition gives
    \[K = \frac{Q_C}{W_{\text{in}}}\]

2) \(W_{\text{in}} = \; ?\) The work input is the net work done on the refrigerator in one cycle.
   The latter is
   \[W_{\text{in}} = -W_{s \text{ net}} = -(W_{s_{2 \to 3}} + W_{S_{4 \to 1}})\]

3) \(Q_C = \; ?\) From the 1st law for the whole cycle:
   \[Q_H = Q_C + W_{\text{in}} \implies Q_C = Q_H - W_{\text{in}}\]

Evaluate.

\[W_{\text{in}} = 119 - 78 = 41 \text{ J}\]

\[Q_C = 105 - 41 = 64 \text{ J}\]

\[K = \frac{64}{41} = 1.56097\ldots \approx 1.6\]

Assess.

1) This is a reasonable value for the coefficient of performance for a refrigerator.

2) No units and 2 sig. figs.

** Problem 1 (Example 21.3)

A refrigerator using helium gas operates on a reverse Brayton cycle with a pressure ratio of 5.0.
Prior to compression the gas occupies 100 mL at a pressure of 150kPa and a temperature of -23°C.
Its volume at the end of the expansion is 80 mL.
What is the refrigerator's COP?

Interpret.

1) It involved the COP for the reverse Brayton cycle with two adiabatic and two isobaric processes.
   Heat energy is transferred only during TWO p=const process.

2) We will use the 1st law for whole cycle to find \(W_{\text{in}}\)

3) We will use the molar specific heat at p=const law, and helium is a monoatomic gas (\(C_p = \frac{5}{2} R\)).

4) We will ideal gas law to eliminate \(nRT\) for \(pV\) and we will use adiabat eq

Represent.

- \(\frac{p_2}{p_1} = 5.0\)

- \(V_1 = 80 \text{ mL}\)

- \(V_4 = 100 \text{ mL}\)

- \(\gamma = \frac{5}{3}\)

Develop.

1) \(K = \; ?\) From the definition \[K = \frac{Q_C}{W_{\text{in}}}\]

2) \(Q_C = \; ?\) The heat transfer from the cold reservoir occurs ONLY during 1->4 at p=const.

 So

   \begin{align*}
     Q_C &= Q_{p_{1 \to 4}} = nC_p (T_4 - T_1) > 0 \\
     Q_C &= \frac{5}{2} p_1 (V_4 - V_1)
   \end{align*}

3) \(W_{\text{in}} = \; ?\) From the 1st law we get: \(W_{\text{in}} = Q_H - Q_C\)

4) \(Q_H = \; ?\) By the same molar specific heat law we obtain the amount: \[Q_H = |Q_{p_{3 \to 2}}| = nC_p |(T_2 - T_3)| = nC_P (T_3 - T_2) = \frac{5}{2} p_2 (V_3 - V_2)\]

5) \(V_2 = \; ?\) From the adibat equation: \(p_2 {V_2}^{\gamma} = p_1 V_1^{\gamma}\)

6) \(V_3 = \; ?\) From the adibat equation: \(p_3 {V_3}^{\gamma} = p_4 {V_4}^{\gamma}\)

Evaluate.

- \(V_2 = 30.46 \text{ cm}^3\)

- \(V_3 = 38.07 \text{ cm}^3\)

- \(Q_H = 14.27 \text{ J}\)

- \(Q_C = 7.50 \text{ J}\)

- \(W_{\text{in}} = 6.77 \text{ J}\)

- \(K = \frac{7.50}{6.77} = 1.1078\ldots \approx 1.1\)

Assess.

- This is a reasonable value for the coefficient of performance for a refrigerator.

* Unit 4 - Part 3 - Feb 12

** What You're Learning

- Reading Assignment: 21.5 - 21.6

- Is there a maximum possible efficiency of a heat engine or max COP of a refrigerator?

- What is the Carnot cycle?

** Summary (Unit 3): TD Processes

- Table 21.1 summarizes the characteristics of ideal gas processes discussed to illustrate the first law of thermodynamics.

- The symbol \(Q\) stands for the head _added_ to and \(W_s\) the work done _by_ the system.

** Summary (Part 1 and 2): Heat Machines

- A heat engine is a cyclic process to change heat into a useful work.
  It requires two energy reservoirs.

- 1st law: \[W_{\text{out}} = Q_H - Q_C\]

- The efficiency is \[\eta = \frac{W_{\text{out}}}{Q_H} = \frac{\text{what you get}}{\text{what you had to pay}} \text{ or } \eta = 1 - \frac{Q_C}{Q_H}\]

- A refrigerator is a cyclic process extracting heat from a cooler region and sending it to a warmer region, taking work in the process.

- 1st law reads: \[Q_H = Q_C + W_{\text{in}}\]

- The COP is \[K = \frac{Q_C}{W_{\text{in}}} = \frac{\text{what you get}}{\text{what you had to pay}}\]

** No Perfect Heat Engine

- In part 1, we hypothesized that /there are no perfect heat engine, with \(\eta = 1\)/.

- Now we can prove it!
  Suppose we had a perfect HE (\(Q_C = 0\)).
  We could use its work output as the work input to an ordinary refrigerator with \(K < \infty\)

- This combo would violate the 2nd law of thermodynamics.
  Consequently, our assumption of a perfect HE must be wrong:

  Second law, informal statement #4. There are no perfect heat engines with efficiency \(\eta = 1\).

- In words: Any real HE must exhaust heat \(Q_C\) to a cold reservoir.

** The Limits of Efficiency

- Important Question:

  #+begin_quote
  Is there a maximum possible efficiency or max COP for a device operating operate between \(T_H\) and \(T_C\)?
  #+end_quote

- Answer: Yes, as demonstrated for a first time in 1824 by a French scientist Sadi Carnot.

- He proved that a perfectly reversible HE - now called a Carnot engine - has a maximum efficiency allowed by the laws of thermodynamics.

- Def. A perfectly reversible engine, is defined as a device that can operate as either heat engine or refrigerator between the same reservoirs and with the same energy transfers, with only their directions changed.

- If a perfectly reversible heat engine is used to operate a perfectly reversible refrigerator, the two devices exactly cancel each other.

- A heat engine more efficient than a perfectly reversible engine could be used to violate the second law thermodynamics.

- Fact. A perfectly reversible engine must use only two types of processes:

  + Frictionless mechanical interactions with no heat transfer (\(Q = 0\))

  + Thermal interactions in which heat is transferred in an isothermal process (\(\Delta E_{\text{th}} = 0\)).

- Def. Any engine that uses only these two types of processes is called a Carnot engine.

- Fact. A Carnot engine is a perfectly reversible engine; thus it has the maximum possible thermal efficiency \(\eta_{\text{max}}\) and if operated as a refrigerator, it has the maximum possible coefficient of performance \(K_{\text{max}}\).

** The Carnot Engine

- Q. How to design a Carnot engine?
  What is its working substance?
  What is its efficiency?

- The answer is an ideal-gas following CW the Carnot cycle that consists of

  + The two adiabatic processes (\(Q = 0\)) and

  + The two isothermal processes (\(\Delta E_{\text{th}} = 0\)) as shown.

- These are the two types of processes allowed in a perfectly reversible gas engine.

- Result: For any Carnot engine (the text) \(\frac{Q_C}{Q_H} = \frac{T_C}{T_H}\),

- Assess.

  + \(\eta_{\text{Carnot}}\) depends only on \(T_H\) and \(T_C\)

  + \(\eta_{\text{Carnot}}\) is always less than 100%

** The Maximum Efficiency

- Now we can answer the central question of Unit 4:

  #+begin_quote
  Is there a maximum possible efficiency?
  #+end_quote

- Second Law, informal statement #7: No heat engine operating between energy reservoirs at \(T_H\) and \(T_C\) can exceed the Carnot efficiency:

  \[\eta = \frac{W_{\text{out}}}{Q_H} \leq \eta_{\text{Carnot}} = 1 - \frac{T_C}{T_H}\]

- Second Law, informal statement #8: No refrigerator operating between energy reservoirs at \(T_H\) and \(T_C\) can exceed the Carnot COP:

  \[K = \frac{Q_C}{W_{\text{in}}} \leq K_{\text{Carnot}} = \frac{T_C}{T_H - T_C}\]

- Assess. High efficiency requires \(\frac{T_C}{T_H} \ll 1 \Leftrightarrow T_H \gg T_C\)

- Practicality often prevent \(T_H\) from being much larger than \(T_C\).

** QuickCheck #1

This heat engine is

- [ ] A reversible Carnot engine.

- [ ] An irreversible engine.

- [X] An impossible engine.

** Applications-Generating Electricity

- Be aware that Eq. 21-27: \[\eta_{\text{Carnot}} = 1 - \frac{T_C}{T_H}\] gives the absolute max efficiency that's theoretically possible.

- By the time all losses are considered the efficiency for real coal-, gas-, and even nuclear-heated steam generators operate at \(\approx 35\%\) efficiency.

- Assess. It means that about 2/3 of the energy extracted from fuels is dumped to the environment as waste heat.

** Problem 1 (Problem 21.44)

A Cargnot heat engine operates between reservoirs at 182°C and 0.0°C.
If the engine extracts 25 J of energy from the hot reservoir per cycle, how many cycles will it take to lift a 10. kg mass a height of 10. m?

Interpret.

1) About the work output of a Carnot engine
2) We will use the efficiency of a Carnot engine
3) We have to calculate the work required to lift the mass

Represent.

Develop.

1) # of cycles = ? If we define W = the work required to lift a 10 kg mass 10 m.
   \[\text{\# of cycles} = \frac{W}{W_{\text{out}}}\]
2) W = ? From mechanics we know that the work required to lift a 10 kg mass 10 m is
   \[W = Fd = Mgd\]
   where g=9.8 N/kg
3) \(W_{\text{out}} = \; ?\) From definition of the efficiency:
   \[W_{\text{out}} = \eta Q_H\]
4) \(\eta = \; ?\) Assuming that HE is a Carnot, one we get \(\eta = 1 - \frac{T_C}{T_H}\)
5) Final Expression:
   \[\text{\# of cycles} = \frac{Mgd}{\left(1 - \frac{T_C}{T_H}\right) Q_H}\]

Evaluate.

\[\text{\# of cycles} = \frac{Mgd}{\left(1 - \frac{T_C}{T_H}\right) Q_H} = (10)(10) \left(\frac{9.8}{\frac{2}{5} (25)}\right) = (10)(9.8) = 98\]

Assess.

1) small work output 10 J/cycle, so the engine will have to cycle 98 times to do this work
2) no units and 2 sig figs

* Unit 5 - Part 1 - Feb 15

** What You're Learning

- Reading assignment: 22.1-22.3 (Read only); 22.4-22.5

- Goal of Unit 5: learn how to calculate and use the electric field.

- What is Coulumb's law?

- How to determine the eletric force on a point charge when several source charges (charge distribution) are present?

- What is an electric field?

- What is the electric fields of a charge single point charge?

** Electric Charges (Read Only)

- In this Unit, you will learn that electric phenomena are based on electric charges, electric forces, and electric fields.

- Basic facts (the charge model):

- Electric phenomena, observed when two objects are rubbed together, depend on the amount of charge.

- There are two kinds of charge, called positive and negative.

- Electrons and protons -- the constituents of atoms -- are the basic charges.

- Charging is the transfer of electrons from one object to another.

** Electric Forces

- Experimental fact: A simple force law occurs for point charges (Coulomb's law), a distance r apart.

- When two positively/negatively charged particles at rest, a distance, r, apart, they each experience a repulsive force of the magnitude:
  \[F_{1 \text{ on } 2} = F_{2 \text{ on } 1} = \frac{K |q_1| |q_2|}{r^2}\]
  where K is called electrostatic constant \(\approx 9.0 \times 10^9 \text{ N}\cdot\text{m}^2 / \text{C}^2\)

- Fact #2: The law of charges: When two oppositely charged particles are a distance, r, apart, the force has the same magnitude but becomes an attractive force

** Coulomb's Law (Read Only)

- The SI Unit of charge: coulumb (C), is derived from the unit of current (Unit 7). For now,

- Def. 1 C is the amount of charge, if placed on two points 1 m apart, it will result in a force \(F \approx 8.99 \times 10^9 \text{ N}\). (huge force why)

** Point Charges and the Superposition Principle

- Consider: Several point-like charges at rest.

- Q. How to find the force on any of them due to the others?

- Answer: Follow the procedure:

  + Draw a diagram showing the charge distribution and coordinate system.

  + Determine the directions of all forces using the law of charges.

  + Calculate the magnitudes of all individual forces using Coulomb's law.

  + Then, add them (superposition principle) vectorially (i.e., by components in a convenient coordinate system)

    \[\vec{\mathbf{F}}_{\text{net}} = \vec{\mathbf{F}}_1 + \vec{\mathbf{F}}_2 + \cdots\]

** The Field Model

- Note that the electric forces are pushes/pulls over a distance.

- Q. How come? Answer: Faraday (1821) proposed 2 step process:

  + Every charge alters the space around it, creating an electric field at all points in space and the field exerts a force.

  + The field exerts a force:

    - Q. How to define \(\vec{E}\) at a point (x, y, z)?

      \[\vec{E}(x, y, z) = \frac{\vec{F}_{\text{on } q} \text{ at } (x, y, z)}{q}\]

- The units of the electric field are \(\frac{N}{C}\).
  The magnitude E of the electric field is called the electric field strength.

  + Every charge alters the space around it, creating an electric field at all points in space and

** The Electric Field of a Point Charge

- If we calculate the field at a sufficient number of points in space, we can draw a field diagram.

- Notice that the field vectors all point straight away from the source (i.e., positive \(q\).)

- Also notice how quickly the arrows decrease in length due to the inverse-square depending on \(r\).

- Equation 22.7 captures these two features:

  \[\vec{E} = \frac{\vec{F}_{\text{on } q'}}{q'} = \left(\frac{1}{4\pi \epsilon_0} \frac{q}{r^2}, \text{ away from } q\right)\]

** The Electric Field of a Point Charge

- Equation 22.7 is precise but inconvenient.
  Q: What happens if q is negative.

- Using unit vector from the source to a point of interest \(\vec{r}\).

- The electric field \(\vec{E}\) at a distance \(r\) from a point charge \(q\) can be written as a vector:
  \[\vec{E} = \frac{1}{4\pi \epsilon_0} \frac{q}{r^2} \hat{r} \quad \text{(electric field of a point charge)}\]

- Note that a negative sign in front of a vector simply reverses its direction.

** Problem 1 (22.43)

What is the force on the 5.0nC charge in the figure below.
Give your answer as magnitude and angle measured CW or CCW (specify which) from the x-axis.

Interpret.

1. The problem is about the net force on charge #1
2. The individual forces on each charge lie along a line connecting the charges.
3. Will use the law of charges to determine the direction.
4. Prediction: the net force is in the 4th quadrant.

Represent.

- \(q_1 = 5.0 \times 10^{-9} \text{C}\)
- \(q_2 = 10 \times 10^{-9} \text{C}\)
- \(q_3 = -5.0 \times 10^{-9} \text{C}\)
- \(r_{13} = 3.0 \times 10^{-2} \text{ m}\)

Develop.

- Step 1: Calculate forces using Coulumb's law: \[F = K \frac{|q_1||q_2|}{r^2}\]
- Step 2: Add forces by components
- Step 3: Once we do have component of the net we can calculate the magnitude of he net force \(\vec{F}_{\text{net}}\): \[F_{\text{net}} = \sqrt{({F_x}^2 + {F_y}^2)}\]
- The angle of net measured CW from the x-axis (why? Because, the vector \(\vec{F}_{\text{net}}\) is in the 4th quadrant): \[\phi = \tan^{-1}\left(\frac{|F_{\text{net } y}|}{F_{\text{net } x}}\right)\]

* Unit 5 - Part 2 - Feb 17

** What You're Learning

- Reading Assignment: 22.1-22.3 (Read only); 22.4-22.5 and 23.1

- Goal of Unit 5-Part 2&3: learn how to calculate and use the electric field.

- How to calculate the electric fields of discrete charge distribution?

- What is the electric field of an electric dipole?

- How to represent electric field through field lines (read only)?

** The Electric Field of a Point Charge

- Recall from Part 1: Using unit vector notation, the electric field at a distance \(r\) from a point charge \(q\) is \[\vec{E} = \frac{1}{4\pi \epsilon_0} \frac{q}{r^2} \hat{r} \qquad \text{(electric field of charge)}\]

- Q: How to construct the unit vector?

- Fact. The unit vector always radiates from the source to the point P, but a negative sign in front of a vector simply reverses its direction and gives the field radiating into the source.

** Fields of Multiple Point Charges

- Consider several point-like charges at rest.

- Q. What is \(\vec{E}_{\text{net}}\) at any point in space P due a set of charges?

- Answer. Follow the procedure:

  + Draw a diagram showing the charge distribution.

  + Determine the directions of \(\vec{E}_i\) using the law of charges.

  + Calculate the magnitudes of \(\vec{E}_i\) using Coulomb's law.

  + Then, add individual fields (superposition principle) vectorially (i.e., by components):
    \[\vec{E}_{\text{net}} = \vec{E}_1 + \vec{E}_2 + \cdots = \sum_i \vec{E}_i\]

** Problem 1 (23.38)

Figure shows three charges at the corners of a square.
Find an expression for the magnitude of the electric field at point P and angle measured CW or CCW (specify which) from the x-axis.

Interpret.

1) We will calculate the net field at P using the law of superposition

Represent.

- q_1 = -Q, q_2 = -Q, q_3 = 4Q, \(r_{12}\) = \(r_{23}\) = L

- Step #1. Draw a diagram showing the charge distribution.

- Step #2. Determine the directions of \(\vec{E}_i\) using the law of charges and predict the net field.

- The individual fields are: #1 horizontal to the left, #2 vertical down and #3 diagonal (1st quadrant)

- PREDICT: the net is along the diagonal

Develop.

- Angle 45°

** The Dipole: An Important Charge Distribution

- Def. An electric dipole consists of two point charges of equal magnitude but opposite signs, held a short distance apart.

- Fact. Many charge distributions, (e.g., molecules) can be modeled as electric dipoles.

- In H20, negative electrons spend more time with the oxygen atom

- Q. What is the electric field of a dipole?

- A. Let us use the superposition principle, Coulomb's law and some simplifying assumptions to find out - see below

** Problem 2 (23.40)

Consider two equal opposite charges -Q and +Q placed a distance L apart.
Find the electric field at an arbitrary point on the line that bisects the electric dipole.

* Unit 5 - Part 3 - Feb 19

** What You're Learning

- Reading Assignment: 23.2-23.7

- How to calculate the electric fields of continuous charge distributions?

- Three important electric fields

- What is parallel plate capacitor?

** Fields of Continuous Charge Distributions

- Recall from Part 1 and Part 2: Up to now, we considered charge distributions of several point charges:
  \[\vec{E}_{\text{net}} = \vec{E}_1 + \vec{E}_2 + \cdots = \sum_i \vec{E}_i\]
- Today, we are posing a new question: how to construct fields produced by large, macroscopic objects like charged rods or disks

- Q: What if the charge is continuous?

- Model: For macroscopic charged objects, like rods or disks, we can think of the charge as having a continuous distribution.

- Q: How to calculate the field of a continuous charge distribution?

  + We divide objects into small point charge-like pieces dq.

  + The summation of fields of an infinite number of infinitesimally small pieces is integration.

  + Note that integrals are carried out over coordinates x, y, z (densities come in here - see below)

- We'll use this strategy to calculate the electric fields of four important charge distributions over a wire, ring, disk, and a plane:
  \[\vec{E}(P) = \int d\vec{E} = \int \frac{k \;dq}{r^2} \hat{r}\]

** An Infinite Line of Charge (Example 1, Example 23.3)

A straight infinite line of charge coincides with the x-axis and (the line carries uniform charge density λ C/m).
Find the electric field at radial distance y in the plane that bisects the line.

Interpret.

1) Divide the line into segments
2) The fields perpendicular to the y axis cancel for two symmetrically opposed segments.

Develop.

1) Only the y-comps add up
2) The electric field in 2nd quad: \(dE_y = dE \cos{\theta}\)
3) \(dE = \frac{k \lambda \;dx}{r^2}\), \(\cos{\theta} = \frac{y}{r}\), and \(r = (x^2 + y^2)^{1/2}\)
4) Integrating over x from \(-\infty\) to \(+\infty\) we get \[\vec{E}(P) = \frac{2k \lambda}{y} \hat{j}\] or \[\vec{E}_{\text{line}} = \left(\frac{1}{4\pi\epsilon_0} \frac{2 |\lambda|}{r}, \begin{cases}\text{away from line if charge } + \\ \text{toward line if charge } -\end{cases}\right)\]

Assess.

1. Check dimensions and direction
2. The direction is radially outward for positive charge and inward for negative charge.
3. The field decreases slower (as 1/r where r perp. distance from the wire.)

** Problem 1 (Exercise 23.12)

The electric field 5.0 cm from a very long charged wire is 2.0 kN/C, toward the wire.
What is the charge (in nC) on a 1.0 cm-long segment of the wire?

** The Field of a Ring of Charge

\[\vec{E}(P) = \frac{kQx}{(x^2 + a^2)^{3/2}} \hat{i}\]

** Problem 2 (Exercise 23.14)

Two 10-cm-diameter charged rings face each other, 20 cm apart.
The left right is charged to -20 nC and the right ring is charged to +20 nC.

a) What is the electric field, both magnitude and direction at the midpoint between the two rings?
b) What is the force on a proton at the midpoint?

Interpret.

1) About the net electric field of two rings. We will use the superposition.
2) The question is only about the net field on the axis of the ring.

Represent.

- R = a = 0.05 m, \(e_p = 1.6 \times 10^{-19} \text{ C}\)
- d = 0.10 m, \(Q = 20 \times 10^{-9} \text{ C}\)
- Sketch
- Part (a) E(z=0)=? Part (b) F = ?

Develop.

1) E(z=0)=? From superposition of the two fields and the expression for the on-axis field of a thin ring we get the magnitude of the net:
   \[E(z=0)=E_1(z=0) + E_2(z=0) = \frac{2kQd}{(d^2 + R^2)^{3/2}}\]
2) F=? From the field-force link we get the force magnitude \(F = e_p E(z=0)\)
3) Final expression: A\[F = \frac{e_p 2k Qd}{(d^2 + R^2)^{3/2}}\]

Evaluate.

1) The value of the field magnitude: \(E(z=0)=2.6\times 10^4 \text{ N/C}\) dir. to the left.
2) The value of the force magnitude \(F=eE = 4.1 \times 10^{-15} \text{ N}\) dir. to the left

Assess.

- Very small force in N, 2 sig figs.

** A Disk of Charge (Read Only)

\[(E_{\text{disk}})_z = \frac{\eta}{2\epsilon_0} \left[1 - \frac{z}{\sqrt{z^2 + R^2}}\right]\]

** The Field of a Plane of Charge

- Fact. The electric field of a plane of charge can be found from the above expression by letting the radius \(R \to \infty\).

- Result. The electric field of an infinite plane of charge with surface charge density η is
  \[\vec{E}_{\text{plane}} = \left(\frac{|\eta|}{2\epsilon_0}\begin{cases}\text{away from plane if charge } + \\ \text{toward plane if charge } -\end{cases}\right)\]

** The Parallel-Plate Capacitor

- Consider two capacitor infinite plates, seen from the side.
- Because opposite charges attract, all of the charge is on the inner surfaces of the two plates.
- Inside the capacitor, the net field points toward the negative plate.
- Outside the capacitor, the net field is zero.
- For finite plates neglect the fringe field (b) you will get = ideal capacitor model
- The electric field of a ideal capacitor:
  \[\vec{E}_{\text{capacitor}} = \begin{cases}\left(\frac{Q}{\epsilon_0 A}, \text{ from positive to negative}\right) &\text{inside} \\ \vec{0} &\text{outside}\end{cases}\]

* Unit 6 - Part 1 - Feb 22

** Summary (Unit 5) - Electric Fields

- The field of a point charge follows from Coulomb's law: \[\vec{E}_{\text{point charge}} = \frac{kq}{r^2} \hat{r}\]

  where the unit vector \(\hat{r}\) is pointing from the source to the field point.

- Fields of charge distributions are found by summing fields of individual point charges, or by integrating in the case of continuously distributed charge:
  \[\vec{E}(P) = \int d\vec{E} = \int \frac{k \;dq}{r^2} \;\hat{r}\]

** What You're Learning

- Reading Assignment: 26.1, 25.1, 25.2, 25.4 and 25.6

- About representing the electric field by the electric potential.

- How to calculate the potential of a uniform electric field?

- How to calculate the potential of a point charge?

- How to use the concept of potential?

** Finding Potential from the Electric Field

- Q: What do we want to accomplish in Unit 6?

- Goal: To represent the electric vector field \(\vec{E}(P)\) by a simple, scalar field called electric potential at P: \(V(P)\).

- Q: How possible? Three step procedure:

  + Like gravity, the electrostatic force is conservative, so its work can be represented by change of electric potential energy (\(\Delta U = U(B) - U(A)\)):
    \[\Delta U = W_{A \to B} = -\int_A^B \vec{F} \cdot d\vec{r}\]
    where \(\vec{r\) is the position vector along a path (any) of the test charge from point A to point B.

  + Now, divide the charge q out, and define the potential difference (\(\Delta V\)) between two points A and B in space with no dependence on q:
    \[\vec{E}_P = \frac{\vec{F}}{q} \qquad V(B) = \Delta V_{AB} = \frac{\Delta U_{AB}}{q} = -\int_A^B \vec{E} \cdot d\vec{r}\]

  + Finally, taking A=the starting point to be a standard reference point, and assuming \(V(A) = 0\), we obtain \(V(B) = \frac{\Delta U}{q}\) which is a function of the point of interest in space (B) only.

- Def. V(B) is called the electric potential (of the field) at B.

- Note that V(B), like the electric field vector \(\vec{E}(P)\) is a property of the source charges and P only.

- Q: What is the physical meaning of potential at a point P?

- We can find out from Eq. (26.3):
  \[V_B = \Delta V_{AB} = \frac{\Delta U_{AB}}{q} = -\int_A^B \vec{E} \cdot d\vec{r}\]
  Looking at the first equality, we read from it that the electric potential \(V_P\) at any point P is the electric potential energy at P per unit charge:
  \[V_P = \frac{U_P}{q}\]
  In other words: Electric potential is a (relative) measure of how much electric potential energy a unit of charge CAN acquire when placed at the location.

- Units: 1 volt is 1 joule per coulomb: 1 V = 1 J/C.

** Example 1 (Example 26.1)

In Unit 5, the electric field inside of a capacitor was found to be uniform (E=const) and point from positive to negative plate.
Find an expression for the potential at point x assuming that \(V = 0\) at \(v = 0\) at \(x = 0\).

Interpret.

1) This is a question about calculating the potential difference in a uniform electric field.
2) Plates are equipotential (see Eq. 26.3) so we ref. point A anywhere on the negative plate.

Represent.

1) E, A=(0,0), B=(x,0), V(A)=0, V_B=V(x)?

Develop.

1) V_B = ? We will use Eq. 26.3:
   \[V_B = -\int_A^B \vec{E} \cdot d\vec{r}\]

2) We need a path from A to B.
   We can choose any path we want, so let us go from A to the point on x axis beneath B and then up to B along the vertical.

3) The electric field anywhere: \(\vec{E} = -E\hat{i}\)

4) On the horizontal segment: \(d\vec{r} = dx \hat{i}\)

5) On the vertical segment: \(d\vec{r} = dy \hat{j}\)

6) The potential difference Eq. 26.3. Setting the zero of potential at A gives V at B:
   \[V_B - V_A = -\int_0^x \vec{E} \cdot d\vec{e} \implies V_B = \int_0^x E \;dx = Ex\]

Assess.

1) V decreases in the direction of the electric field, or

2) V increases from negative to positive

3) In other words, \(\vec{E}\) lines always point in the direction of decreasing potential

4) For a positive test charge, the field direction is "downhill" (positive moving in the field direction is losing \(U \downarrow\) and gaining \(K \uparrow\))

** Problem 1 (Example 25.6)

A proton with speed of \(3.0 \times 10^5\) m/s enters a region of space in which there is an electric potential.
What is the proton's speed after it moves through a potential difference of +100 V?

Interpret.

1) It is about the relationship between \(\Delta V\) and \(\Delta U\).
2) Total energy is conserved, so \(\Delta U\) is linked to \(\Delta K\)
3) PREDICT: A positive q slows down as it moves into a region of higher potential (recall U↑ implies K↓): \(V_f < V_i\)

Represent.

- \(q = 1.6 \times 10^{-19} \text{ C}\), \(m = 1.67 \times 10^{-27}\), \(v_i = 3.0 \times 10^5\) m/s, \(\Delta V = 100 \text{ V}\); Target \(v_f = \; ?\)

Develop.

1) \(v_f = \; ?\) From the COE and def of \(K = \frac{1}{2} mv^2\) we get
   \[K_f = K_i - \Delta U = K_i - q\Delta V \implies v_f = \sqrt{{v_i}^2 - \frac{2q\Delta V}{m}}\]

Evaluate.

\[v_f \approx 2.66 \times 10^5 \text{ m/s} \approx 2.7 \times 10^5 \text{ m/s}\]

Assess.

1) The proton slowed down, as expected. 2 sig figs, m/s

** Example 2, Electric Potential of a Point Charge

Find an expression for the potential of a positive POINT charge q at a point B.

Interpret.

- This is a question about calculating the potential difference in the electric field of a point like charge.

Represent.

- \(r_A\), \(r_B\), \(q\), \(\Delta V_{AB} = \;?\)

Develop.

1) \(\Delta V_{AB} = \;?\) We will use Eq. 26.3:
   \[\Delta V_{AB} = \frac{\Delta U_{AB}}{q} = -\int_A^B \vec{E} \cdot d\vec{r}\]

2) We need a path.
   You can choose any path you want: so go from A along the radius up to the distance \(r_B\), then go to B along the arc (why?)

3) The electric field anywhere: \(\vec{E} = \frac{kq}{r^2} \hat{r}\)

4) On the radial segment: \(d\vec{r} = dr \hat{r}\)

5) The potential difference Eq. 26.3
    \begin{align*}
        \Delta V_{AB} &= \frac{\Delta U_{AB}}{q} = -\int_A^B \vec{E} \cdot d\vec{r} \\
        \Delta V_{AB} &= -\int_{r_A}^{r_B} \frac{kq}{r^2} dr = -kq \int_{r_A}^{r_B} \frac{dr}{r^2} = kq \left(\frac{1}{r_B} - \frac{1}{r_A}\right)
    \end{align*}

6) Setting the zero of potential at infinity (\(r_A = \infty\)) gives V at B:
   \[V_{\text{point charge}} = \frac{1}{4 \pi \epsilon_0} \frac{q}{r}\]

Assess.

- Again, the electric potential decreases in the direction of the electric field.

- In other words, E lines point in the direction of decreasing potential

- For a positive charge, the field direction is "downhill" (positive charge moving in the field direction is losing U↓ and gaining K↑)!

** The Electric Potential of a Charged Sphere

- Fact. Outside a uniformly charged sphere of radius R, the field and the electric potential are identical to that of a point charge Q at the center:
  \[V = \frac{1}{4 \pi \epsilon_0} \frac{Q}{r}\]
  where \(r \geq R\)

- Fact. If the potential at the surface \(V_0\) is known, then the potential at \(r \geq R\) is \[V = \frac{R}{r} V_0\]

** Applications

- Fact. In the form of radioactive decay known as alpha decay, an unstable nucleus emits a helium-atom nucleus, which is called an alpha particle.
  The alpha particle contains two protons and two neutrons, thus having mass m = 4 u and charge q = 2e.

** Problem 2 (25.58)

Suppose a uranium nucleus with 92 protons decays into thorium, with 90 protons, and an alpha particle.
The alpha particle is initially at rest at the surface of the thorium nuleus, which is 15 fm in diameter.
What is the speed of the alpha particle when it is detected in the laboratory?
Assume the thorium nucleus remains at rest.

Interpret.

1) It is, again, about the relationship between \(\Delta V\) (of spherically symmetric charge distribution) and \(\Delta U\)
2) Total energy is conserved, so \(\Delta U\) is linked to \(\Delta K\)
3) Predict: The alpha is speeding up when moving away from thorium, b/c it moves into a region of lower potential

Develop.

1) \(v_f = \; ?\) From the \(\Delta U \leftrightarrow \Delta V\) relationship, the COE and definition of KE: \(K = \frac{1}{2} mv^2\) we get:
   \[K_f = K_i - \Delta U = K_i - q\Delta U = -q(V_f - V_i) = qV_i\]
2) \(v_i = \; ?\) Potential on the surface of thorium: \(V_i = \frac{KQ}{R}\)
3) Final expression: \[v_f = \sqrt{\frac{K\cdot 2 \cdot 2 \cdot e \cdot 20 \cdot e}{m \cdot R}}\]

Evaluate.

\[v_f \approx 4.07 \times 10^7 \text{ m/s} \approx 4.1 \times 10^7 \text{ m/s}\]

Assess.

- The speed is smaller than c. 2 sig. figs and m/s.

* Unit 6 - Part 2 - Feb 24

** What You're Learning

- Reading Assignment: 25.7 and 25.2

- How to calculate electric potential in the field of a set of charges and continuous charge distributions?

- How to calculate the work required to assemble a charge distribution?

- How to get the electric field if you know the potential?

- About the concept of equipotential line or surfaces (read)

- What are the properties of conductors in electrostatic equilibrium (read)?

** Summary (Unit 6 - Part 1)

- Goal: To represent the electric vector field \(\vec{E}(P)\) by a simple, scalar field called electric potential at \(P\): \(V(P)\).

- Electric potential difference is the potential energy change per unit charge involved in moving charge between \(A\) and \(B\) in an electric field:
  \[\Delta V_{AB} = \frac{\Delta U_{AB}}{q} = -\int_A^B \vec{E} \cdot d\vec{r}\]

- In a uniform field, the potential difference becomes
  \[V_P = Ex\]

- Electric potential differences of a point charge is where the zero of potential is taken at infinity.
  \[V_P = \frac{kq}{r}\]

** The Electric Potential of a Set of Point Charges

- Q: How to determine the potential at a point P due to a collection of point charges?
  \[\Delta V_{\text{AB}} = \frac{\Delta U_{AB}}{q} = -\int_A^B \vec{E} \cdot d\vec{r} \qquad \vec{E}(P) = \vec{E}_1 + \vec{E}_2 + \vec{E}_3 = \sum_i \frac{kq}{{r_i}^2} \hat{r}_i\]

- Answer: See the above definition of the electric potential difference and use the superposition principle for electric field.

- The potential at a point P due to a system of point-like charges is the arithmetic sum of the potentials due to each individual charge.

- Note: This is a major advantage in using electric potential!

** Example 1 (Example 25.9)

What is the eletric potential (in V) at the dot point indicated in Figure

Interpret.

1) The problem involves the calculation of the potential of multiple point charges.

2) We will use superposition principle.

Represent.

- q1=2e-9 C, r1=0.05 m, q2=-10e-9 C, r2=0.04 m, k=8.99e9

Develop.

1) V(P)=? Using the superposition we can write the final expression:
   \[V(P) = k \left(\frac{q_1}{r_1} + \frac{q_2}{r_2}\right)\]

** Using the Potential (Electrostatic Energy)

- Fact. It takes work to bring positive charges into proximity.

- That work is stored as electrostatic energy associated with the new configuration of charges.

- Q: How to compute it?
  Answer:
  - Each charge pair (\(q_i, q_j\)) of point charges contributes energy
    \[U_{ij} = \frac{kq_i q_j}{r_{ij}}\]
    where \(r_{ij}\) is the distance between the charges.

- Q: Why this rule? See the example below:

- Example: Let's find the work needed to create this configuration of 3 point charges

- \(W_{21} = U_f-U_i = q_2V_1 = kq_1q_2/a\), \(W_{3(21)} = q_3V_1 + q_3V_2\)

- The total work \(W_{21} + W_{3(21)}\) is the stored electric energy = \(\sum_{(pairs)} U_{ij}\)
  \[U_{\text{electrostsatic}} = \frac{kq_1q_2}{a} + \frac{kq_1q_3}{a} + \frac{kq_2q_3}{a}\]

** The Potential of a Continuous Distribution

- Q: How to find the electric potential at P of a continuous distribution of charge?

- The potential due to an arbitrary continuous charge distribution can be expressed as an integral of the potentials of point-like charge elements:
  \[V(P) = \int dV = \int \frac{k\;dq}{r}\]

- Assess.
  Contrast this expression with the one for electric field:
  \[\vec{E}(P) = \int d\vec{E} = \int \frac{k \;dq}{r^2} \hat{r}\]

** The Electric Potential of a Ring and Disk

- Example 2 (25.10): For a uniformly charged ring of total charge \(Q\), integration gives the potential on the ring axis at a point \(x\):
  \[V(x) = \int \frac{k\;dq}{r} = \frac{k}{r} \int dq = \frac{kQ}{\sqrt{x^2 + a^2}}\]

- Example 3 (25.11-READ): Integrating the potentials of charged rings that make up the disk, gives the potential of a uniformly charged dist at a point \(x\) on the axis \(\left(dq = \frac{2Q}{a^2} r \;dr\right)\)
  \[V(x) = \frac{2kQ}{a^2} \left(\sqrt{x^2 + a^2} - |x|\right)\]

- For a derivation read in the text (EM 25.11)

- Assess. This reduces to the infinite-sheet potential close to the disk, and the point-charge potential far from the disk

- For a derivation read in the text (EM 25.11)

- Assess. This reduces to the infinite-sheet potential close to the disk, and the point-charge potential far from the disk.

** Problem 1 (Problem 25.71)

Figure shows a thin rod with charge \(Q\) that has been bent into a semicircle of radius \(R\).
Find an expression for the electric potential at the center.

Interpret.

1) Because the rod is thin, assume the charge is uniformly distributed along the semicircle of radius R.

2) We will use the superposition principle.

Represent.

- \(Q\) or \(\lambda\), R, K; target V(P) = ?

Develop.

1) V(P)=?
2) Divide the semicircle into # small segments, each carrying the charge dq.
   All segments are the same distance R from the center
3) The potential V at P is the integral of the potentials due to each segment of charge:
   \[V(P) = k \frac{1}{R} \int dQ = \frac{kQ}{r}\]
4) The final expression in terms of the charge density \(\lambda\)
   \[V(P) = k\lambda\pi\]

Assess.

- The expression has correct dimension in volts.

** Problem in class:
The wire in Figure below has linear charge density \(\lambda\).
Find an expression for the electric potential at the center of the semicircle?

* Unit 6 - Part 3 - Feb 26

** What You're Learning
** Capacitance and Capacitors

- Recall from Part 3 - Unit 5, a pair of conductors, insulated from each other, initially neutral, is called a parallel plate capacitor

- You charge the capacitor by connecting it to a battery or by transferring charge between the plates, and building up positive charge on one plate and equal negative charge on the other

- The charge separation creates a potential difference \(\Delta V_c = \epsilon\) (called the EMF) between the plates.

- Q: What factors affect the amount of charge Q in a capacitor like this one?

- Consider a simple model of /ideal/ parallel-plate capacitor and make a guess: \(\epsilon\), A?

- Recall from Unit 5:

- In the /ideal/ parallel-plate capacitor, the electric field is approximately uniform inside and negligible outside
  \[\vec{E}_{\text{capacitor}} = \begin{cases}\left(\frac{Q}{\epsilon_0 A}, \text{ from positive to negative}\right) &\text{inside} \\ \vec{0} &\text{outside}\end{cases}\]

- The figure shows two electrodes of ideal parallel-plate, charged to \(\pm Q\)

- Integrating along a path from the negative plate to positive gives the potential difference \(\Delta V\) (see Ex. 1 in Part 1), that is:

- Part 1: \(V(x) = E_{\text{inside}} x\), with \(E_{
  \text{inside}} = \frac{Q}{A\epsilon_0}\) \[\Delta V_c = E_{\text{inside}} d = \frac{Q \;d}{\epsilon_0 A} \implies Q = C \Delta V_C\]

- Def. The ratio of \(Q\) to the potential difference \(\Delta V_C\) is called the capacitance (symbol C) of the capacitor. This is the QCV theorem.

- Let us assess the QCV theorem result: \[C_{pp} \equiv \frac{Q}{\Delta V_C} = \frac{\epsilon_0 A}{d}\]

- Assess. C = the capacitance is a purely geometric property of two electrodes because it depends only on their surface area and spacing.

- Def. Its SI unit is the farad (F):
  \[1 \text{ farad} = 1 \text{ F} = 1 \text{ C/V}\]

- QCV theorem

** Inserting a Dielectrics into a C (Read Only)

- Fact. Most capacitors have solid insulating materials, or dielectrics, that contain molecular dipoles.

- Fact. If the dielectric fills the space between the two conductors, it reduces the potential difference \(\Delta V\) (why? \(E_{\text{net}} < E_0\)) \[\kappa \equiv \frac{E_0}{E}\] and increases the capacitance C(=Q/ΔV)

** Connecting and Combining Capacitors

- Def. Capacitors connected in parallel have their top plates connected together and their bottom plates connected together.

- Therefore, the potential difference across the two capacitors is the same but Qs adds up.
  \[\Delta V = \Delta V_1 = \Delta V_2 \text{ and } Q = Q_1 + Q_2\]

- In figure (b), we have replaced the capacitors with a single "equivalent" capacitor.
  Its \(C_{\text{eq}}\) is
  \[C_{\text{eq}} = \frac{Q}{\Delta V_C} = \frac{Q_1 + Q_2}{\Delta V_C} = \frac{Q_1}{\Delta V_C} + \frac{Q_2}{\Delta V_C}\]

- Assess. If capacitors \(C_1\), \(C_2\), \(C_3\), ... are in parallel, their equivalent capacitance is always more than the individual Cs:
  \[C_{\text{eq}} = C_1 + C_2 + C_3 + \cdots \qquad \text{(parallel capacitors)}\]

- Def. Capacitors connected in series are wired so that one capactior follows the other.

  + The figure shows that this makes the same charge on the two capacitors the same but potential difference adds:
    \[\Delta V = \Delta V_1 + \Delta V_2 \text{ and } Q = Q_1 = Q_2\]

  + In figure (b), we have replaced the capacitors with a single "equivalent" capacitor.
    Its \(C_{\text{eq}}\) is
    \[\Delta V = \frac{Q}{C_{\text{eq}} = \frac{Q_1}{C_1} + \frac{Q_2}{C_2}\]

  + Assess.
    \[C_{\text{eq}} = \left(\frac{1}{C_1} + \frac{1}{C_2} + \frac{1}{C_3} + \cdots\right)^{-1} \qquad \text{(series capacitors)}\]

** Solving Problems with Capacitors

\begin{align*}
C_{\text{parallel}} &= C_1 + C_2 + C_3 + \ldots \\
\frac{1}{C_{\text{series}}} &= \frac{1}{C_1} + \frac{1}{C_2} + \frac{1}{C_3} + \ldots
\end{align*}

1. Complicated circuits (see (a)) are analyzed by breaking them in steps into parallel ((a) → (b)) and series ((b) → (c)) connections.

2. In each step ((a) → (b) → (c)), you calculate the equivalent capacitances, and redraw the circuit in simpler form.

3. You continue the process until you are left with one (equivalent) capacitor between A and B and then you work in reverse!

** Problem 1 (26.57)

What are the charge on and the potential difference across each capacitor in Figure:

Interpret.

- \(C_1\) and \(C_2\) are in parallel
- \(C_{12}\) and \(C_3\) are in series
- We will use QCV theorem
- We skip calculation of \(\Delta V_i\)

Develop.

- \(Q_3 =\; ?\) \(C_{\text{eq}}\) is a series combo of \(C_{12}\) and \(C_3\).
  They have the same charge:
  \[Q_3 = Q_{12} = Q_{\text{tot}}\]

- \(Q_{\text{tot}} = \;?\) From QCV, \(\Delta V_b\) across \(C_{\text{eq}}\) produces a charge:
  \[Q_{\text{tot}} = C_{\text{eq}} \Delta V_b\]

- \(C_{\text{eq}} = \;?\) \(C_{\text{eq}}\) is a series combo of two capacitors \(C_{12}\) and \(C_3\), so
  \[C_{\text{eq}} = \frac{C_{12} C_3}{C_{12} + C_3}\]

- \(Q_1 = \; ?\) \(Q_2 = \; ?\) Parallel \(C_1\) & \(C_2\) have the same potential difference as the equivalent capacitor \(C_{12}\).
  So the charge on each is given by QCV theorem:
  \[Q_1 = C_1 \Delta V_{12} \text{ and } Q_2 = C_2 \Delta V_{12}\]

- \(\Delta V_{12} = \; ?\) From QCV theorem, \(\Delta V_{12}\) across the 12 capacitor can be computed from now know the charge \(Q_{12}\):
  \[\Delta V_{12} = \frac{Q_{12}}{C_{12}} = \frac{Q_{12}}{C_1 + C_2}\]

Evaluate.

\begin{align*}
Q_1 &= 4.0 \;\mu\text{C} \\
Q_2 &= 12 \;\mu\text{C} \\
Q_3 &= 16 \;\mu\text{C}
\end{align*}

** In class Problem 2 (Extra credit)

A battery with an emf of 60 V is connected to the two capacitors shown in Figure.
Afterward, the charge on capacitor 2 is 450 μC.
What is the capacitance of capacitor 2?

Interpret.

Represent.

Develop.

Evaluate.

Assess.

* Unit 7 - Part 1 - Mar 1

** What You're Learning

- Reading Assignment: 27.1 - 27.3

- What is electron current?

- What is conventional current?

- How are they related?

** The Electron Current

- Goal of Unit 7: study the controlled motion of charges.

- Question: How do we know that something "flows" when for example, a capacitor gets discharged?

- Indicators:

  + makes the wires warm

  + deflects a compass needle

  + makes lightbulbs to glow

- Question: On the MICRO level, what is needed for a flow of charges to occur, say in metals?

- Answer: Several things...

  + First, we need charges free to move.

- Fact: In metals, the outer electrons of metal's atoms--the valence electrons--are only weakly bound to the nuclei, easy to move.

** The Electron Current on MICRO Level

- Fact: In a typical metal conductor, there are TWO motions:

  + The valence electrons are moving at high speed with random thermal velocities that don't result in a new flow of charge.

  + When an electric field is present, it causes a slow drift at speed \(v_d\) to be superimposed on the thermal motion of electrons.

- Q: How this drift speed \(v_d\) determines the rate of flow of electrons?

- Consider wire, at moment \(t\), with the sea of valence electrons moving to the right with \(v_d\).

- Def: the electron current \(i_e\) is the number of electrons per second that pass through a cross section \(A\) of the conductor.

- Q: How to calculate \(i_e\)? A: Take the number \(N_e\) of electrons that pass through the cross section during the time interval \(\Delta t\) and divide it by \(\Delta i\)

  \[i_e = N_e / \Delta t\]

- Q: Is there a more practical expression? A: Yes, if we know the number density of conduction electrions \(n_e\), then the total number of electrons in the shaded cylinder \(N_e\) is
  \[N_e = n_e V = n_e A \Delta x = n_e A v_d \Delta t\]

- Assess. The electron current is related to the drift speed \(v_d\) by
  \[i_e = n_e A v_d\]

** The Electron Current

- We found that the electron current is related to the drift speed \(v_d\) by
  \[i_e = n_e A v_d\]

- Assess. Three quantities matter for the magnitude of \(i_e\): the drift speed- \(v_d\), the area - \(A\) and \(n_e\).

- Fact. In most metals, each atom contributes 1 valence electron to the sea of electrons.

- Fact. Thus, the number of electrons \(n_e\) is the same as the number of atoms per cubic meter.

** Example 1 (Exercise 27.1)

What is the electron current in a 2.0 mm-diameter copper wire if the electron drift speed is \(1.0 \times 10^{-4} \text{ m/s}\)?

Interpret.

- About the size of the electron current in cylindrical wire made of Cu.

Represent.

- r = 1.0 mm = 0.001 m, ne(Cu) = 8.5e28 m^-3, vd = 1.0e-4 m/s, ie = ?

Develop.

- ie = ? From the electron current relation to drift speed
  \[i_e = n_e A v_d\]

- A = ? Circular cross section \(A = \pi r^2\)

- Final expression: \(i_e = n_e \pi r^2 v_d\)

Evaluate. \[i_e = 2.669 \times 10^{19} \approx 2.7 \times 10^{19} \text{ s}\]

Assess.

- The number is high not because \(v_d\) is large but \(n_e\) is enormous.

** Problem 1 (Exercise 27.2)

The electron drift speed in a 1.0mm-diameter gold wire is \(5.0 \times 10^{-5} \text{ m/s}\).
How long does it take 1 mole of electrons to flow through a cross-section of the wire?

Interpret.

- We will use the definition of electron current

- About the size of the electron current in cylindrical wire made of Cu.

Represent.Applications

- Ne = 1 mole, ne(Au) = 5.9e28

Develop.

- \(\Delta t = \;?\) From the definition of the electron current, \(i_e = N_e / \Delta t\) the time for 1 mole of electrons to pass through A is
  \[\Delta t = N_A \times 1 \text{ mole} / i_e\]

- \(i_e = \;?\) Using the relation of the electron current to the drift speed and assuming the circular cross section \(A = \pi r^2\), the electron current:
  \[i_e = n_e (\pi r^2) v_d\]

Evaluate.

\[\Delta t = N_A \times 1 \text{ mole} / (n_e (\pi r^2) v_d) = 6.02 \times 10^{23} / (2.32 \times 10^{18}) = 2.60 \times 10^5 \text{ s} \approx 3.0 \text{ days}\]

Assess.

- \(v_d\) is small, and \(N_A\) is large.
  A long time ~3 days is reasonable.

** The Conventional Current (MACRO)

- Q: How to quantify a flow of charge on MACRO level?

- Def: we define the (conventional) current \(I\) in the wire to be the rate of charge flow (i.e., the amount of charge per second that pass through a cross section \(A\) of a conductor).

  + For a steady current, which will be our primary focus:
    \[I = Q / \Delta t\]
    where \(Q\) is the total amount of charge has moved past a cross section \(A\) in a wire in time interval \(\Delta t\).

- Units: The SI unit of current is the ampere (A), 1A = 1 C/s.

- Fact: the convenctional (electric) current \(I\) and the elctron current \(i_e\) are related (micro-macro conneciton) by \(Q = eN_e\) or
  \[I = \frac{Q}{\Delta t} = \frac{eN_e}{\Delta t} = ei_e\]

** Example 2 (Exercise 27.14)

The current in a 2.0mm * 2.0mm square aluminum wire is 2.5 A.
What is the electron's drift speed?

Interpret.

- Problem about macro-micro relationship.

- The cross section is rectangular (a square)

* Unit 7 - Part 2 - Mar 3

** What You've Learned in Part 1

- Recall that current is an ordered motion of charges in a wire.

- On the micro level, the sea of electrons flows through the wire at the drift speed \(v_d\)

- Def. On macro level, the electron current \(i_e\) is the number of electrons \(N_e\) passing through a cross-section per second:
  \[i_e = N_e / \Delta t\]

- Fact. The electron current is related to the drift speed by
  \[i_e = n_e A v_d\]

- Def. On macro level, the (conventional) current is the rate of charge flow:
  \[I = Q / \Delta t\]

- Fact. The current I is related (micro-macro connection) to the electron current by
  \[I = ei_e = en_e A v_d\]

** The Current Density

- Fact. Currents aren't confined to wires, so their magnitude and direction may vary with position in the conducting medium.
  In such cases, we characterize the flow, not by \(I\) but by a local vector quantity called current density \(\vec{J}\) (P) with magnitude \(J = dl/dA\):

  + Use \(I = ei_e = en_e A v_d\) to obtain:
    \[J = en_e v_dv \implies \vec{J} = nq\vec{v}_d\]

- Assess.

  - Units: the current density has units \(\text{A/m}^2\) (\(J = dl/dA\))

  - The direction of the vector at each point is of that of local flow and the magnitude is the /current per unit area/.

  - In general, when \(\vec{J}(P)\) varies from point to point, the (conventional) current through an area is a surface integral of the current density over that area:
    \[I = \int_{\text{area}} \vec{J} \cdot d\vec{A}\]

  - Popular model:
    When current density is uniform (=does not vary over from point to point, over area) and is perpendicular to a flat area, current \(I\) becomes the product of \(J\) and \(A\):
    \[I = JA\]

** Example 1 (Exercise 27.15)

A hollow copper wire with an inner diameter of 1.0mm and an outer diameter of 2.0mm carries a current of 10A.
What is the current density in the wire?

Interpret.

- We will assume/use the uniform model of current density.

Represent.

- r2 = 0.0005 m, r1 = 0.0001m, I=10.A
- Target J=?

Develop.

- \(J = I/A\)
- \(A = \pi({r_1}^2 - {r_2}^2)\)
- \(J = I/(\pi({r_1}^2 - {r_2}^2))\)

Evaluate.

\[J \approx 4.3 \times 10^6 \text{ A/m}^2\]

** Problem 1 (CALC) (27.65)

A wire of radius \(R\) has a current density that increases linearly with distance from the center of the wire:
\(J(r) = kr\), where \(k\) is a constant.
Find an expression for \(k\) in terms of \(R\) and the total current \(I\) carried by the wire.

Interpret.

- About a current density that is non-uniform and it is modeled as a linear function of the radius.

- The relationship between current density and the current will be used.

Represent.

- I, R, target k=?

Develop.

- k = ?

  \[I = \int_{\text{area}} \vec{J} \cdot d\vec{A} = \int_0^R kr \cdot 2\pi r\;dr = \frac{2}{3} \pi kR^3\]

- Final expression: \[k = \frac{3I}{2\pi R^3}\]

Assess.

- Units are in \(A/m^3\)

** Conservation of Current and the Junction Rule

- Fact. There are TWO laws that govern the flow of current.

- Law #1. Due to conservation of charge, the current \(I\) must be the same at all cross sections along a current-carrying wire.

- Law #2. For a junction, the law of conservation of current requires that
  \[\sum I_{\text{in}} = \sum I_{\text{out}}\]
  where the ∑ symbol means summation.

- This basic statement is called Kirchhoff's junction law.

** Problem 2 (27.62)

The two wires in Fig. are made of the same materials.
What is the electron drift speed in the 2.0-mm diameter segment of the wire?

Interpret.

- About the drift speeds in two segments.
  We will use the micro-macro relationship:
  \[J = nev_d\]

- The currents are the same (EQUATION) in both segments.

- We assume uniform model of current density

- The same materials means that the electron densities are the same

- Prediction. \(v_2 < v_1\)

Represent.

- We will denote all quantities for the 1.0-mm-diameter wire with the subscript 1, and all quantities for the 2.0-mm-diameter wire with the subscript 2.

- \(I_1 = 2 \text{ A}\)

- \(D_1 = 0.001 \text{ m}\)

- \(D_2 = 0.002 \text{ m}\)

- \(v_1 = 2 \times 10^{-4} \text{ m/s}\)

- Target \(v_2 = \;?\)

Develop.

- \(v_2\) = ?
- The currents are the same in both segments.
- We use the uniform model then the micro-macro relationship:
  \[I_1 = I_2 \implies J_1 A_1 = J_2 A_2 \implies nev_1 A_1 = nev_2 A_2\]
- \(A = \;?\) Circular cross section: \(A = \pi D^2 / 4\)
- Final expression: \(v_2 = (D_1/D_2)^2 v_1\)

Evaluate.

\[v_2 = (D_1/D_2)^2 v_1 = 5.0 \times 10^{-5} \text{ m/s}\]

Assess.

- A drift speed that is small and only 1/4 of \(v_1\)

- It's reasonable.

** In-class Problem #1

An aluminimum wire consists of three segments shown in Fig.
The current in the top segment is 10 A.
For each of these three segments, find the drift speed.
Place your results in a table for easy viewing.

* Unit 7 - Part 3 - Mar 5

** What You've Learned in Part 1 & 2

- Current is an ordered motion of charges in a wire.
  On the micro level, the sea of electrons flows through the wire at the drift speed \(v_d\).

- The electron current \(i_e\) is the number of electrons \(N_e\) passing through a cross-section of the wire per second:
  \[i_e = N_e / \Delta t\]

- The electron current is related to the drift speed by \[i_e = n_e A v_d\]

- On macro level, we measure the (conventional) current (=the rate of charge flow):
  \[I = Q / \Delta t\]

- The current \(I\) is related (micro-macro connection) to the electron current \(i_e\) by \[I = ei_e\]

- In the uniform density model, the current density is \(J = I/A\).

** Establishing the Elect. Field in a Wire

- In Part 1 and 2, we learned how to describe motion of electrons through a wire as a current.
  In Part 3 we pose a question:

- Question: What is needed for a sustained flow of charges to occur?

- A: Consider a book on a table will slow down and stop unless you continue pushing.

- Analogously, the sea of electrons will slow down and stop unless you continue pushing with an electric field.

** Establishing the Elect. Field in a Wire (Read)

- Q: How is the electric field produced?

- Consider an electrostatic situation (two wires + capacitor) with uniform surface density and the field (E = 0) everywhere inside

- This distribution creates an electric field (E ≠ 0) \(\approx\) uniform inside the wire that pushes the electron current

** A Micro Model of Conduction in Metals

- In the presence of the uniform E field, the electric forces causes the x-component of the electron's velocity to increase with \(\Delta t\):
  \[v_x = v_{0x} + a \Delta t = v_{0x} + (eE/m) \Delta t\]

- So, take time average over a series of collisions and the electron's (avergae) drift speed is \[v_d = \frac{e\tau}{m} E\] where \(\tau\) (lower case Greek tau) is the mean time interval between collisions.

- Subsituting to Eq. 27.3 (\(i_e = n_e A v_d\)) we get
  \[i_e = \frac{n_e e \tau A}{m} E\]

- Assess. the electron current is directly proportional to the field strength \(E\) and the cross-section \(A\) of the wire.

** The Local Form of Ohm's Law

- Recall from Part 2:
  J(P) is local and E(P) is local,
  so let us the uniform model: \(J = ei_e / A\) and substitute \(i_e\) from Eq 27.8.
  The area A cancels out and we obtain:
  \[J = ei_e / A = (n_e e^2 \tau / m) E\]

- Assess. The current density J(P) turns out to be directly proportional to the electric field strength E(P).
  We can write \[J = \sigma E\]

- This important relation is the local form of Ohm's law where the proportionality constant \(\sigma\) (lower case sigma letter) is called the conductivity of the material.

  \[\sigma = \text{conductivity} = \frac{n_e e^2 \tau}{m}\]

** Conductivity and Resistivity

- Assess. Conductivity, like density, characterizes a material the wire is made of.

- Def. The reciprocal of \(\sigma\) is called the resistivity (lower case rho letter): \[\rho = \text{resistivity} = \frac{1}{\sigma} = \frac{m}{n_e e^2 \tau}\]

- Assess. The resistivity tells us how reluctantly the electrons move in response to an electric field.

- In the next section, we will introduce a new unit, the ohm, symbol \(\Omega\) (upper case Greek omega).

- Units: The SI units of \(\rho\) are \(\Omega \cdot \text{m}\)

** Example 1 (Exercise 27.20)

A 2.0-mm diameter iron wire carries a current of 5.0A.
What is the electric field strength inside of the wire?

Interpret.

1) About the local version Ohm's law
2) We assume a uniform density model.

Represent.

3) \(r = 1.0\times 10^{-3} \text{ m}\)
4) \(I = 5.0 \text{ A}\)
5) \(\sigma_{\text{Fe}} = 1.0 \times 10^7 (\Omega \cdot \text{m})^{-1}\)
6) Target E = ?

Develop.

1) E = ? \(E = J/\sigma\)
2) J = ? \(J = I/A\)
3) A = ? \(A = \pi r^2\)
4) Final expression: \[E = \frac{I}{\pi\sigma r^2}\]

Evaluate.

\[E = \frac{5.0 \times 10^{-7 + 6}}{3.14} = \frac{5.0}{31.4} = 0.159236 \approx 0.16 \text{ V/m}\]

Assess.

- Rounded off to 2 sig. figs.
- Units N/C = V/m
- The value is a lot smaller than E we discussed in electrostatic situations.

** Resistance and Ohm's Law

- Q: What matters for the size of conventional current \(I\) flowing through that say, hair dryer?

- A clue is in the diagram

- Step #1: The micro version of Ohm's law, related the current density \(J\) to the electric field \(E\):
  \[J = \frac{E}{\rho}\]

- Step #2: (uniform flow model): Now, assume that the flow has uniform density (\(I = JA\)) and \(E\) is uniform field with the potential diff. across: \(\Delta V = EL\), both when combine give:
  \[I = JA = EA / \rho = ELA / \rho L \implies I = \frac{A}{\rho L} \Delta V\]

** Resistance and Ohm's Law

- Now let's introduce a definition: \(R = \frac{\rho L}{A}\)

- Def. The proportionality constant \(R\) is called the resistance.

- Assess. It measures how hard it is to push charges through a wire segment \(L\).

- Units. The SI unit is the ohm. 1 ohm = 1 Ω = 1 V/A

- Fact. The definition allows us to rewrite Eq 27.21 as the answer to the question on slide #10.

- Answer:
  \[I = \frac{\Delta V}{R} \quad \text{(Ohm's law)}\]

** Problem 1 (Exercise 27.28)

An engineer cuts a 1.0-m-long, 0.33-mm-diameter piece of wire, connects it across a 1.5 V battery, and finds that the current in the wire is 8.0 A.
Of what material is the wire made?

Interpret.

1) The problem is about the conductivity
2) Ohm's law and uniform flow model
3) Assume the wire has a circular cross section.

Represent.

- L = 1.0m, r = 0.165e-3 m, ΔV = 1.5 V, I = 8.0 A, ρ = ?

Develop.

1) ρ = ? Uniform model: \(R = \rho L/A \implies \rho = RA / L\)
2) R = ? Ohm's law \(R = \Delta V / I\)
3) A = ? Geometry \(A = \pi r^2\)

Evaluate.
\[\rho = \frac{\Delta V A}{IL} = 1.60287 \times 10^{-8} \approx 1.6 \times 10^{-8}\]

Assess. From Table 27.2 this resistivity is of silver.

** Problem 2 (Problem 27.31)

The terminal of a 0.70 V are connected by a 100-m long gold wire with a 0.10mm in diameter.
What is the current in the wire?

Interpret.

1) Uniform flow model and Ohm's law

Represent.

\begin{align*}
\Delta V &= 0.70 \text{ V} \\
L &= 100 \text{ m} \\
r &= 0.05 \text{ mm} \\
\rho &= 2.4 \times 10^{-8}
\end{align*}

Develop.

1) I = ? \(I = \frac{\Delta V}{R}\)
2) R = ? \(R = \frac{\rho L}{A}\)
3) Final expression: \[I = \frac{\Delta V \pi r^2}{\rho L}\]

Evaluate.
\[I = \frac{\Delta \pi \left(\frac{d}{2}\right)^2}{\rho L} = \frac{0.7 \pi}{(4)(2.4)(100)} = 0.00229 \approx 2.3 \text{ mA}\]

Assess.
- 2 sig figs.
- small value so in mA.

** In-class Problem #2:

You're writing the instruction manual for a power saw, and you have to specify the maximum permissible length for an extension cord made from 18-gauge copper wire (diameter 1.0 mm).
The saw draws 13.0 A and needs a minimum of 115 V across its motor when the outlet supplies 120 V.
What do you specify for the maximum length extension cord, given that they come in 25-foot increments?
Hint: 1 ft = 0.3048 m.

Interpret.
1) Answer: max length
2) But the uniform model will translate the max length into max resistance
3) Ohms law will translate the max resistance into max voltage per wire.

Represent.
\begin{align*}
\rho_{\text{Cu}} &= 1.7 \times 10^{-8} \\
\Delta V_{\text{max}} &= 2.5 \text{ V} \\
I &= 13 \text{ A} \\
r &= 0.5 \text{ mm}
\end{align*}
Target: \(L_{\text{max}} = \;?\)

* Unit 8 - Part 1 - Mar 8

** What You're Learning

- Reading Assignment: 28.1 - 28.3

- To read and draw electric-circuit diagrams

- How are circuits analyzed?

- To calculate the rate at which the battery supplies energy to a circuit

- To calculate the rate at which a resistor dissipate energy to a circuit

** Introduction

- In Unit 7, we discussed flow of current in a simple circuit

- In Unit 8, we will introduce more general principles enabling us to analyze more complex circuits involving combinations of batteries, and resistors

- Note: In Unit 8, we will consider only circuits operating in their steady state (= DC circuits)

** Circuit Elements and Diagrams

- Def: We will use the ideal-wire model: an electric circuit is a collection of electrical components connected by good (R=0) conductors.

- When using the ideal wire model, we represent real circuits (a) by diagrams (b) implementing and following two rules:

  + Components such as batteries, capacitors and resistors are represented by symbols

  + Connecting wires with R=0 are represented by straight lines

** Circuit Elements and EMF (Read ONLY)

- Fact: To maintain a steady flow of charge we need to supply energy. Why?

- The positive charge "falls downhill" through the resistor (with R ≠ 0) but the flow can be sustained only if there is the charge escalator lifting positive charge from lower potential (-) terminal to the higher (+) terminal

- Fact: a battery has an internal source of energy that keep the charge escalator running.

- Def. The value of the energy imparted per unit charge in "lifting" charge against the electric field is called the electromotive force (in short, emf) of a battery as is denoted (\(\mathcal{E}\)).

- Units. emf units are volts (1 V = 1 J/C).

** Kirchhoff's Laws and the Basic Circuit

- Kirchhoff's junction law:

- For a junction, the law of conservation of current requires that
  \[\sum I_{\text{in}} = \sum I_{\text{out}}\]

- Kirchhoff's loop law:

- For a loop (any path that starts and ends at the same point), the law of conservation of energy requires that
  \[\Delta V_{\text{loop}} = \sum (\Delta V)_i = 0\]

- In words: the sum of all the potential differences encountered while walking around a loop is zero.

- Note: Eq. (28-2) can be true only if at least one \((\Delta V)_i\) is negative.

** Kirchhoff's Loop Rule

- Question: When you walk around a loop, which potential differences are positive, which are negative?

  - For an ideal battery in the negative-to-positive direction:
    \[\Delta V_{\text{bat}} = +\mathcal{E}\]

  - For an ideal battery in the positive-to-negative direction:
    \[\Delta V_{\text{bat}} = -\mathcal{E}\]

  - For a resistor: \[\Delta V_{\text{res}} = -\Delta V_R = -IR\]

- For a resistor, traversed in the direction you've assigned to the current, \(\Delta V_{\text{res}}\) is \(-IR\) ("drop" means negative value);

** Kirchhoff's Laws and the Basic Circuit

- Recall from Unit 7, the most basic electric circuit is a single load (resistor, bulb, or a device) connected to the two terminals of a battery.

- Figure (a) shows a literal picture of the circuit elements and the connecting wires.

- Figure (b) is the circuit diagram.

- Question: How to use Kirchhoff's laws to analyze this circuit?

- Facts. This circuit has no junction.

- Assume the same CW current I is in all four sides.

- Kirchhoff's junction law not needed.

- Question. How to find the current \(I\)?

- Answer. Let us use the ideal wire model, in which there is no voltage drop along the wires

- Then the loop rule with two elements: battery and the resistor, requires:
  \[\Delta V_{\text{bat}} + \Delta V_{\text{res}} = 0\]

- Now, let's look at each of the two voltages.

  + We travel through the battery from - to + so, \(\Delta V_{\text{bat}} = +\epsilon\).

  + And through the load, with the flow of the current,
    \[\Delta V_{\text{res}} = -IR \implies I = \mathcal{E} / R\]

** Energy and Power

- Consider again the basic circuit with a battery which sets up a current \(I\) and a potential difference \(\Delta V\) across a device (e.g., a bulb or hot plate)

- Q: What is the rate at which battery supplies energy to the charge. A: \(P_{\text{bat}} = \frac{dU}{dt} = \frac{dq}{dt} \Delta V_{\text{bat}}\)
  \[P_{\text{bat}} = I \mathcal{E} \quad \text{(power delivered by an emf)}\]

- Recall: The units of power are J/s or W.

- The energy delivered by \(\mathcal{E}\) is transferred into the thermal energy of the resistor, raising its temperature. The rate of transfer is
  \[P_R = \frac{dE_{\text{th}}}{dt} = \frac{dq}{dt} \Delta V_R = I \Delta V_R\]

- Using Ohm's law \(\Delta V_R = RI\), we can write
  \[P_R = I \Delta V_R = I^2 R = \frac{(\Delta V_R)^2}{R} \quad \text{(power dissipated by a resistor)}\]

- Assess. If \(I\) is the same, the most \(P\) will be dissipated by the largest \(R\).

** Kilowatt Hours

- Fact. The product W * sec = J, is the primary SI unit of energy.

- However, most electric companies prefers to use the kilowatt hour (kW * h, not W * sec), to measure the energy you use each month.

- Examples:

  + A 4000 W (=4 kW) electric water heater uses 40 kWh of energy in 10 hours.

  + A 1500 W (= 1.5 kW) hair dryer uses 0.25 kWh of energy in 10 minutes (= 1/6 hr).

  + Fact. The average cost of electricity in the United States is 10¢ per kWh (= $0.10/kWh)

** Problem 1 (G25.79)

A 2800-W oven is connected to a 240-V source.
The oven brings 120 mL of water at 15°C to boiling.
Assuming 75% efficiency of the oven, how much will this cost at 11¢/kWh?

Interpret.

1) About energy consumption in a simple circuit.

2) Power delivered to oven and efficiency, specific heat

Represent.

- c_water = 4186 J/kg C
- ΔT = 85°C
- M = 0.120 kg
- P_oven = 2800 W = 2.8 kW
- efficiency = 0.75
- price = $0.11 / kWh

Develop.

- Cost = ? The concept of price in units kWh: Cost = price * P_oven * (Δt in sec *Conversion sec to hr)

- Δt in sec = ? Using the efficiency and power; then the specific heat
  Energy used for heating = 0.75 * P_oven * Δt in sec = M*c*ΔT => Δt in sec = M*c*ΔT/(P_oven * 0.75)

Evaluate.

- 0.17 cents.

Assess.

- small cost - a fraction of a cent and given with 2 sig. figs.

* Unit 8 - Part 2 - Mar 10

** What You're Learning

- Reading Assignment: 28.4 - 28.7

- To combine resistors in series

- Ammeters

- What are real batteries? (read only)

- What is a short circuit? (read only)

- To combine resistors in parallel

- Voltmeters

** Series Resistors

- The figure above shows two resistors connected in series between points a and b.

- Fact #1: There is no junction in the system, so the current \(I\) is the same through the two resistors placed in series.

- Fact #2: The total potential difference between points a and b is the sum of the individual potential differences across \(R_1\) and \(R_2\):
  \[\Delta V_{\text{ab}} = \Delta V_1 + \Delta V_2 = IR_1 + IR_2 = I(R_1 + R_2)\]

- Assess. The series combo is a voltage divider:
  \(\Delta V_1 = \frac{R_1}{R_1 + R_2} \Delta V_{\text{ab}}\) and \(\Delta V_2 = \frac{R_2}{R_1 + R_2} \Delta V_{\text{ab}}\).

- Suppose we replace \(R_1\) and \(R_2\) with a single resistor: \(R_{\text{ab}}\) with the same current \(I\) and the same potential difference \(\Delta V_{\text{ab}}\).

- Ohm's law gives resistance between points \(a\) and \(b\):
  \[R_{\text{ab}} = \frac{\Delta V_{\text{ab}}}{I} = \frac{I(R_1 + R_2)}{I} = R_1 + R_2\]

- If we have \(N\) resistors in series, their equivalent resistance is
  \[R_{\text{eq}} = R_1 + R_2 + \cdots + R_N \quad \text{(series resistors)}\]

- General rules: Resistors in series add.
  They have the same I.

** Real Batteries (Read Only)

- Fact: When a current is drawn from a real battery, the voltage across its terminals drops to, so called terminal voltage value ,below its rated emf
  \[\Delta V_{\text{terminal}} < \mathcal{E}\]

- Q: Why?

- A: Real battery provides always some hindrance to completely free flow of charge.

- Fact: A real battery is modeled as if it were a perfect emf in series with a resistor \(r\).

- So \(\Delta V_{\text{terminal}} = \mathcal{E} - I \cdot r \leq \mathcal{E}\)

- Hence the current in a circuit path real battery is \(I = \frac{\mathcal{E}}{R_{\text{eq}}} = \frac{I}{R + r}\)

- The behavior of the circuit will be unchanged if the N series resistors are replaced by the single resistor \(R_{\text{eq}}\).

** Ammeters

- Fact: an ammeter measures the current in a component.

- Q: How to use the device?

- A: Connect an ammeter in series with the component whose current you're measuring (e.g., R)

- Fact: an ideal ammeter has zero resistance (R=0), so it doesn't affect the circuit being measured.

- Fact: a real ammeter should have \(R_A \ll R\) than resistances in the circuit being measured.

** Parallel Resistors

- The figure above shows two resistors connected in parallel between points c and d.

- Fact #1: There are two equivalent paths between c and d, so the potential differences \(\Delta V\) are the same across two resistors placed in parallel:
  \[\Delta V_{\text{cd}} = \Delta V_1 = \Delta V_2\]

- Fact #2: By Kirchhoff's junction law, the input current is the sum of the current through the resistor: \(I = I_1 + I_2\)
  \[I = \frac{\Delta V_1}{R_1} + \frac{\Delta V_2}{R_2} = \frac{\Delta V_{\text{cd}}}{R_1} + \frac{\Delta V_{\text{cd}}}{R_2} = \Delta V_{\text{cd}} \left(\frac{1}{R_1} + \frac{1}{R_2}\right)\]

- Suppose we replace \(R_1\) and \(R_2\) with a single resistor \(R_{\text{cd}}\) with the same current \(I\) and the same potential difference \(\Delta V_{\text{cd}}\)

- Using Eq. 28.22 Ohm's law gives resistance between points c and d:
  \[R_{\text{cd}} = \frac{\Delta V_{\text{cd}}}{I} = \left(\frac{1}{R_1} + \frac{1}{R_2}\right)^{-1} = \frac{R_1 R_2}{R_1 + R_2}\]

- If we have N resistors in parallel, their equivalent resistance is
  \[R_{\text{eq}} = \left(\frac{1}{R_1} + \frac{1}{R_2} + \cdots + \frac{1}{R_N}\right)^{-1} \quad \text{(parallel resistors)}\]

- General rule: Resistors in parallel add in reciprocals.
  They have the same potential difference.
  \(R_{\text{eq}}\) is smaller than any \(R_i\).

- Fact: The behavior of the circuit will be unchanged if the \(N\) parallel resistors are replaced by \(R_{\text{eq}}\).

** Problem 1 (Exercise 28.23)

What is the value of resistor R in the figure?

Interpret.

- This problem involves three resistors in parallel.
- Use Ohm's law and junction rule.

Represent.

- R1 = 10, R2 = 15, ΔV = 8V, I = 2A, R = ?

Develop.

- R = ? From Ohm's law to calculate R from ΔV; R = ΔV/I3
- I3 = ? Current conservation
- I1 = ? I2 = ? The voltage the same & Ohm's law I1 = ΔV/R1, I2 = ΔV/R2

Evaluate.

- R = 12 Ω

Assess.

I1 = 4/5, I2 = 8/15, I3 = 10/15
The currents add up to 2 A.

** Problem 1 (Exercise 28.23)

What is the value of resistor R in the figure?

Develop.

- R = ? Use formula Req = (1/R1 + 1/R2 + 1/R)^-1
- Req = ? Use Ohm's law to calculate Req = ΔV/I

** Voltmeters

- Fact: a voltmeter measures the potential difference across a component or between its two terminals.

- Q: How to use a voltmeter?

- A: Connect a voltmeter in parallel with the component whose voltage you're measuring (e.g., R2)

- Fact: an ideal voltmeter has infinite resistance (R=∞) so it doesn't affect the circuit being measured.

- Fact: a real voltmeter should have a resistance much greater than resistances in the circuit being measured.

* Unit 8 - Part 3 - Mar 12

** What You're Learning

- Reading Assignment: 28.7

- How to analyze resistor circuits with one battery?

- How to analyze resistor circuits with several batteries?

** What You've Learned in Part 2

- The series combo is a voltage divider:
  \(\Delta V_1 = \frac{R_1}{R_1 + R_2} \Delta V_{\text{ab}}\)
  and
  \(\Delta V_2 = \frac{R_2}{R_1 + R_2} \Delta V_{\text{ab}}\)

- The parallel combo is a current divider:
  \(I_1 = \frac{\Delta V_{\text{cd}}}{R_1}\)
  nd
  \(I_2 = \frac{\Delta V_{\text{cd}}}{R_2}\)

** Resistor Circuits

- To analyze a circuit with one battery and several resistors, look for series and parallel combinations

- Then, follow these steps:

  + Calculate the equivalent resistances, and redraw the circuit in simpler form

  + Look again for series and parallel combinations and repeat step 1

  + You continue the process until you are left with (one) requivalent resistor between terminals of a battery or the circuit is reduced the basic circuit.

- Note: this technique is similar to the technique used in combining capacitors.

** Problem 1 (Problem 28.60)

(a) Determine the equivalent resistance of the circuit shown in the Fig. below. (b) Find the current through the battery.

Interpret.

- R2 & R3 & R4 are in parallel

Develop.

- Req = ? R234 is in series with R1 So Req = R234 + R1

- R234 = ? R2, R3, R4 are in parallel

  + R234 = (R2 * R3 * R4) / (R2 * R3 + R2 * R4 + R3 * R4)

- Ib = ? The basic circuit \(I_b = \frac{\mathcal{E}}{R_{\text{eq}}}\)

Evaluate.

- R234 = 3 Ω, Req = 6 Ω, Ib = 2A

Assess.

- One digit and proper units.
  You could check currents.

- Can you use the same method to solve this circuit (PSW)

** Resistor Circuits with Several Batteries

- Some circuit can be reduced to the basic circuit using series and parallel combinations (see on the left).

- Some circuits cannot be solved using to series-parallel analysis (see on the right).

- Then it's necessary to use Kirchoff's node and loop rules.

** Kirchhoff's Laws (REVIEW)

- Recall: The junction rule states that at any circuit node, the total current into the junction equal the total current leaving the junction \[\sum I_{\text{in}} = \sum I_{\text{out}}\]

- To use the junction rule, follow this procedure: Introduce symbols for all the currents I, and assume directions (arrows) in each branch

- Write Kirchhoff's junction for all independent node

- For node A: \(-I_1 + I_2 + I_3 = 0\)

- For node B: \(+I_1 - I_2 - I_3 = 0\)

- Fact #1: The loop rule states that the sum of all the potential differences around a closed loop is zero.
  \[\sum (\Delta V)_i = 0\]

** Using Kirchoff's Laws

Solving problems with several batteries, follow this procedure:

1. Label each current (a symbol for value and arrow for the direction).

2. For all but one node, write equations expressing node rule.

3. For as many independent loops as necessary (count # of unknown currents), write equations expressing loop rule.

4. Solve the set of equations to determine the unknown currents or other quantities.

5. Assess your answer verifying that the parallel branches have the same potential differences across them.

** Problem 1 (Example 28.10)

Develop.

1) Write the node equation.
   \[I_1 - I_2 - I_3 = 0\]

2) Two loop equations for the left and right loops (CW):
   \begin{align*}
   19 - 12 - 300 I_1 - 100 I_3 &= 0 \\
   12 + 100 I_3 - 200 I_2 &= 0
   \end{align*}

Evaluate.

- We eliminate \(I_2\) using the (N) eq. (\(I_2 = I_1 - I_3\)) in the R eq.

  \begin{align*}
  7 - 300 I_1 - 100 I_3 &= 0 \\
  12 + 300 I_3 - 200 I_1 &= 0
  \end{align*}

- Then, add 3X(L) to (R) to eliminating \(I_3\).

- We obtain the solution for \(I_1\): \(I_1 = 33/1100 = 3/100 = 30\) mA.

* Unit 9 - Part 1 - Mar 15

** What You're Learning

Reading Assignment: 29.1-29.3

1. The facts about magnetism (read only).

2. The discovery of the magnetic field.

3. The sources of magnetic field: moving charges.

** Basic Facts about Magnetism

1. Magnets have two poles called north and south poles, and thus they're mag. dipoles.

2. Two like poles exert repulsive forces on each other; two opposite poles attract.

3. Magnets also exert force on certain materials, like iron- see the picture

4. The magnetic force--like the electric force--acts over a distance


Q: How to explain the action at a distance?

   - As we did for the electric forces, we describe the interaction as a two-step process:
     One magnet produces a magnetic field \(\vec{B}\), and another responds to the field in its vicinity
** Properties of the magnetic field

Let us define the magnetic field \(\vec{B}\) as having the properties:

1. A magnetic field is alteration of space surrounding a magnet.

2. The magnetic field at each point is a vector.
   It has both a magnitude (called the field strength) and a direction.

3. The magnetic field exerts forces on magnetic poles.
   The force on a north pole is parallel to \(\vec{B}\);
   the force on a south pole is opposite \(\vec{B}\).

Result: A compass needle can be used as a probe of the field.

Question: How magnetic field occurs in space?

** The Discovery of the Magnetic Field

Fact: In 1819, Hans Christiian Oersted discovered that an electric current in a wire causes a compass to turn.

** Explanation of the discovery

Current is a flow of electric charge, so to explain the discovery, we have to assume that moving charges are the source of magnetic field.

** Determining the orientation of the compass needles

The Right-Hand Rule determines the orientation of the compass needles to the direction of the current.

1. Point your /right/ thumb in the direction of the current.

2. Curl your fingers around the wire to indicate a circle.

3. Your fingers point in the direction of the magnetic field lines around the wire.

** Notation Convention

- Fact: Magnetism requires a 3D perspective, but 2D figures are easier to draw.

- Use 'x' to represent vectors into the page.

- Use '·' to represent vectors out of the page.

Magnetic field lines are imaginary lines drawn through a region of space following two rules:

1. A tangent of a field line is in the direction of the magnetic field.

2. The field lines are closer together where the magnetic field strength is larger.

** REVIEW: The Cross Product

- Def: the cross product \(\vec{C}\) of two vectors \(\vec{A}\) and \(\vec{B}\) has a magnitude \(C = AB \sin{\theta}\) (where \(\theta\) is the angle between \(\vec{A}\) and \(\vec{B}\)) and where the direction given by the right-hand rule.

- It is written: \(\vec{C} = \vec{A} \times \vec{B}\)

- Some properties of cross products:
  \begin{align*}
  \vec{A} \times \vec{B} &= -\vec{B} \times \vec{A} \\
  \vec{A} \times (\vec{B} + \vec{C}) &= \vec{A} \times \vec{B} + \vec{A} \times \vec{C}
  \end{align*}

** Magnetic Field of a Moving Charge

- Fundamental Law #1 of Magnetism (B-S):

  Moving charges are the source of the magnetic field.

- The Biot-Savart law describes the magnetic field at the position of the dot of a point-like charged particle q moving with velocity v:
  \[\vec{B}_{\text{point charge}} = \frac{\mu_0}{4\pi} \frac{q\vec{v} \times \vec{r}}{r^2} \qquad \text{(magnetic field of a point charge)}\]
  where the constant (denoted \(k' = \frac{\mu_0}{4 \pi} = 10^{-7}\) exact!)
  \[\mu_0 = 4\pi \times 10^{-7} \text{ T m/A} = 1.257 \times 10^{-6} \text{ T m/A}\]
  is called the permeability constant:
- Recall: the vector cross product concept

** Biot-Savart law similar to Coulomb's law

The Biot-Savart law is like Coulomb's law for the electric field.
\[\vec{E} = \frac{1}{4\pi\epsilon_0} \frac{q}{r^2} \hat{r} \quad \text{(electric field of a point charge)}\]
\[\vec{B}_{\text{point charge}} = \frac{\mu_0}{4\pi} \frac{q\vec{v} \times \hat{r}}{r^2} \quad \text{(magnetic field of a point charge)}\]

** Problem 1 (Exercise 29.6)

What is the magnetic field at the position of the dot in Figure?
Give your answer as a vector.

Interpret.

1) A point charge is moving with a constant velocity along x-axis.
2) The problem involves the Biot-Savart law.
3) The concept of vector product will be used.
4) Predict: Into the page

Represent.

- \(q = 1.60 \times 10^{-19} \text{ C}\)
- \(x_q = y_P = 1 \text{ cm} = 10^{-2} \text{ m}\)
- \(v = 2.0 \times 10^7 \text{ m/s}\)
- \(k' = 10^{-7}\)
- \(\mu_0 = 4\pi \times 10^{-7} \text{ T m/A}\)
- The point P is on the y-axis:
  + \(\vec{r}_P = y_P \hat{j}\)
- The charge is on the x-axis
  + \(\vec{r}_q = x_q \hat{i}\)
- The velocity vector is pointing along the neg. x-axis:
  + \(\vec{v} = v(-) \hat{i}\)
- The target quantity is \(\vec{B}(P) = \;?\)

Develop.

- \(\vec{B}(P) = \;?\) The Biot-Savart law gives us the plan:
  \[\vec{B}_{\text{point charge}} = \frac{\mu_0}{4\pi} \frac{q\vec{v} \times \vec{r}}{r^2}\]

- We only need to construct the unit vector from q to P;

  + first the position vector from q to P: \(\vec{r} = \vec{r}_P - \vec{r}_q = y_P \hat{j} - x_q \hat{i}\)

  + and the corresponding unit vector: \(\hat{r}\)
    \[\hat{r} = \frac{y_P \hat{j} - x_q \hat{i}}{\sqrt{{x_q}^2 + {y_P}^2}}\]

  + The final expression for the magnetic field at P is
    \[\vec{B}(P) = \frac{k' q v(-\hat{i}) \times (y_P \hat{j} - x_q \hat{i})}{r^3} = \frac{k' q v y_P (-\hat{k})}{r^3}\]

Evaluate.
\[\vec{B}(P) = B*(-) \hat{k}\]

\[B = 10^{-7} \cdot 1.6 \times 10^{-19} \cdot 2 \times 10^7 \cdot 10^{-2} / (2^{1.5} \times 10^{-6}) \approx 1.13 \times 10^{-15} \text{ T}\]

Assess. Small value, in T, B vector points into the page as predicted.

* Unit 9 - Part 2 - Mar 17

** What You're Learning

- Reading Assignment: 29.4

- Superposition of magnetic fields

- How magnetic fields originate from a steady current distribution (the Biot-Savart law)

- The magnetic field produced by a long straight wire carrying a steady current

- The magnetic field produced by circular loop carrying a steady current.

** Summary: Magnetism - Part 1

- Fundamental Law #1 of Magnetism:
  Moving charges are the source of the magnetic field.

- The Biot-Savart law describes the magnetic field at the position of the dot of a point-like charged particle q moving with velocity v:
  \[\vec{B}_{\text{point charge}} = \frac{\mu_0}{4\pi} \frac{q\vec{v} \times \hat{r}}{r^2} \qquad \text{(magnetic field of a point charge)}\]
  where the constant \(k' = \frac{\mu_0}{4\pi} = 10^{-7}\) where \(\mu_0 = 4\pi \times 10^{-7} \text{ T m/A} = 1.257 \times 10^{-7} \text{ T m/A}\) is called the permeability constant:

** Superposition of Magnetic Fields

- Fact: There are many charges moving inside of the wire.

- Q: How to explain the Oersted discovery about the magnetic field of electric current distribution?

- A: We need additional principle:

- Fact: Magnetic fields, like electric fields, have been four experimentally to obey the principle of superposition.

- If there are n moving point charges, the net (total) magnetic field is given by the vector sum:
  \[\vec{B}_{\text{total}} = \vec{B}_1 + \vec{B}_2 + \cdots + \vec{B}_n\]

- This principle will be the basis for calculating the magnetic fields of several important current distributions:

  + Long straight wire

  + Current loop

** The Magnetic Field of a Current

- Consider a short segment of current \(I\).

- The current \(I\) in the segment of length \(\Delta s\) represents the motion of positive charge carriers through the wire:
  \[(\Delta Q)\vec{v} = \Delta Q \frac{\Delta \vec{s}}{\Delta t} = \frac{\Delta Q}{\Delta t} \Delta \vec{s} = I \Delta \vec{s}\]

- From the Biot-Savart law for a single charge \(q = \Delta Q\) the magnetic field \(d\vec{B}\) arising from an infinitesimal current element \(\Delta s\) is
  \[d\vec{B}_{\text{current segment}} = \frac{\mu_0}{4\pi} \frac{I \Delta \vec{s} \times \hat{r}}{r^2}\]

- By the superposition principle, the field of a finite current follows by integrating:
  \[\vec{B} = \int d\vec{B} = \int \frac{\mu_0}{4 \pi} \frac{I d\vec{s} \times \hat{r}}{r^2}\]

** The Magnetic Field of a Long Straight Wire (Example 1)

Find an expression for the magnetic field produced at a point P by a long straight wire carrying steady current \(I\).

Interpret.

- We split the wire into pieces and use the superposition principle.

- Predict: the field is out of the page.

Represent.

- I, y, \(\vec{B}(P) = \;?\) Sketch with a CS: x-axis horizontal, the y-axis vertical

Develop.

- The field contribution \(d\vec{B}\) from a current element of length \(ds\) to the net field at a point \(P(x,y)\) is \(d\vec{B} = db \;\hat{k}\), where the strength \(dB\)
 (\(\Delta s \sin{\theta} = ds \frac{y}{r}\))

\[d\vec{B}_{\text{current segment}} = \frac{\mu_0}{4 \pi} \frac{I \Delta \vec{s} \times \hat{r}}{r^2} \implies dB = \frac{\mu_0 I}{4 \pi} \frac{y \;dx}{(x^2 + y^2)^{3/2}}\]

- Integrating the contributions \[db = \frac{\mu_0 I}{4\pi} \frac{y \;dx}{(x^2 + y^2)^{3/2}\]
  along an infinite line from \(-\infty\) to \(+\infty\) and using
  \[\int \frac{dx}{(x^2 + a^2)^{3/2}} = \frac{x}{a^2 \sqrt{x^2 + a^2}}\]
  gives
  \[B = \int dB = \frac{\mu_0 Iy}{4\pi} \int_{-\infty}^{\infty} \frac{dx}{(x^2 + y^2)^{3/2}} = \frac{\mu_0 I}{2 \pi y} = \frac{2 k' I}{y}\]

- Assess.

  + The field falls off as the inverse of the distance \(y\) from the wire.

  + At P, the direction is out of the page (the z-axis)

  + The field encircles the current.

  + Their direction agrees with the RHR for straight wire.

** The Magnetic Field of a Current Loop

- Fact: The next simplest and common circuit geometry is a current flowing around a circle

  \[\vec{B}(P) = \frac{\mu_0 I a^2}{2(x^2 + a^2)^{3/2}} \hat{i}\]

1. For large distances \(|x| \gg a\)
   \[B = \frac{\mu_0}{2\pi} \frac{IA}{|x|^3}\]

2. \[B_{\text{coil center}} = \frac{\mu_0}{2} \frac{NI}{R}\]

** RHR for the Magnetic Fields from Currents

- Question: How to predict the direction of the magnetic field produced by a current in a loop?

- Answer: We can generalize the RHR for the magnetic fields from a current in a straight wire or in a loop.

- Imagine your right hand is grasping the wire so that your right thumb points the same way as the current.

- Your fingers curl the same way as the circular magnetic field surrounding the wire.

** Example 3 (Exercise 29.17 b)

A 100A current circulates around a 2.0mm diameter superconducting ring.
Find the on-axis magnetic field strength (in T) 5.0 cm from the ring.

Interpret. What is the problem about?

1) The problem involves on-axis field of a ring, a large distance away (5 cm \(\gg\) 1 mm).

2) CS with x along the axis and perpendicular to the ring surface.

Represent.

- a = 0.001 m
- I = 100A
- k' = 10^-7 T
- B_ring(x=0.05)=?
- Sketch with an appropriate CS (x is the ring axis)

Develop.

- B_ring(x=0.05)=? See Eq.(29.9) far away.
  \[B_{\text{ring}} = \frac{2 k' I A}{|x|^3}\]

** Problem 1 (29.54 CALC)

Part of a long wire carrying current \(I\) is bent into a semicircle of radius a, as in Fig. below.
Use the Biot-Savart law to find an expression for the magnetic field at P, the center of the semicircle.

Interpret.

1) Split the wire into 3 segments and then use the principle of superposition adding the fields of the segments

2) Use the Biot-Savart law for each segment

3) Choose CS (see) with the x axis along the straight line segments, y vertical up, z axis into the page.

4) Predict: SC only. Its field is into the page.

Represent.

- a, I; target \(\vec{B}_{\text{net}} = \;?\)

Develop.

1) \(\vec{B}_{\text{net}} = \;?\) Superposition + the B-S law for the semicircle gives:
   \begin{align*}
   \vec{B}_{\text{net}} &= \vec{B}_{\text{left}} + \vec{B}_{\text{right}} + \vec{B}_{\text{SC}} \\
   &= \vec{B}_{\text{SC}} \\
   &= \frac{\mu_0I}{4\pi} \int_{\text{SC}} \frac{d\vec{l} \times \hat{r}}{a^2} \\
   &= \int_0^{\pi} \frac{r \;d\theta}{a^2} \hat{k} \\ &= \frac{\mu_0 I}{4\pi} \left(\frac{\pi a}{a^2}\right) \hat{k} \\
   &= \frac{\mu_0 I}{4a} \hat{k}
   \end{align*}

2) \(\hat{r}\) is to the center and \(\hat{k}\) into the page (use RHR for the cross product)

Assess.

- The strength decreases with the radius.

** Problem 2 (29.43)

What is the strength and direction of the magnetic field at the center of the loop in figure below?

Interpret.

1) Superposition of two known fields of loop and long wire:

   \[B_{\text{coil center}} = \frac{\mu_0}{2} \frac{NI}{R}\]

   \[B_{\text{wire}} = \frac{\mu_0}{2\pi} \frac{I}{r} \quad \text{(long, straight wire)}\]

2) Predict: both fields are into the page.

Represent.

- k' = 10^-7
- I = 5.0 A
- a = R = 0.01 m
- B_net(P) = ?

Develop.

B_net = B_coil + B_wire

** In-Class Problem 2

A single piece of wire carrying current I is bent so it includes a circular loop of a radius a, as shown in Fig. below.
Find an expression for the magnetic field vector at the loop center.

Interpret.

Represent.

Develop.

Evaluate.

Assess.

* Unit 9 - Part 3 - Mar 19

** What You're Learning

- Reading Assignment: 29.5 and 29.6

- Review of Part 2

- About magnetic dipoles

- About Ampere's law

** Summary: Magnetism - Part 2

- Basic fact: The magnetic field of a current is described by the Biot-Savart law:
  \[\vec{B} = \int d\vec{B} = \int \frac{\mu_0}{4 \pi} \frac{I d\vec{L} \times \hat{r}}{r^2}\]

- Fields of simple current distributions:

  + Long, straight line current - the field a distance r from the wire is

  + Its direction is given by the RHR

    \[B_{\text{wire}} = \frac{\mu_0}{2\pi} \frac{I}{r} \quad\text{(long, straight wire)}\]

** A Current Loop is a Magnetic Dipole

Question: Why the magnetic field of a loop is important?

- The far away on-axis magnetic field of a loop has the same \(\frac{1}{|x|^3}\) dependence is as the inverse cube dependence of the electric field of an electric dipole on the axis:
  \[E = \frac{2kp}{|x|^3} \Leftrightarrow B = \frac{\mu_0}{4\pi} \frac{2I\pi a^2}{|x|^3}\]

- So we say by analog: A current loop is a magnetic dipole.

  + Its dipole moment is \(\mu = IA\), with \(A\) the loop area.
    For an \(N\)-turn loop, \(\mu = NIA\).
    Recall \(k = \frac{1}{4\pi \epsilon_0}\) and \(\frac{\mu_0}{4\pi} = k'\).

- Thus, the far away on-axis magnetic field of a loop can be re-written in terms of \(\mu\), even more like the electric field of an electric dipole.

  \[E = \frac{2kp}{|x|^3} \Leftrightarrow B = \frac{2k'\mu}{|x|^3}\]

** The Magnetic Dipole Moment

- Fact: We can convert dipole moment into a vector.

- The direction of the dipole moment vector is perpendicular to the loop area.

- Def: The magnetic dipole moment of a current loop enclosing an area A is defined as a vector:
  \[\vec{\mu} = (AI, \text{ from the south pole to the north pole)}\]

- Take the scalar Eq. 29.9
  \[B = \frac{2k' \mu}{|x|^3}\]

- Fact: It has the same direction as the on-axis magnetic field of a current loop:
  \[\vec{B}_{\text{dipole}} = \frac{\mu_0}{4\pi} \frac{2\vec{\mu}}{|z^3|}\]

** Example 1 (29.7)

What is the current in a 3.0-mm diameter superconducting loop if the axial magnetic field is 9.0 \(\mu\)T at a distance of 2.5 cm?

Interpret.

- The measurements are done far enough from the loop that we can model the magnetic field as a magnetic dipole (\(x \gg a = R\))

Represent.
Develop.

1) \(I = \;?\) We can use the definition of magnetic dipole moment to find \(I\):
   \[\mu = IA \implies I = \frac{\mu}{A} = \frac{\mu}{\pi a^2}\]

2) \(\mu = \;?\) The model of the loop as a magnetic dipole (\(x \gg a = R\)), Eq. 29.9 gives the magnetic moment:
   \[B = \frac{2k'\mu}{|x|^3} \implies \mu = \frac{x^3 B}{2k'}\]

3) Final expression: \[I = \frac{x^3 B}{k' 2\pi a^2}\]

Evaluate.

\[I = \frac{x^3 B}{k' 2\pi a^2} = \frac{0.025^3 \cdot 9 \cdot 10}{3.14 \cdot 2 \cdot 0.0015^2} = 99.52229 \approx 99 \text{ A}\]

Assess.

- Superconductor.

** Problem 1 (Problem 29.18)

A small, square loop carries a 25 A current.
The on-axis magnetic field strength 50 cm from the loop is 7.5 nT.
What is the edge length of the square?

Interpret.

1) We assume that the size of the loop is much smaller than 50 cm, so that the problem is about the magnetic dipole moment.

Represent.

- B=7.5e-9 T, I = 25 A, x=0.050 m, target L = ?

Develop.

1) L = ? Geometry area of a square A = L^2
2) A = ? We can use the definition of magnetic dipole moment to find A:
   \[\mu = IA \implies A = \frac{\mu}{I}\]
3) \(\mu = \;?\) The model of the loop as a magnetic dipole (\(x \gg a = R\)),
   Eq. 29.9 gives the magnetic moment:
   \[B = \frac{2k'\mu}{|x|^3} \implies \mu = \frac{x^3 B}{2k'}\]
4) Final expression for A: \(A = \frac{x^3 B}{2k' I}\)

Evaluate.

- 1.4 cm

Assess.

- 1.4 cm edge length is much smaller than 50 cm

** Ampere's Law - an Introduction

- Recall: Gauss's law for electric field:

- Analogously, Ampère's law provides a global description of the magnetic field in relation to its source = moving charge / current.

- Fact: Ampere's law = the Biot-Savart law.

  + Gauss' law involves a surface integral: \(\oint \vec{E} \cdot d\vec{A}\)
    over a closed surface

  + Ampère's law involves a line integral: \(\oint \vec{B} \cdot d\vec{r}\)
    around a closed loop

  + For steadty currents, Ampère's law says
    \[\oint \vec{B} \cdot d\vec{s} = \mu_0 I_{\text{through}}\]
    where the integral is taken around ANY closed loop surrounding the current, and \(I_{\text{through}}\) is the NET current encircled by that loop, piercing through.

** Line Integrals

- Figure (a) shows a curved line from \(i\) to \(f\).

- For example, the length of this line can be found by doing a line integral:
  \[l = \sum_k \Delta s_k \to \int_i^f \;ds\]

* Unit 9 - Part 4 - Mar 22

** What You're Learning

Reading Assignment: 29.6 and 29.7

1. The magnetic field

** Summary: Magnetism - Part 3

- For steady currents, Ampère's law says
  \[\oint \vec{B} \cdot d\vec{s} = \mu_0 I_{\text{through}}\]
  where the integral is taken around ANY closed loop surrounding the current, and \(I_{\text{through}}\) is the NET current encircled by that loop.

** The Magnetic Field of a Solenoid

- Fact: Third important current/field configuration is a solenoid.

- Def: A solenoid is a long, tightly wound coil of wire.

- Q: What is the magnetic field of this source?

- Answer: Based on the superposition principle (see above) we can predict as follows:

  + Inside: the field is uniform except near the ends.

  + Outside: the field outside is very small.

- Simple Model: In the case of an infintely long solenoid (ILS):
  the magnetic field: (a) outside is zero and (b) inside is uniform:

- Q: How to find the magnitude of the field inside?

- Answer from Ampère's law: The field is uniform, so the line integral along the whole CCW rectangle as shown is B*L along the path inside.

- Our path encircles a total current = N*I

- So Ampère's law gives:
  Circulation integral = BL = μ_0*N*I = μ_0*n*L*I

- Assess: The field B is directly proportional to I and n = # of turns per unit length of the solenoid of any cross section

  \[B_{\text{solenoid}} = \frac{\mu_0 NI}{l} = \mu_0 n I \quad \text{(solenoid)}\]

- Q: How to determine the direction of B produced in a solenoid?

- RHR (#3, for solenoid): Imagine your right hand grasping the solenoid so that your fingers curl the same way as the current.
  Then, your thumb will then point to the north pole of the solenoid/loop.

** The Magnetic Force on a Moving Charge

- Consider a point charge q moving with the velocity \(\vec{v}\)

- Fact: 2nd Fundamental Law of Magnetism holds:
  the magnetic field exerts a force on a moving charge:
  \[\vec{F} = q\vec{v} \times \vec{B}\]

- Prediction: An electric current consists of moving charges, so a current-carrying conductor placed in a magnetic field, should experience a magnetic force too.

- The magnitude of mag. force is: \[F = qv B \sin{\theta}\]

- The magnitude Eq. defines the units of B: N/(A·m)

- SI primary unit of B: 1T (Tesla): 1T = 1N/A·m

- Fact: 1T is a quite large field!

- A smaller unit--the Gauss: 1G = 10^-4 T is often used.

** Problem 2 (Exercise 29.27 (a))

An electron moves with a speed of \(1.0 \times 10^7\) m/s in the magnetic field of 0.50 T directed along the positive x-axis.
(a) Find the magnetic force \(\vec{F}\) on the electron in a vector form.
(b) Form the dot products: \(\vec{F} \cdot \vec{B}\) and \(\vec{F} \cdot \vec{v}\) to show explicitly that the force is perpendicular to both \(\vec{B}\) and \(\vec{v}\).

Develop.

(a) F = ? 2nd law of magnetism and cross product:
\(\vec{F} = q\vec{v} \times \vec{B} = -evB(-\hat{k}) \times \hat{i} = evB \hat{j}\)

(b) \(\vec{v} \cdot \vec{V} = \;?\) and \(\vec{B} \cdot \vec{F} = \;?\) Definition of dot-product and \(\hat{i}\), \(\hat{k}\) perp. \(\hat{j}\).
\[\vec{v} \cdot \vec{F} = 0 \text{ and } \vec{B} \cdot \vec{F} = 0\]

Evaluate.

(a) F = e*v*B = 8.0 * 10^-13 N and the direction along the y-axis.

Assess.

- We checked that the answer is reasonable as far as the direction is concerned.

** Cyclotron Motion

- Consider: \(\vec{F} = q\vec{v} \times \vec{B}\)

- Notice: \(\vec{F}\) is always at right angles to \(\vec{v}\)

- Assess. it changes the direction of motion but not the speed.

- Special case: If a positive charge is moving in a plane perpendicular to uniform \(B_{\text{out}}\), it undergoes CW uniform circular motion -called the cyclotron motion.

- Q: What is the radius of the circle?

- A: From Newton 2nd law: F=m*a*m*v^2/r we obtain:
  \[F = qvB = \frac{mv^2}{r} \implies r = \frac{mv}{qB}\]

- Assess. The radius: r ~ mv, r ~ 1/q, r ~ 1/B

- Q: What's the period T of a particle's circular orbit?

- A: Using Eq. 29.20, the answer, given as cyclotron frequency, is
  \[\frac{2\pi r}{T} = v \implies f = \frac{1}{T} = \frac{v}{2\pi r} = \frac{v}{2\pi (mv / qB)} = \frac{qB}{2\pi m}\]

- Assess. Remarkably, f does not depend on v = the charge's speed.
  Only the q/m & B matter!

- Generalization: When the particle has a component of \(\vec{v}\) along the field, its path, in uniform B, is not a circle but a spiral.

- Solve problem 29.65 (PSW) where the velocity has two components.
  The perpendicular component is responsible for the circular motion, and the parallel component is responsible for the uniform motion along the magnetic field direction.

** Charged Particles in Magnetic Fields

- Fact: A device called a mass spectrometer separates ions (see d values) according to their q/m ratio.

- Q: How does it work?

- The device has two parts.
  The sample is ionized...

- The + ions of charge q and mass m are accelerated from rest through a potential difference \(=\Delta V\).
  \[COE: K_i + qV_i = K_f + qV_f \implies \frac{1}{2} mv^2 = qV_i\]

- Then, they follow a CW (q > 0) circular path in uniform magnetic field (out of the page).
  After half an orbit, they land on a detector.

- Let us find an expression for \(d\).

- Develop.

  + Use the COE to find v

  + Use Newton's 2nd law and solve for d = 2r.
    \[F = qvB = \frac{mv^2}{r} \implies r = \frac{mv}{qB} \implies d = 2r = \frac{2mv}{qB} = 2 \sqrt{\frac{2mV}{qB^2}}\]

- Assess. For a fixed V & B, d depends only on q/m.

** Problem 3 (Example 29.11)

An electron is accelerated from rest through a potential difference of 500 V, then injected into a uniform magnetic field (into the page).
Once in the magnetic field, it completes half a revolution in 2.0 ns.
What is the radius of its orbit?

Interpret.

- An electron is accelerated from rest through a potential difference, then it makes a CW uniform circluation in an into the page uniform magnetic field.

Represent.

Develop.

1) r = ? Recall Eq. 29.20 the radius of the orbit is
   \[r = \frac{mv}{eB}\]

2) B = ? We can find B from the period/frequency relation (Eq. 29.21):
   \[f = \frac{1}{T} = \frac{eB}{2\pi m}\]

3) Solving for B one gets: \(B = \frac{2\pi m}{eT}\)

4) v = ? From the COE: \(K_f = eV_f = 0 \implies v = \sqrt{2e \cdot V/m}\)

5) Final expression for the target: \(r = \frac{T}{2\pi} \sqrt{2 eV / m}\)

Evaluate.

\[r = \frac{T}{2\pi} \sqrt{2 eV / m} = 0.009199 \approx 9.2 \text{ mm}\]

Assess.

1) The answer in mm and 2 sig. figs. The answer in the text 8.5 mm

2) A 18 mm orbit is a typical size for a modest B.

** Charged Particles in E&M Fields

- Q: What happens when both E and B fields are present?

- Fact: Both an electric force \(\vec{F}_E\) and magnetic force \(\vec{F}_B\) add up:
  \[\vec{F} = \vec{F}_E + \vec{F}_B = q\vec{E} + q\vec{v} \times \vec{B}\]

- Prediction: When fields are perpendicular, and \(\vec{v}\) is at right angle to both, the \(F_E\) and \(F_B\) are antiparallel.

- Consider E field to the right and B field down.
  A charge q enters at right angle to both (into the page).

- The F_E and F_B are antiparallel and cancel each other when
  \[qE = qvB\]
  so only particles with speed \(v = E/B\) pass through the region undeflected.

- Assess. So the device acts as a velocity selector.

** Problem 4 (Problem 29.59)

An electron travels with speed 1.0 * 10^7 m/s between the two parallel charged plates shown in the Figure below.
The plates are separated by 1.0 cm and are charged by a 200 V battery.
What magnetic field strength (in mT) and direction will allow the electron to pass between the plates without being deflected?

Interpret.

1) The problem is about an electron passing through perpendicular and uniform fields without deflection.

2) In this case, the electric and magnetic forces have to cancel each other.
   This is the equation to be used to find the magnetic field strength.

Represent.

- m_e = m = 9.11*10^-31 kg
- q = -e
- e = 1.6*10^-19 C
- v = 1.0*10^7 m/s
- V = 200V
- d = 0.01 m
- targets: B = ? direction of B = ?

Develop.

1) B = ? Undeflected means v = E/B => B = E/v
2) E = ? Uniform electric field between charged plates distance d apart (Unit 6):
   \[\Delta V = E \cdot d \implies E = \Delta V / d\]
3) Final expression: the magnitude \(B = \frac{\Delta V}{d v}\)
   From RHR, the B field is into the page X

Evaluate.

\[B = \frac{\Delta V}{d v} = \frac{200}{(10^5)}\text{ T} = 2.0 \text{ mT}\]

Assess.

- The field is weak so we use mT.

* Unit 9 - Part 5 - Mar 26

** Summary: Magnetism - Part 5

- Recall: 2nd Fundamental Law of Magnetism:
  the magnetic field exerts a force on a moving charge
  \[\vec{F} = q\vec{v} \times \vec{B}\]

- Prediction:
  An electric current consists of moving charges

** The Magnetic Force on a Current

- Consider a segment of length \(L\) in uniform \(\vec{B}\).

- In the segment, the charge carriers are moving with drift velocity \(v_d\).
  They have total charge \(Q\).

- If a wire of length \(L\) contains a current \(I = \frac{Q}{\Delta t}\), it means a charge \(Q\) must move the distance \(L\) in a time \(\Delta t\):
  \[\Delta t = \frac{L}{v_d}\]

- Thus, we have a relationship: \(Q v_d = (I \Delta t) v_d = IL\)

- Since \(\vec{F}_q = q\vec{v} \times \vec{B}\) and field is uniform, the net magnetic force on a current-carrying segment is
  \[\vec{F} = I \vec{L} \times \vec{B}\]

- We defined \(\vec{L}\) to point in the direction of \(\vec{v}_d\) and \(I\).

- Note: If field is not uniform we can use Eq. 29.26 in infinitesimal form:
  \[d\vec{F} = I d\vec{\ell} \times \vec{B}\]

** Problem 1 (Example 29.13)

The 0.10 T uniform magnetic field of Figure below is horizontal, parallel to the floor.
A straight segment of 1.0-mm-diameter copper wire, also parallel to the floor, is perpendicular to the magnetic field.
What current through the wire, and in which direction, will allow the wire to "float" in the magnetic field?

Interpret.

1) The question is about the magnetic force balancing the weight.
   This provides the equation to find the current.

2) Also the problem deals with a piece of wire with mass uniformly distributed over the cylinder.

3) Predicted in QC#1: the current is left to right.

Represent.

- \(\rho_{Cu} = 8920\)

- r = 0.0005 m

- B = 0.10 T

- I = ?

Develop.

1) I = ? Floating: \(F_B = F_G \implies ILB = mg\)

2) m = ? The concept of uniform density:
   \(m = V \rho_{Cu} \implies ILB = \rho_{Cu} V g\)

3) V = ? Geometry: volume of a cylinder: \(V = L\pi r^2\)

4) Final expression \[I = \frac{\rho \pi r^2 g}{B}\]

Evaluate.

\[I = (8920)(3.14)(0.0005^2)(9.8) / (0.10) \approx 0.69 \text{ A}\]

Assess.

1) Typical small current in A.

2) 2 sig. figs.

** Problem 2 (Exercise 29.35)

The right edge of the circuit in Figure extends into a 50 mT uniform magnetic field.
What are the magnitude (in mN) and direction of the net force on the circuit?

Interpret.

1) The current is flowing CW.
   There is magnetic forces on three segments, so we have to calculate the net magnetic force on the circuit.

2) The net force on the top and bottom segments is zero-why?

3) For the third (right) segment, use the magnetic force on a straight wire in a uniform field (Eq. 29.26)

Represent.

- V = 15V, R = 3Ω, L = 0.10m, B = 50*10^-3 T
- Target: F = ?

Develop.

1) F = ? Direction = ? Eq. 29.26 \(F = ILB\) Direction to the right.

2) I = ? Ohm's law \(I = \mathcal{E} / R\)

3) Final exrpession \[F = \mathcal{E} L B / R\]

Evaluate.

\[F = \mathcal{E} L B / R = (15)(0.1)(50\cdot 10^{-3}) / 3 = 25 \text{ mN to the right}\]

Assess.

- Small force is reasonable.
- In mN.
- 2 sig. figs.

** Problem 4 (Wolfson 26-57) (CALC)

A wire carrying 1.5 A passes through a 48-mT magnetic field.
The wire is perpendicular to the field and makes a quarter-circle turn of radius 21 cm in the field region, as shown in Fig.
Find the magnitude and direction of the magnetic force on the curved section of wire.

Interpret.

1) Magnetic force on a small straight segment
2) Superposition principle <--> integrating

** Magnetic Force Between Parallel Wires

- Consider two parallel wires with currents, both up

- Q: How do they interact?

- Answer: Parallel currents attract each other.

** Magnetic Force Between Parallel Wires

- Q: What is the magnitude of the attractive force between two parallel wires?
  Find an expression for the magnitude.

- A: Let us work out the answer:

  + The strength \(B_1\) produced at the position of wire 2 due to the current in wire 1 is:
    \[B_1 = \frac{\mu_0}{2\pi} \frac{I_1}{d}\]

  + Then, this field (into the page x, perpendicular to L) exerts a force on a length \(L_2\) of wire 2.

  Then, the force is \[\vec{F}_L = I\vec{L} \times \vec{B}\]

- Subsituting the strength \(B_1\), we obtain:
  \[F_2 = \frac{\mu_0}{2 \pi} \frac{I_1 I_2} d L_2\]

** Magnetic Force Between Parallel Wires

- Q: What is a typical value involved in Eq. 29.27?
  For I = 1A d = 1m

- Q: How is the constant \(\mu_0\) in (26-11) exactly \(4 \pi \times 10^{-7}\)?

** Problem 3 (G28.18)

A rectangular loop of wire is placed next to a straight wire, as shown in the figure.
There is a current of 3.5 A in both wires.
Determine the direction and magnitude of the net force (in μN) on the loop.

Interpret.

1) There are four segments, so the problem is about the net magnetic force on the circuit.

Develop.

1) \(F_{\text{net}} = \;?\) Vector subtraction = \(F_{\text{net}} = F_{\text{near}} - F_{\text{far}}\)
2) \(F_{\text{near}} = \;?\) and \(F_{\text{far}} = \;?\)
   We use Eq. 29.27 \(F = \frac{2 k' L I_1 I_2}{d}\)
3) Final expression \[F_{net} = 2k' L I_1 I_2 \left(\frac{1}{d_{\text{near}}} - \frac{1}{d_{\text{far}}}\right)\right)\]

** Forces and Torques on Loops

- Recall from Part 3: A current loop is a magnetic dipole.

- PREDICTION: If magnetic dipoles are the magnetic analog of electric dipoles, so they should experience (a) no net force in a uniform B, but (b) the net torque trying to align its dipole moment along B.

  + Consider a square loop \(L \times L\) with a steady current \(I\) in uniform \(B\), making angle \(\theta\) with the field

** In-class problem #4

A conducting bar of length \(L\) and mass \(m\) rests at the left end of the two frictionless rails of length \(d\) in Figure below.
A uniform magnetic field of strength \(B\) points upward.
(a) In which direction (into or out of the page), will a current \(I\) through the conducting bar cause the bar to experience a force to the right?
(b) Find an EXPRESSION for the bar's speed as it leaves the rails at the right end.

* Unit 10 - Part 1 - Mar 29

** What You're Learning

- Reading Assignment: 30.1-30.3 and 30.5

- About the experiments leading to the discovery of EM induction

- How to calculate the magnetic flux

- Using Faraday's law, to calculate induced emfs and induced currents

** Induced Currents

- Q: If electric currents produce magnetic fields, is the reverse possible?

- In another wordes, is it possible that a magnetic field can produce an electrical current in a wire (no battery)?

** Faraday's 1831 Discovery

- Fact: Almost 200 years ago, Faraday and Henry performed four different experiments providing an evidence of induced electric currents produced by changing magnetic fields:

  + move a magnet near a circuit

  + move the circuit near a magnet

  + move a electromagnet near a circuit

  + change current nearby

** Induced Currents in a Circuit

- Q: What is common in all these experiments called EM induction?

- Explanation for all four cases: An induced current appears in a loop only if the number of lines of magnetic field that pass through that loop is changing

- Recall: It takes a force (=EMF) on charge particles to drive electric current, so we can say:
  An induced EMF appears in a loop only if the number of lines

** Magnetic Flux

- Q: What counts the number of lines of \(\vec{B}\) that pass through a loop?

- Recall (from Units 5 & 9): Key fact: the density of field lines at a given location is proportional to the field strength \(B\) at that location:

  - \(\vec{B} \cdot d\vec{A}\) = the number of lines through a patch with the area dA

- From this, we can answer the above question:

- The magnetic flux of \(\vec{B}\) through a loop counts the total number of lines passing through that loop:
  \[\Phi_{\text{m}} = \underset{\text{area of loop}}{\int} \vec{B} \cdot d\vec{A}\]

- SIMPLE MODEL: In this course, we will assume a FLAT surface and a UNIFORM field.
  With this model, the flux becomes:
  \[\Phi_{\text{m}} = \underset{\text{area of loop}}{\int} \vec{B} \cdot d\vec{A} \implies \Phi_{\text{m}} = A_{\text{eff}} B = AB \cos{\theta}\]

- \(\theta\) = the angle between \(\vec{B}\) and the normal vector \(\vec{A} = A\hat{n}\)

- ASSESS: \(\Phi_{\text{m}}(A)\) measures the amount of magnetic field passing through an area \(A\) of a loop if the loop is tilted at an angle \(\theta\) from the field.

- ASSESS: Only \(A_{\text{eff}}\) (\(=A_{\perp}=A\cos{\theta}\)) component to \(\vec{B}\) matters!
  \[\Phi_{\text{m}} = A_{\text{eff}} B = AB \cos{\theta}\]

- Three variables determine the value of \(\Phi_{\text{m}}\): \(B\), \(A\) and \(\theta\)

- Units of the flux: 1 weber = 1 WB = 1 T·m^2

- ASSESS: Two new predictions (from \(A\) and \(\theta\) dependence):

- \(\Phi_{\text{m}}\) will change not only if the loop rotates but also when it expands or contracts

** Example 1 (Exercise 30.7)

What is the magnetic flux through the loop shown in the Figure?

Interpret.

1) About the concept of flux.
2) B is uniform and perpendicular to the loop
3) B is confined to a rectangle \(a \times b\)

Represent.

- a, b, B, target \(\Phi_{\text{m}} = \;?\)

Develop.

1) \(\Phi_{\text{m}} = \;?\) From the simple uniform model
   \[\Phi_{\text{m}} = B\cdot A_{\text{eff}} = B a \cdot b\]

Assess.

1) Correct dimensions (Wb)

** Problem 1 (Example 30.5)

A long, straight wire carries current \(I\).
A rectangular wire loop of dimensions \(a \times b\) lies in a plane containing the wire, with its closest edge a distance a from the wire and its dimension b parallel to the wire.
Find an expression for the magnetic flux through the loop.

Interpret.

1) The field is non-uniform and out of the page.
   Simple model Eq. 30.9 is not applicable.

2) B is of a long straight wire--it varies with x-distance from the wire

3) We will use the integral definition of flux.

Represent.

- a, b, Target: \(\Phi_{\text{m}} = \;?\)

Develop.

1) \(\Phi_{\text{m}} = \;?\) Integral model: \(\Phi_{\text{m}} = \int d \Phi_{\text{m}}\)
2) \(d\Phi_{\text{m}} = \;?\) Now field is uniform over the strip \(dx\)
   \[d\Phi_{\text{m}} = B(x) b \cdot dx = \frac{\mu_0 b I}{2\pi} \frac{dx}{x}\]
3) Final expression Integral definition.
   We evaluate the integral from \(x = a\) to \(x = 2a\)
   \[\Phi_{\text{m}} = \int B \;dA = \frac{\mu_0 b I}{2\pi} \ln{2}\]

Assess.

1) Correct dimensions (Wb)

** Faraday's Law

- Now we can formulate Faraday's law of inductino in terms of the magnetic flux:
  An emf is induced in a conducting loop if the magnetic flux through the loop changes.

- The magnitude of the emf is
  \[\mathcal{E} = \left|\frac{d\Phi_{\text{m}}}{dt}\right|\]

- The direction of the emf (\(\pm\)) is such as to drive an induced current in the direction given by Lenz's law (see Part 2)

** Using Faraday's Law: Motional EMF

- Example 2: If we slide a conducting wire along a U-shaped conducting rail, we can complete a circuit and drive an induced electric current.

- Develop.
  We can find the induced emf (motional) and current by using Faraday's law and Ohm's law:
  \begin{align*}
  \mathcal{E} &= \left|\frac{d\Phi_{\text{m}}}{dt}\right| = \frac{d}{dt} (xlB) = \frac{dx}{dt} lB = vlB \\
  I &= \frac{\mathcal{E}}{R} = \frac{vlB}{R}
  \end{align*}

- Assess.
  This is exactly the same conclusion we could reach if we analyzed the situation from the perspective of magnetic force on moving charge carriers (see Sec.30.2)

** Problem 2 (Problem 30.37)

A 20 cm × 20 cm square loop has a resistance of 0.10 Ω.
A mangetic field perpendicular to the loop is \(B = 4t - 2t^2\), where \(B\) is in tesla and \(t\) is in seconds.
what is the current in the loop at \(t = 0.0 \text{ s}\)?

Interpret.

1) About Faraday's law when the flux is changing due to the magnetic field changing in time \(B(t)\)

Represent.

Develop.

1) \(I(0) = \;?\) Ohms law \[I(0) = \frac{\mathcal{E}(0)}{R}\]

2) \(\mathcal{E}(0) = \;?\) Faraday's law and definition of flux in the simple uniform model:
   \[\mathcal{E}(0) = \frac{d(B \cdot A)}{dt} (0) = A (4 - 4t) \Big|_0\]

3) \[I(0) = \frac{A(4)}{R}\]

Evaluate.

\[I(0) = 1.6 A\]

Assess.

1) The rate of change is large so the induced current is large too.
2) 2 sig. figs.
3) Units (solve)

** Problem 3 (Problem 30.47)

Figure shows a 1.0-cm-diameter loop with R=0.50 Ω inside a 2.0-cm-diameter solenoid.
The solenoid is 8.0 cm long, has 120 turns, and carries the current shown in the graph.
Determine the current in the loop at t = 0.010 s.

Interpret.

1) About the current induced in a loop placed in uniform magnetic field of solenoid, when the flux is changing due to the magnetic field of the solenoid changing in time.

Represent.

- \(R_{\text{loop}} = 0.005 \text{ m}\)
- \(r_{\text{sol}} = 0.01 \text{ m}\)
- \(R = 0.50 \;\Omega\)
- \(L = 0.8 \text{ m}\)
- \(N = 120\)
- From the graph: \(\frac{dl_{\text{sol}}}{dt} (0.01) = 50 \text{ A/s}\)
- The target: \(I(0.01) = \;?\) Make a sketch

Develop.

1) \(I(0.01) = \;?\) Ohm's Law: \(I(0.01) = \frac{\mathcal{E}(0.01)}{R}\)
2) \(\mathcal{E}(0.01) = \;?\) Faraday's law and definition of flux in the simple model:
   \[\mathcal{E}(0.01) = \left|\frac{d(B_{\text{sol}} \cdot A_{\text{loop}})}{dt} (0.01)\]
3) \(\frac{B_{\text{sol}}}{dt} = \;?\) Magnetic field in solenoid and we differentiate it
   \[\frac{B_{\text{sol}}}{dt} = \mu_0 \left(\frac{N}{L}\right) \left(\frac{dl_{\text{sol}}}{dt}\right)\]
4) Final expression: \[I(0.01) = A_{\text{loop}} \cdot \mu_0 \left(\frac{N}{L}\right) \left(\frac{dl_{\text{sol}}}{dt}\right) \frac{1}{R}\]

Evaluate.

\[I = \mu_0 A_{\text{loop}} \left(\frac{N}{RL}\right) \left(\frac{dl_{\text{sol}}}{dt}\right) = 147.894 \cdot 10^{-7} \approx 1.5 \times 10^{-5} \text{ A}\]

Assess.

- 15 \(\mu\text{A}\) is reasonable value of induced current.
- 2 sig. figs.

* Unit 10 - Part 2 - Mar 31

** What You're Learning

- Reading Assignment: 30.4-30.7

** Summary (Part 1) - Faraday's Law

- Faraday's law: An emf is induced in a conducting loop if the magnetic flux through the loop changes.
- The magnitude of the emf is \(\mathcal{E} = \left|\frac{d\Phi_B}{dt}\right|\)
- Magnetic flux (uniform B and flat A):
  \[\Phi_B = B_{\perp} A = BA \cos{\theta}\]

** Lenz's Law

- Q: How to find the direction of the induced EMF and the induced current?

- Consider a bar magnet pushed toward a loop increases the flux through the loop.
  Which direction is the induced current?

- Lenz's Law: an induced current always moves in a direction that its magnetic field opposes the original change of flux.

- In the above example, the N pole of the magnet approaches the loop.
  So a CCW induced current turns the loop into  a magnet with upward-pointing magnetic field, opposing the approaching magnet.

** Lew's Law

- Q: How to apply Lenz's law to determine for the direction of current induced in a loop?

- Follow these three steps:

  + Determine whether the magnetic _flux_ is

    - increasing

    - decreasing

    - unchanged

  + The magnetic field due to the induced current points

    - in the opposite direction to the original \(\vec{B}\) if the flux is increasing;

    - in the same direction as the original \(\vec{B}\), if the flux is decreasing; and

    - is zero if the flux is not changing.

  + Once you know the direction of the induced field, use the RHR for \(\vec{B}\) to determine the direction of the induced _current_.

** Practice with Lenz's Law

- Example 1: In which direction is the current induced in the circular loop for each situation in figures below?

- Hint: use the procedure above the appropriate RHR for \(\vec{B}\) of a loop

- Answers: (a) CCW (b) CW

** Applying the Faraday's Law

A 2.0 cm × 2.0 cm square loop of wire with resistance 0.010 Ω has one edge parallel to a long straight wire.
The near edge of the loop is 2.0 cm from the wire.
The current in the wire is increasing at the rate of 100 A/s.
What is the current in the loop (just the value; direction was opposite to one in QC#2)?

Interpret.

1) Assume the wire is long enough so we can use the formula for the magnetic field of an "infinite" wire.

2) The field is non-uniform.
   Recall Problem 1 (Example 30.9) fomr Part 1.
   To calculate the flux of that field, we have to split the flat surface into narrow strips

Represent.

- b=c=a=0.02m, T=0.010Ω, dl/dt=100A/s; target I=?

Develop.

\[I = \frac{\mathcal{E}{R} = \frac{1}{R} \frac{d}{dt} \ln{2}\]]

** Induced Electric Fields

- Consider a /conducting loop/ in an increasing magnetic field

- According to Lenz's law, there is an induced current in the CCW direction.

- Q: What provides the induced EMF in a conducting loop?

- Something has to act on the charge carriers to make them move, so we infer that there must be an induced electric field \(\vec{E}\) tangent to the loop at all points.

- Since EMF is the work /per unit charge/ (recall Unit 6) done as charge goes around a closed loop, so Faraday's law becomes:
  \[\mathcal{E} = \left|\frac{d\Phi}{dt}\right| = A \left|\frac{dB}{dt}\right| \implies \oint \vec{E} \cdot d\vec{s} = A \left|\frac{dB}{dt}\right|\]

- Here, the integral = the field circulation, is around the conducting loop, and the flux is through any loop

** Induced Electric Fields

- Generalization:
  An induced electric field \(\vec{E}\) results whenever a magnetic field changes with time, whether or not an electric circuit is present.

- Below is a generalization of Faraday's law (without the absolute value) - valid with or also without conducting loop:
  \[\oint \vec{E} \cdot d\vec{s} = -\frac{d\Phi_m}{dt}\]

- Eq. 30.27 is a general statement of Faraday's law that relates the induced electric field \(\vec{E}\) to the changing magnetic field \(\vec{B}(t)\).

- Note: Lenz's law is incorporated in the minus
 sign.

** Example 1 (Problem 30.63)

Find an expression for the induced electric field outside a solenoid (\(r > R\)) in which the magnetic field is changing at the rate \(\frac{dB}{dt}\).

Interpret.

1) The problem involves the generealized form of Faraday's law - Eq 30.23
2) The solenoid is long with magnetic field confined to its interior.
3) The induced electric field is circumferential.

Represent.

- r, R, dB/dt, target E(r)=?

Develop.

1) E(r)=? From Faraday's law:
   \[\oint\vec{E} \cdot d\vec{s} = A \left|\frac{dB}{dt}\right|\]
   and using the field circumferential symmetry we obtain
   \[2\pi r E(r) = A \frac{dB}{dt}\]

2) A=? Geometry-circle + the fact that the field B is confied to the interior of the solenoid:

3) Final expression: \[E(r) = \frac{R^2}{2r} \frac{dB}{dt}\]

ASSESS.

1) Are units of the expression OK?

** Problem 2 (Exercise 30.19)

The magnetic field in Figure EX30.19 is decreasing at the rate 0.10 T/s.
What is the acceleration (magnitude and direction) of a proton initially at rest at point c?

Interpret.

1) Newton's 2nd law
2) Field force relationship
3) The problem involves the generalized form of Faraday's law - Eq. 30.23

Represent.

- m=1.67×10^-27 kg

Develop.

1) a=? Newton's 2nd law + force field relationship: \(F = eE = ma\)
   \[a = \frac{eE(r)}{m}\]
2) \(E(r) =\;?\) From Example 1: \[E(r) = \frac{r}{2} \frac{dB}{dt}\]
   where \(r\) indicates the radial distance between point 'c' and the center
3) Final expression: \[a = \frac{e}{m} \frac{r}{2} \frac{dB}{dt}\]

Evaluate.

\[a = 4.8 \cdot 10^4 \text{ m/s}^2, \text{ direction down}\]

Assess.

- Units m/s^2
- 2 sig figs

* Unit 10 - Part 3 - Apr 2

** What You're Learning

- Reading Assignment: 30.7 - 30.8

** Summary Unit 10 - Part 1 and Part 2

- Magnetic flux

- Faraday's law

- An induced electric field is due to a change of magnetic flux

** Mutual Inductance

- Recall from Part 1: there are many ways to change magnetic flux through a circuit

- Mutual inductange: a changing current in one coil will induce a current in a second coil

- From Faraday's law for coil 2 (\(B_1 = \mu_0 n I_1\)):
  \[\mathcal{E}_2 = -M_{21} \frac{dI_1}{dt}\]

- Def: the constant \(M\), known as the mutual inductance
  \[M_{21} = \Phi_2 / I_1\]

- Fact: \(M\) depends only on geometrical factors of the two coils.

** Example 1 (Problem 30.48 (b))

Interpret.

1) mutual induction in #2 due to change of \(I_1\) in #1

2) The field of long solenoid

3) Faraday's law

Represent.

- \(d_w = 0.001 \text{ m}\)

- \(N_2 = N_1 = 20\)

- \(\frac{dI_1}{dt} = 20 \frac{1}{s}\)

- target \(\mathcal{E}_2 = \;?\)

Develop.

1) \(\mathcal{E}_2 = \;?\) Faraday's law and uniform flux:
   \[\mathcal{E}_2 = N_2 \left|\frac{d\Phi_2}{dt}\right| = N_2 A_2 \left|\frac{dB_1}{dt}\right|\]
2) \(\frac{dB_1}{dt} = \;?\) Long solenoid model for the coil:
   \[\frac{dB_1}{dt} = \frac{N_1 \mu_0}{L_1} \frac{dI_1}{dt}\]
3) \(n_1 = \;?\) Def of density \[n_1 = \frac{N_1}{L_1} = \frac{1}{d_w}\]
4) \[\mathcal{E}_2 = N_2 \left|\frac{d\Phi_2}{dt}\right| = \frac{N_2 \pi r^2 \mu_0}{d_w} \left|\frac{dI_1}{dt}\right|\]

Evaluate.

\[\mathcal{E}_2 \approx 0.16 \text{ mV}\]

Assess.

- 2 sig. figs. and mV units, small induced voltage.

** More about Mutual Inductance

- The SI units of \(M\) are \(\text{T m}^2 / \text{A}\) or henry:
  \[1 \text{ H} = 1 \text{ V}\cdot\text{s/A} = 1 \;\Omega \cdot \text{s}\]

- Fact: In reverse situation, the same constant \(M_{12} = M_{21} \equiv M}\) enters:
  \[\mathcal{E}_1 = -M \frac{dI_2}{dt}\]

- Fact: a transformer is an example of mutual inductance.

- The principle of operation: two coils (linked by an iron core) with primary coil connected to an AC power supply (required!)

** Self-Inductance

- Fact: A changing (increasing) current in a coil will also induce an emf \(\mathcal{E}_L\) in itself:
  \[\mathcal{E}_L = -L \frac{dI}{dt}\]

- Here, \(L\) (not length) is called the self-inductance of an inductor
    \[L = \Phi / I\]

- Example 3: A long solenoid of cross-section \(A\) and length \(\ell\) has \(n\) turns per unit length.
  Find its self-inductance.

- Develop. Using the uniform model of flux and \(B = \mu_0 n I\) we get:
  \[L = \frac{\Phi}{I} = \frac{NBA}{I} = \mu_0 N^2 A}{l} = \mu_0 n^2 Al\]

** Magnetic Energy in an Inductor

- Fact: Recall from Unit 6, energy can be stored in an electric field of a capacitor, also energy can be stored in a magnetic field in an inductor (think of long coil = solenoid.)

- When the current in an inductance \(L\) is \(I\), the energy stored is given by
  \[U = \frac{1}{2} LI^2\]

** Magnetic Energy Density

- In Eq. 30-33
  \[B = \mu_0 n I\]
- Eq. 30-39 then gives the magnetic energy stored in a solenoid carrying a current \(I\) as
  \[U = \frac{1}{2} LI^2 = \frac{1}{2} \frac{B^2}{\mu_0} Al\]
- so the energy per unit volume (\(A\ell\)) = the magnetic energy density is
  \[u_B = \frac{B^2}{2\mu_0}\]
- Fact: This is a universal expression: where ever there's a magnetic field, there's energy with density:
  \[\frac{B^2}{2\mu_0}\]
- Recall: The energy density in an electric field:
  \[u_E = \frac{1}{2} \mathcal{E}_0 E^2\]

** Example 5 (Exercise 30.28)

Interpret.

1) Assume the solenoid is long enough that we can approximate the field as being constant inside and zero outside.

Represent.

- \(r_{sol}\) = 0.20 m
- L = 1.0 m
- I = 100 A
- B = 5.0 T
- \(u_B = \;?\)

Develop.

1) \(u_B = \;?\) Def. magnetic energy density
   \[u_B = \frac{B^2}{2\mu_0}\]

Evaluate.

\[u_B = 10. \text{ MJ/m}^3\]

Assess.

- 2 sig. figs

** ICP #2

A 1250-turn solenoid 23.2 cm long and 1.58 cm in diameter carries 165 mA.
How much magnetic energy (in μJ) does it contain?

Interpret.

Represent.

Develop.

Evaluate.

Assess.

* Unit 11 - Part 1 - Apr 5

** Introduction

- Question: What is the goal of Unit 11?

- Important fact: Everything you've learned up to now in your studies of E&M can be summarized in FOUR integral equations for fields called Maxwell's equations and

  \begin{align*}
    \oint \vec{E} \cdot d\vec{A} &= \frac{Q_{\text{in}}}{\epsilon_0} &\text{Charged particles create an electric field.} \\
    \oint \vec{B} \cdot d\vec{A} &= 0 &\text{There are no isolated magnetic poles.} \\
    \oint \vec{E} \cdot d\vec{s} &= -\frac{d\Phi_{\text{m}}}{dt} &\text{An electric field can also be created by a changing magnetic field.} \\
    \oint \vec{B} \cdot d\vec{s} &= \mu_0 I_{\text{through}} &\text{Currents create a magnetic field.}
  \end{align*}

  \[\vec{F} = q(\vec{E} + \vec{v} \times \vec{B}) \quad \text{(Lorentz force law)}\]

- Fact: But Ampere's law is still incomplete because it holds only for steady currents.

** Maxwell's Correction to Ampere's Law

- Consider a capacitor being charged from a battery.

- Curve C is a closed curve encircling the wire on the left.

- Surface \(S_1\) has \(I_{\text{through}} = I\)

- Surface \(S_2\) has \(I_{\text{through}} = 0\)

- Question: Is Ampere's Law wrong or incomplete?

- Answer: The problem is with the right side of Ampère's law

- Hint #1: We incorrectly put 0 when applied to surface \(S_2\)

- Hint #2 (Recall FL + symmetry): We could expect that a /changing electric field/ flux can create /magnetic field/ as well

- The electric field is \[E = \frac{Q}{\epsilon_0 A}\]

- The electric flux (\(S_2\)) \[\Phi_{e} = EA = \frac{Q}{\epsilon_0}\]

- The rate the \(\Phi_e (S_2)\) is changing, is
  \[\frac{d\Phi_e}{dt} = \frac{1}{\epsilon_0} \frac{dQ}{dt} = \frac{I}{\epsilon_0}\]

- Eq. 31.19 suggests that \(\frac{\epsilon_0 d\Phi}{dt}\) is equivalent to current \(I_{\text{through}}\).

- Final solution: Maxwell added a correction term to Ampere's Law using what he called the displacement current \(\frac{\epsilon_0 d\Phi}{dt}\):
  \[\oint \vec{B} \cdot d\vec{s} = \mu_0 (I_{\text{through}} + I_{\text{disp}}) = \mu_0 \left(I_{\text{through}} + \epsilon_0 \frac{d\Phi_e}{dt}\right)\]

** The Ampere-Maxwell Law

- Assess: The A-M Law states that a changing electric flux through a closed loop or an electric current piercing through the loop creates a magnetic field around the loop:
  \[\oint \vec{B} \cdot d\vec{s} = \mu_0(I_{\text{through}} + I_{\text{disp}}) = \mu_0 \left(I_{\text{through}} + \epsilon_0 \frac{d\Phi_e}{dt}\right)\]
  where the circulation of \(\vec{B}\) is around the closed curve that bounds the surface through which the elecric flux is changing and/or current is piercing through.

- Assess: This equation means that
    a magnetic field can be created either by an electric current or by a changing electric field.

** Example 1 (Example 31.3)

A 2.0cm-diameter parallel-plate capacitor with 1.0 mm spacing is being charged at the rate of 0.50 C/s at some instant in time.
What is the induced magnetic field strength (in μT) 0.50 cm radially outward from the center of the plates?

Develop.

1) \(B(r) = \;?\) From the A-M Eq. (31.21) + circumferential symmetry:
   \[2\pi r B(r) = \frac{\mu_0 \epsilon_0 d\Phi_e}{dt}\]

2) \(\frac{d\Phi_e}{dt} = \;?\) The electric flux \(\Phi_e\) through the circle of \(r < R_p\) is
   \[{\Phi_e}^{(t)} = \pi r^2 E(t)\]

3) \(E(t) = \;?\) The electric field in a capacitor is
   \[E(t) = \frac{\eta}{\epsilon_0} = \frac{Q}{\epsilon_0 A_p}\]

4) Final expression: \[B(r) = \mu_0 \frac{r}{2\pi {R_p}^2} \frac{dQ}{dt} = \mu_0 \frac{r}{2\pi {R_p}^2} I\]

Evaluate.

\[B = 5.0 \;\mu\text{T}\]

Assess.

- In Unit 9, we've seen a current carrying wires with \(I \approx 1 \text{ A}\) producing fields of a few \(\mu\)T.
  So the answer is reasonable.

** Maxwell's Equations in Vacuum

- Now, consider empty space (=vacuum) case: \(q = 0\) and \(I = 0\)

- In vacuum, there's no electric charge and therefore no electric current.

- Fact: Then there's complete symmetry between electric and magnetic fields.

- Now the only source of either type of field is change in time of the other type of field.

** Plane EM Waves

- Fact: The simplest solution of Maxwell's equations in empty space is a plane EM wave, (wavefronts are infinite planes).

- Def: A plane wave consists of E & M fields that vary in space only in the direction of the wave propagation (here x-axis).

  \begin{align*}
    \vec{E}(x,t) &= E_p \sin{(kx - \omega t)} \hat{j} \\
    \vec{B}(x,t) &= B_p \sin{(kx - \omega t)} \hat{k}
  \end{align*}

- Assess.

  + The wave moves along \(x > 0\) axis.

  + The fields are perp. to each other and to the direction of propagation

  + \(\vec{E} \times \vec{B}\) is in the direction of propagation (x-axis)

  + It is a plane wave for which, at a given moment, the fields are the same at every point in a yz-plane slicing the x-axis

  + The field strengths vary with x.

* Unit 11 - Part 2 - Apr 7

** Review Part 1: Maxwell's Equations in a Vacuum

- Recall the empty space (=vacuum) case: \(q = 0\) and \(I = 0\).

- In vacuum, there's no electric charge and therefore no electric current.

- Now the only source of either type of field is change in time of the other type of field.

** Review Part 1: Plane EM Waves

- Fact: The simplest solution of Maxwell's equations in empty space is a plane EM wave.

- Definition: A plane wave consists of E&M fields that vary in space ONLY in the direction of the wave propagation (here x-axis).

  \begin{align*}
    E_y &= E_0 \sin{(kx - \omega t)} \\
    B_z &= B_0 \sin{(kx - \omega t)}
  \end{align*}

- Assess:

  + The wave moves along \(x > 0\) axis.

  + The fields are perpendicular to each other and to the direction of propagation.

  + The cross product \(\vec{E} \times \vec{B}\) is in the direction of propagation.

  + The planarity means that at any given moment \(t\), the fields are the same at every point in a \(yz\)-plane slicing the \(x\)-axis (see LEFT).

  + The field strengths vary with \(x\) (see RIGHT).

** Properties of Plane EM Waves

  \begin{align*}
    E_y &= E_0 \sin{(kx - \omega t)} \\
    B_z &= B_0 \sin{(kx - \omega t)}
  \end{align*}

- Assess:
  There are 3 parameters characterizing the plane wave

- \(k\) = the wave number describing the variation of the field strengths with \(x\)

- \(w\) = the angular frequency describing the time variation at a fixed point in space

- \(v\) = the speed of the wave

  \[k = \frac{2\pi}{\lambda}, \quad \omega = 2 \pi f, \text{ and } f \lambda = \frac{\omega}{k} = v\]

** The EM Spectrum (Read Only)

- Fact: EM waves come in a vast range of frequencies and wavelengths, from low-frequency, long-wavelength radio waves (left) through very high-frequency, short-wavelength gamma rays (right).

- Fact: Visible light occupies the wavelength range from about 400 nm to 700 nm.

** Plane EM Waves-continued

- Fact: The plane wave in Equations (31.37) satisfies Maxwell's equations in a vacuum if the wave speed is given by
  \[v = \frac{\omega}{k} = \frac{1}{\sqrt{\mathcal{E}_0 \mu_0}} = c = 3.0 \times 10^8 \text{ m/s}\]

- This is precissely the speed of light in vacuum.

- So light is an EM wave

- Optics is a branch of E&M

- In addition: Faraday's Law requires the relationship between the field strengths \(E\) and \(B\):
  \[E = \frac{\omega}{k} B = cB \implies E_0 = cB_0\]

- Assess: Any peak field values called also the amplitudes (\(E_0\) and \(B_0\)) are possible, provided they are related as in 31.38 and any frequency or wavelength is possible, provided \(\frac{\omega}{k} = c\) or equivalently \(f \lambda = c\).

** Example 1 (Exercise 31.14)

The magnetic field of an EM wave in a vacuum is \(B_z = (3.00 \mu T) \sin{[(1.00 \times 10^7) x - \omega t]}\), where \(x\) is in m and \(t\) is in s.
(a) Find the wave's wavelength (in nm), (b) frequency (in Hz), (c) the electric field amplitude (in V/m).

Hint: From Lorentz force: Units of \(E_0\) are T m/s = V/m

Interpret.

- This is an EM wave along the x axis moving with v = c.

Represent.

- \(k = 1.00 \times 10^7 \text{ m}^{-1}\)
- \(c = 3.00 \times 10^8 \text{ m/s}\)
- \(B_0 = 3.00 \times 10^{-6} \text{ T}\)
- Targets: \(\lambda = \;?\), \(f = \;?\), \(E_0 = \;?\)
- Sketch: \(E\) along \(y\)

Develop.

1) \(\lambda = \;?\) From the relation \(\lambda = \frac{2 \pi}{k}\)
2) \(f = \;?\) From Equation \(f \lambda = c \implies f = \frac{ck}{2\pi}\)
3) \(E_0 = \;?\) From Equation 31.38 \(E_0 = cB_0\)

Evaluate.

\[\lambda = 628 \text{ nm}, f = 4.77 \times 10^{14} \text{ Hz}, E_0 = 900 \text{ V/m}\]

Assess.

- Why is the wavelength reasonable? Because it is rather weak.

** Producing Electromagnetic Waves (Read Only)

- Fact: EM waves are generated by accelerated electric charges.

- Defailts of emitting systems depend on wavelength, wiith most efficient emitters being roughly a wavelength in size.

- Radio waves are generated by alternating currents in metal antennas (see the sketch).

- Molecular vibration and rotation produce infrared waves.

- Visible light arises largely from atomic-scale processes.

- X-rays are produced in the rapid deceleration of electric charge.

- Gamma rays result from nuclear processes.

** Energy in EM Waves

- Fact: The energy flow of an EM wave is described by the Poynting vector:

  \[\vec{S} \equiv \frac{1}{\mu_0} \vec{E} \times \vec{B}\]

- Three facts about the Poynting vector:

  + \(S\) points in the direction in which an EM wave is traveling

  + Units of \(S\) are \(\text{W/m}^2\) (units of intensity)

  + Physical interpretation: Consider total energy in the box with volume \(A \;dx\):
    \[dU = (u_E + u_B) A \;dx = \left(\frac{B^2}{2\mu_0} + \frac{1}{2} \mathcal{E}_0 E^2\right) A \;dx \implies EB \frac{1 + c^2 (\mathcal{E}_0 \mu_0)}{2 c\mu_0} A c \;dt\]

    - Recall definition of \(u_B\) and \(u_E\) then use: \(E = cB\) and \(c^2 = \frac{1}{\mathcal{E}_0 \mu_0}\)

- All the energy moves out of the box at a time \(dt = \frac{dx}{c}\), so we get for \(S\) (= the instantaneous intensity) of a plane EM wave:
  \[S = \frac{1}{A} \frac{dU}{dt} = \frac{E \cdot B}{\mu_0}\]

- Fact: The Poynting vector is a function of time, oscillating from zero to \(S_{\text{max}} = \frac{B_0 E_0}{\mu_0} = \frac{{E_0}^2}{c \mu_0}\) and back to zero, twice during each period of the wave's oscillation.

- So, of more interest is the average energy transfer, averaged over one cycle of oscillation, which is the wave's intensity \(I\).

- The average intensity of a P-EM wave (recall \(E_0 = cB_0\)) is
  \[S(t) = \frac{E(t) B(t)}{\mu_0} \implies S_{\text{avg}} = \frac{E_0 B_0}{2 \mu_0} = \frac{E_0 E_0}{2c \mu_0}\]

  \[I = \frac{P}{A} = S_{\text{avg}} = \frac{1}{2c \mu_0} {E_0}^2 = \frac{c \epsilon_0}{2} {E_0}^2\]

- Assess. Relates \(I\) to \(E_0\), a quantity easy to measure.

** Spherical EM Waves

- Fact: A plane wave is an idealization, valid far away from a point source.

- Close to the source, more practical model is spherical wave with the power emitted uniformly in all directions.

- From COE for a point source:
  \[P_{\text{source}} = P(r_1) = P(r_2) = P(r)\]

- Dividing by the area of a sphere, one gets:
  \[S_{\text{avg}} = \frac{P_{\text{source}}}{4 \pi r^2}\]

- Assess. The intensity of a spherical EM waves at a distance \(r\) away from an isotropic source is determined by power \(P_{\text{source}}\)
  \[I = \frac{P_{\text{source}}}{4 \pi r^2}\]

* Unit 11 - Part 3 - Apr 9

** Review Part 2: Plane EM Waves

- Assess. There are 3 parameters characterizing the plane wave in Eq.31.37

  + \(k\) = the wave number: \(k = \frac{2\pi}{\lambda}\)

  + \(\omega\) = the angular frequency: \(\omega = 2\pi f\)

  + \(v\) = the speed of the wave is the speed of light in vacuum \[v = \frac{\omega}{k} = \frac{1}{\sqrt{\epsilon_0 \mu_0}} = c = 3.0 \times 10^8 \text{ m/s}\]

- In addition: the field strengths \(E\) and \(B\) are related:
  \[E = \frac{\omega}{k} B = cB \implies E_0 = cB_0\]

** Review Part 2: Energy in EM Waves

- Fact: A measure of energy in EM waves is the time average intensity of a plane EM wave is
  \[I = \frac{P}{A} = S_{\text{avg}} = \frac{1}{2c \mu_0} {E_0}^2 = \frac{c\epsilon_0}{2} {E_0}^2\]

- Assess. Eq.31.40 relates \(I\) to \(E_0\)--a quantity easy to measure.

- A plane wave is an idealization, valid far away from a point source.

- Close to the source, more practical model is spherical wave, with power emitted uniformly in all directions.

- From the COE, the intensity \(I\) of a spherical EM waves at a distance \(r\) away from an isotropic source with power \(P_{\text{source}}\) is
  \[I = \frac{P_{\text{source}}}{4\pi r^2}\]

** Problem 1 (31.44)

The intensity of sunlight reaching the earth (\(R_{\text{sun-earth}} = 1.50 \times 10^{11} \text{ m}\)) is \(1360 \text{ W/m}^2\).
What is the intensity of sunlight on Mars (\(R_{\text{sun-Mars}} = 2.28 \times 10^{11} \text{ m}\))?

Interpret.

1) Sun as a point emitter far away
   (\(R_{\text{earth}} = 6.37 \times 10^6 \text{ m}\), \(R_{\text{Sun}} = 6.96 \times 10^8 \text{ m}\))
2) Sunlight is a spherical, uniform EM wave.
3) Predict: is the intensity of sunlight on Mars is smaller than on Earth

Represent.

- \(r_{SE} = 1.50 \times 10^{11} \text{ m}\)
- \(r_{SM} = 2.28 \times 10^{11} \text{ m}\)
- \(I_E = 1360 \text{ W/m}^2\)
- \(I_M = \;?\)

Develop.

- \(I_M = \;?\) Both intensities are related by Eq. 31.41
  \[I_i = \frac{P_s}{4\pi r^2} \implies {r_{SE}}^2 I_E  = {r_{SM}}^2 I_M \implies I_M = I_E \left(\frac{r_{SE}}{r_{SM}}\right)^2\]

Evaluate.

\[I_M = I_E \left(\frac{r_{SE}}{r_{SM}}\right)^2 = 588.6 \approx 589 \text{ W/m}^2\]

Assess.

- \(I_M\) is smaller than \(I_E\)

** Problem 2 (31.45)

Assume that 7.0-cm-diameter, 100 W lightbulb radiates all its energy as a single wavelength of visible light.
Estimate the electric field strengths at the surface of the bulb.

Interpret.

1) The problem is about the peak value = amplitude of the electric field

2) Assume that filament is a point source of spherical wave that becomes plane EM wave on the surface of the bulb.

Represent.

- \(r = 0.035 \text{ m}\)
- \(P_{\text{source}} = 100 \text{ W}\)
- \(c = 3.0 \times 10^8\)
- \(\mu_0 = 4\pi \times 10^{-7}\)
- \(E_0 = \;?\)

Develop.

- \(E_0 = \;?\)
  \[I(r) = I_{PEM} = \frac{P}{A} = S_{\text{avg}} = \frac{{E_0}^2}{2c \mu_0} \implies E_0 = \sqrt{2c I(r) \mu_0\]

- \(I(r) = \;?\) Uniform, spherical
  \[I(r) = \frac{P_{\text{source}}}{4\pi r^2}\]

- Final exp.
  \[E_0 = \sqrt{2c \mu_0 \frac{P_{\text{source}}}{4\pi r^2}\]

Evaluate.

- \(E_0 = 2213 \approx 2000 \text{ V/m}\)

Assess.

- "estimate" means 1 sig. fig. in V/m.

** Momentum in EM Waves

- Fact: EM waves also carry momentum.

- Model: Suppose we shine a beam of light on an object that completely absorbs the light energy.

- Maxwell showed that the momentum transfer (\(\Delta p\)) to the object and the energy transfer (\(\Delta E\)) are related:
  \[\Delta p = \text{energy absorbed} / c\]

- Consider the force on an object per unit area called the radiation pressure (\(p_{\text{rad}}\)) that is related to the energy absorbed. See p. 895 for a derivation.

- For the object that absorbs all the light the pressure is
  \[p_\text{rad} = \frac{F}{A} = \frac{P/A}{c} = \frac{I}{c}\]
  where \(I\) is the intensity of light EM wave.

- Fact: Radiation pressure doubles if an object reflects EM wave.

** Problem 3 (31.51)

The intensity of sunlight reaching the earth is 1360 W/m^2.
Assuming all the sunlight is absorbed, what is the radiation-pressure force (in newtons) on the earth?

Interpret.

- The pressure exerts a force on a flat area.
- To make it solvable, we assume that sunlight is absorbed by effective area equal to a flat circle of radius \(R_{\text{earth}}\).

Represent.

- \(R_{\text{earth}} = 6.37 \times 10^6 \text{ m}\)
- \(I = 1360 \text{ W/m}^2\)
- \(c = 3.0 \times 10^8\)
- \(F_{\text{rad}} = \;?\)

Develop.

- \(F_{\text{rad}} = \;?\) Radiation pressure equation
  \[p_{\text{rad}} = \frac{F}{A} \implies F = p_{\text{rad}} A\]

- \(p_{\text{rad}} = \;?\) Radiation pressure equation
  \[p_{\text{rad}} = \frac{I}{c}\]

- \(A = \;?\) Area of a circle
  \[A = \pi {R_{\text{earth}}}^2\]

- Final exp.
  \[F_{\text{rad}} = \frac{I}{c} A = \frac{I}{c} \pi {R_{\text{earth}}}^2\]

Evaluate.

\[F_{\text{rad}} \approx 5.87 \times 10^8 \text{ N}\]

Assess.

- Compare this with \(F_{\text{grav}}\) of the sun
* Unit 12 - Part 3 - Apr 16

** Images with Lenses - Introduction

- Def: A lens is a piece of transparent material that uses refraction to form images.
- There are two kinds of lenses:
  + converging lenses which bring parallel rays to a focus.
  + diverging lenses which bend parallel rays so they appear to diverge from a focus.
